%//[CREB, CREBBP, SST, NRAS, EGF, EGFR, CLIP1, CLIP2, Ras, CRTC2, CRTC1, CREBZF, GATA1, CRTC3, TCAP, CAP, NCBP1, CTIF, NCBP2]
transcription_factor('CREB').
protein('CREB').
transcription_factor('CREBBP').
protein('CREBBP').
enzyme('CREBBP').
protein('SST').
ligand('EGF').
%protein('EGF').
receptor('EGFR').
protein('EGFR').
enzyme('EGFR').
transcription_factor('CLIP1').
protein('CLIP1').
protein('CLIP2').
ligand('Ras').
protein('Ras').
enzyme('Ras').
transcription_factor('CRTC2').
protein('CRTC2').
transcription_factor('CRTC1').
protein('CRTC1').
transcription_factor('CREBZF').
protein('CREBZF').
transcription_factor('GATA1').
protein('GATA1').
transcription_factor('CRTC3').
protein('CRTC3').
protein('TCAP').
enzyme('TCAP').
transcription_factor('CAP').
protein('CAP').
protein('NCBP1').
protein('CTIF').
protein('NCBP2').

%las siguientes lineas son para evitar errores en el proceso no deben ser modificadas
enzyme('').
protein('').
transcription_factor('').
receptor('').
ligand('').
