wkr_ligand('').
wkr_proteins('').
wkr_transcription_factors('').
wkr_adaptor_proteins('').
wkr_receptors('').
wkr_enzymes('').
wkr_somatostatin(X):-wkr_somatostatin_28(X).
wkr_pituitary_hormone_release_inhibiting_hormones(X):-wkr_somatostatin(X).
wkr_hypothalamic_hormones(X):-wkr_pituitary_hormone_release_inhibiting_hormones(X).
wkr_peptide_hormones(X):-wkr_hypothalamic_hormones(X).
wkr_hormones(X):-wkr_peptide_hormones(X).
wkr_hormones_hormone_substitutes_and_hormone_antagonists(X):-wkr_hormones(X).
wkr_chemicals_and_drugs_category(X):-wkr_hormones_hormone_substitutes_and_hormone_antagonists(X).
wkr_physiological_effects_of_drugs(X):-wkr_hormones_hormone_substitutes_and_hormone_antagonists(X).
wkr_pharmacologic_actions(X):-wkr_physiological_effects_of_drugs(X).
wkr_chemical_actions_and_uses(X):-wkr_pharmacologic_actions(X).
wkr_chemicals_and_drugs_category(X):-wkr_chemical_actions_and_uses(X).
wkr_peptides(X):-wkr_peptide_hormones(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_peptides(X).
wkr_chemicals_and_drugs_category(X):-wkr_amino_acids_peptides_and_proteins(X).
wkr_neuropeptides(X):-wkr_hypothalamic_hormones(X).
wkr_peptides(X):-wkr_neuropeptides(X).
wkr_nerve_tissue_proteins(X):-wkr_neuropeptides(X).
wkr_proteins(X):-wkr_nerve_tissue_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_proteins(X).
wkr_pancreatic_hormones(X):-wkr_somatostatin(X).
wkr_peptide_hormones(X):-wkr_pancreatic_hormones(X).
wkr_egf_family_of_proteins(X):-wkr_heparin_binding_egf_like_growth_factor(X).
wkr_intercellular_signaling_peptides_and_proteins(X):-wkr_egf_family_of_proteins(X).
wkr_ligand(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_peptides(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_proteins(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_biological_factors(X):-wkr_intercellular_signaling_peptides_and_proteins(X).
wkr_chemicals_and_drugs_category(X):-wkr_biological_factors(X).
wkr_receptor_protein_tyrosine_kinases(X):-wkr_erbb_receptors(X).
wkr_protein_tyrosine_kinases(X):-wkr_receptor_protein_tyrosine_kinases(X).
wkr_protein_kinases(X):-wkr_protein_tyrosine_kinases(X).
wkr_phosphotransferases_alcohol_group_acceptor_(X):-wkr_protein_kinases(X).
wkr_phosphotransferases(X):-wkr_phosphotransferases_alcohol_group_acceptor_(X).
wkr_transferases(X):-wkr_phosphotransferases(X).
wkr_enzymes(X):-wkr_transferases(X).
wkr_enzymes_and_coenzymes(X):-wkr_enzymes(X).
wkr_chemicals_and_drugs_category(X):-wkr_enzymes_and_coenzymes(X).
wkr_receptors_cell_surface(X):-wkr_receptor_protein_tyrosine_kinases(X).
wkr_receptors(X):-wkr_receptors_cell_surface(X).
wkr_membrane_proteins(X):-wkr_receptors_cell_surface(X).
wkr_proteins(X):-wkr_membrane_proteins(X).
wkr_receptors_growth_factor(X):-wkr_erbb_receptors(X).
wkr_receptors(X):-wkr_receptors_growth_factor(X).
wkr_receptors_peptide(X):-wkr_receptors_growth_factor(X).
wkr_receptors(X):-wkr_receptors_peptide(X).
wkr_receptors_cell_surface(X):-wkr_receptors_peptide(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_grb2_adaptor_protein(X).
wkr_adaptor_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_ligand(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_peptides(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_proteins(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_carrier_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_proteins(X):-wkr_carrier_proteins(X).
wkr_son_of_sevenless_proteins(X):-wkr_sos1_protein(X).
wkr_ras_guanine_nucleotide_exchange_factors(X):-wkr_son_of_sevenless_proteins(X).
wkr_guanine_nucleotide_exchange_factors(X):-wkr_ras_guanine_nucleotide_exchange_factors(X).
wkr_gtp_binding_protein_regulators(X):-wkr_guanine_nucleotide_exchange_factors(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_gtp_binding_protein_regulators(X).
wkr_son_of_sevenless_proteins(X):-wkr_sos2_protein_human(X).
wkr_bacterial_proteins(X):-wkr_orf13_protein_streptococcus_pneumoniae(X).
wkr_proteins(X):-wkr_bacterial_proteins(X).
wkr_lymphoproliferative_disorders(X):-wkr_autoimmune_lymphoproliferative_syndrome(X).
wkr_lymphatic_diseases(X):-wkr_lymphoproliferative_disorders(X).
wkr_hemic_and_lymphatic_diseases(X):-wkr_lymphatic_diseases(X).
wkr_diseases_category(X):-wkr_hemic_and_lymphatic_diseases(X).
wkr_immunoproliferative_disorders(X):-wkr_lymphoproliferative_disorders(X).
wkr_immune_system_diseases(X):-wkr_immunoproliferative_disorders(X).
wkr_diseases_category(X):-wkr_immune_system_diseases(X).
wkr_genetic_diseases_inborn(X):-wkr_autoimmune_lymphoproliferative_syndrome(X).
wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X):-wkr_genetic_diseases_inborn(X).
wkr_diseases_category(X):-wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X).
wkr_autoimmune_diseases(X):-wkr_autoimmune_lymphoproliferative_syndrome(X).
wkr_immune_system_diseases(X):-wkr_autoimmune_diseases(X).
wkr_transcription_factors(X):-wkr_crtc3_protein_rat(X).
wkr_proteins(X):-wkr_transcription_factors(X).
wkr_rap_gtp_binding_proteins(X):-wkr_rap1_gtp_binding_proteins(X).
wkr_monomeric_gtp_binding_proteins(X):-wkr_rap_gtp_binding_proteins(X).
wkr_gtp_binding_proteins(X):-wkr_monomeric_gtp_binding_proteins(X).
wkr_gtp_phosphohydrolases(X):-wkr_gtp_binding_proteins(X).
wkr_acid_anhydride_hydrolases(X):-wkr_gtp_phosphohydrolases(X).
wkr_hydrolases(X):-wkr_acid_anhydride_hydrolases(X).
wkr_enzymes(X):-wkr_hydrolases(X).
wkr_carrier_proteins(X):-wkr_gtp_binding_proteins(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_monomeric_gtp_binding_proteins(X).
wkr_cyclohexanols(X):-wkr_vomifoliol_9_o_arabinofuranosyl_1_6_glucopyranoside(X).
wkr_hexanols(X):-wkr_cyclohexanols(X).
wkr_fatty_alcohols(X):-wkr_hexanols(X).
wkr_alcohols(X):-wkr_fatty_alcohols(X).
wkr_organic_chemicals(X):-wkr_alcohols(X).
wkr_chemicals_and_drugs_category(X):-wkr_organic_chemicals(X).
wkr_lipids(X):-wkr_fatty_alcohols(X).
wkr_chemicals_and_drugs_category(X):-wkr_lipids(X).
wkr_cyclohexanes(X):-wkr_cyclohexanols(X).
wkr_cycloparaffins(X):-wkr_cyclohexanes(X).
wkr_hydrocarbons_alicyclic(X):-wkr_cycloparaffins(X).
wkr_hydrocarbons_cyclic(X):-wkr_hydrocarbons_alicyclic(X).
wkr_hydrocarbons(X):-wkr_hydrocarbons_cyclic(X).
wkr_organic_chemicals(X):-wkr_hydrocarbons(X).
wkr_macrocyclic_compounds(X):-wkr_cycloparaffins(X).
wkr_polycyclic_compounds(X):-wkr_macrocyclic_compounds(X).
wkr_chemicals_and_drugs_category(X):-wkr_polycyclic_compounds(X).
wkr_disaccharides(X):-wkr_vomifoliol_9_o_arabinofuranosyl_1_6_glucopyranoside(X).
wkr_oligosaccharides(X):-wkr_disaccharides(X).
wkr_polysaccharides(X):-wkr_oligosaccharides(X).
wkr_carbohydrates(X):-wkr_polysaccharides(X).
wkr_chemicals_and_drugs_category(X):-wkr_carbohydrates(X).
wkr_sugars(X):-wkr_disaccharides(X).
wkr_carbohydrates(X):-wkr_sugars(X).
wkr_raf_kinases(X):-wkr_proto_oncogene_proteins_b_raf(X).
wkr_map_kinase_kinase_kinases(X):-wkr_raf_kinases(X).
wkr_protein_serine_threonine_kinases(X):-wkr_map_kinase_kinase_kinases(X).
wkr_protein_kinases(X):-wkr_protein_serine_threonine_kinases(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_map_kinase_kinase_kinases(X).
wkr_proto_oncogene_proteins(X):-wkr_raf_kinases(X).
wkr_oncogene_proteins(X):-wkr_proto_oncogene_proteins(X).
wkr_neoplasm_proteins(X):-wkr_oncogene_proteins(X).
wkr_proteins(X):-wkr_neoplasm_proteins(X).
wkr_craniofacial_abnormalities(X):-wkr_noonan_syndrome(X).
wkr_musculoskeletal_abnormalities(X):-wkr_craniofacial_abnormalities(X).
wkr_musculoskeletal_diseases(X):-wkr_musculoskeletal_abnormalities(X).
wkr_diseases_category(X):-wkr_musculoskeletal_diseases(X).
wkr_congenital_abnormalities(X):-wkr_musculoskeletal_abnormalities(X).
wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X):-wkr_congenital_abnormalities(X).
wkr_heart_defects_congenital(X):-wkr_noonan_syndrome(X).
wkr_cardiovascular_abnormalities(X):-wkr_heart_defects_congenital(X).
wkr_cardiovascular_diseases(X):-wkr_cardiovascular_abnormalities(X).
wkr_diseases_category(X):-wkr_cardiovascular_diseases(X).
wkr_congenital_abnormalities(X):-wkr_cardiovascular_abnormalities(X).
wkr_heart_diseases(X):-wkr_heart_defects_congenital(X).
wkr_cardiovascular_diseases(X):-wkr_heart_diseases(X).
wkr_connective_tissue_diseases(X):-wkr_noonan_syndrome(X).
wkr_skin_and_connective_tissue_diseases(X):-wkr_connective_tissue_diseases(X).
wkr_diseases_category(X):-wkr_skin_and_connective_tissue_diseases(X).
wkr_pyrazoles(X):-wkr_pf_04880594(X).
wkr_azoles(X):-wkr_pyrazoles(X).
wkr_heterocyclic_compounds_1_ring(X):-wkr_azoles(X).
wkr_heterocyclic_compounds(X):-wkr_heterocyclic_compounds_1_ring(X).
wkr_chemicals_and_drugs_category(X):-wkr_heterocyclic_compounds(X).
wkr_pyrimidines(X):-wkr_pf_04880594(X).
wkr_heterocyclic_compounds_1_ring(X):-wkr_pyrimidines(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_lamtor3_protein_human(X).
wkr_mitogen_activated_protein_kinase_kinases(X):-wkr_map_kinase_kinase_1(X).
wkr_protein_serine_threonine_kinases(X):-wkr_mitogen_activated_protein_kinase_kinases(X).
wkr_protein_tyrosine_kinases(X):-wkr_mitogen_activated_protein_kinase_kinases(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_mitogen_activated_protein_kinase_kinases(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_ragulator_complex_protein_lamtor2_human(X).
wkr_guanine_nucleotide_exchange_factors(X):-wkr_lamtor4_protein_human(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_hbxip_protein_human(X).
wkr_p_type_atpases(X):-wkr_copper_transporting_atpases(X).
wkr_adenosine_triphosphatases(X):-wkr_p_type_atpases(X).
wkr_acid_anhydride_hydrolases(X):-wkr_adenosine_triphosphatases(X).
wkr_membrane_transport_proteins(X):-wkr_p_type_atpases(X).
wkr_carrier_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_membrane_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_cation_transport_proteins(X):-wkr_copper_transporting_atpases(X).
wkr_ion_pumps(X):-wkr_cation_transport_proteins(X).
wkr_membrane_transport_proteins(X):-wkr_ion_pumps(X).
wkr_receptors_somatostatin(X):-wkr_somatostatin_receptor_5(X).
wkr_receptors(X):-wkr_receptors_somatostatin(X).
wkr_receptors_g_protein_coupled(X):-wkr_receptors_somatostatin(X).
wkr_receptors(X):-wkr_receptors_g_protein_coupled(X).
wkr_receptors_cell_surface(X):-wkr_receptors_g_protein_coupled(X).
wkr_receptors_neuropeptide(X):-wkr_receptors_somatostatin(X).
wkr_receptors(X):-wkr_receptors_neuropeptide(X).
wkr_receptors_neurotransmitter(X):-wkr_receptors_neuropeptide(X).
wkr_receptors(X):-wkr_receptors_neurotransmitter(X).
wkr_receptors_cell_surface(X):-wkr_receptors_neurotransmitter(X).
wkr_receptors_peptide(X):-wkr_receptors_neuropeptide(X).
wkr_receptors_pancreatic_hormone(X):-wkr_receptors_somatostatin(X).
wkr_receptors(X):-wkr_receptors_pancreatic_hormone(X).
wkr_receptors_peptide(X):-wkr_receptors_pancreatic_hormone(X).
wkr_receptors_pituitary_hormone_regulating_hormone(X):-wkr_receptors_somatostatin(X).
wkr_receptors(X):-wkr_receptors_pituitary_hormone_regulating_hormone(X).
wkr_receptors_peptide(X):-wkr_receptors_pituitary_hormone_regulating_hormone(X).
wkr_microtubule_associated_proteins(X):-wkr_cytoplasmic_linker_protein_115(X).
wkr_microtubule_proteins(X):-wkr_microtubule_associated_proteins(X).
wkr_biopolymers(X):-wkr_microtubule_proteins(X).
wkr_polymers(X):-wkr_biopolymers(X).
wkr_macromolecular_substances(X):-wkr_polymers(X).
wkr_chemicals_and_drugs_category(X):-wkr_macromolecular_substances(X).
wkr_biomedical_and_dental_materials(X):-wkr_polymers(X).
wkr_chemicals_and_drugs_category(X):-wkr_biomedical_and_dental_materials(X).
wkr_specialty_uses_of_chemicals(X):-wkr_biomedical_and_dental_materials(X).
wkr_chemical_actions_and_uses(X):-wkr_specialty_uses_of_chemicals(X).
wkr_manufactured_materials(X):-wkr_biomedical_and_dental_materials(X).
wkr_technology_industry_and_agriculture(X):-wkr_manufactured_materials(X).
wkr_technology_and_food_and_beverages_category(X):-wkr_technology_industry_and_agriculture(X).
wkr_cytoskeletal_proteins(X):-wkr_microtubule_proteins(X).
wkr_proteins(X):-wkr_cytoskeletal_proteins(X).
wkr_nerve_tissue_proteins(X):-wkr_microtubule_associated_proteins(X).
wkr_carrier_proteins(X):-wkr_clip4_protein_human(X).
wkr_eukaryotic_initiation_factors(X):-wkr_ctif_protein_human(X).
wkr_peptide_initiation_factors(X):-wkr_eukaryotic_initiation_factors(X).
wkr_ribosomal_proteins(X):-wkr_peptide_initiation_factors(X).
wkr_proteins(X):-wkr_ribosomal_proteins(X).
wkr_rna_cap_binding_proteins(X):-wkr_nuclear_cap_binding_protein_complex(X).
wkr_rna_binding_proteins(X):-wkr_rna_cap_binding_proteins(X).
wkr_carrier_proteins(X):-wkr_rna_binding_proteins(X).
wkr_nucleoproteins(X):-wkr_rna_binding_proteins(X).
wkr_proteins(X):-wkr_nucleoproteins(X).
wkr_connectin(X):-wkr_tcap_protein_mouse(X).
wkr_protein_kinases(X):-wkr_connectin(X).
wkr_muscle_proteins(X):-wkr_connectin(X).
wkr_contractile_proteins(X):-wkr_muscle_proteins(X).
wkr_proteins(X):-wkr_contractile_proteins(X).
wkr_exoribonucleases(X):-wkr_pan2_protein_human(X).
wkr_exonucleases(X):-wkr_exoribonucleases(X).
wkr_esterases(X):-wkr_exonucleases(X).
wkr_hydrolases(X):-wkr_esterases(X).
wkr_ribonucleases(X):-wkr_exoribonucleases(X).
wkr_esterases(X):-wkr_ribonucleases(X).
wkr_gata1_transcription_factor(X):-wkr_gata1_protein_rat(X).
wkr_erythroid_specific_dna_binding_factors(X):-wkr_gata1_transcription_factor(X).
wkr_dna_binding_proteins(X):-wkr_erythroid_specific_dna_binding_factors(X).
wkr_proteins(X):-wkr_dna_binding_proteins(X).
wkr_transcription_factors(X):-wkr_erythroid_specific_dna_binding_factors(X).
wkr_gata_transcription_factors(X):-wkr_gata1_transcription_factor(X).
wkr_dna_binding_proteins(X):-wkr_gata_transcription_factors(X).
wkr_transcription_factors(X):-wkr_gata_transcription_factors(X).
wkr_homeodomain_proteins(X):-wkr_cdx1_protein_human(X).
wkr_dna_binding_proteins(X):-wkr_homeodomain_proteins(X).
wkr_cdx2_transcription_factor(X):-wkr_cdx2_protein_rat(X).
wkr_homeodomain_proteins(X):-wkr_cdx2_transcription_factor(X).
wkr_nuclear_proteins(X):-wkr_cdx2_transcription_factor(X).
wkr_proteins(X):-wkr_nuclear_proteins(X).
wkr_transcription_factors(X):-wkr_cdx2_transcription_factor(X).
wkr_p300_cbp_transcription_factors(X):-wkr_creb_binding_protein(X).
wkr_histone_acetyltransferases(X):-wkr_p300_cbp_transcription_factors(X).
wkr_lysine_acetyltransferases(X):-wkr_histone_acetyltransferases(X).
wkr_acetyltransferases(X):-wkr_lysine_acetyltransferases(X).
wkr_acyltransferases(X):-wkr_acetyltransferases(X).
wkr_transferases(X):-wkr_acyltransferases(X).
wkr_transcription_factors(X):-wkr_p300_cbp_transcription_factors(X).
wkr_basic_leucine_zipper_transcription_factors(X):-wkr_smile_protein_rat(X).
wkr_dna_binding_proteins(X):-wkr_basic_leucine_zipper_transcription_factors(X).
wkr_transcription_factors(X):-wkr_basic_leucine_zipper_transcription_factors(X).
wkr_transcription_factors(X):-wkr_crtc_protein_drosophila(X).
wkr_drosophila_proteins(X):-wkr_crtc_protein_drosophila(X).
wkr_insect_proteins(X):-wkr_drosophila_proteins(X).
wkr_arthropod_proteins(X):-wkr_insect_proteins(X).
wkr_proteins(X):-wkr_arthropod_proteins(X).
wkr_trans_activators(X):-wkr_crtc2_protein_rat(X).
wkr_dna_binding_proteins(X):-wkr_trans_activators(X).
wkr_transcription_factors(X):-wkr_trans_activators(X).
wkr_viral_regulatory_and_accessory_proteins(X):-wkr_trans_activators(X).
wkr_viral_proteins(X):-wkr_viral_regulatory_and_accessory_proteins(X).
wkr_proteins(X):-wkr_viral_proteins(X).
