base([
event('fatty acid',activate,'MYOD'),
event('MEF2',activate,'MYOD'),
event('RSRFC4',inhibit,'MEF2'),
event('MYOD',decrease,'E2F'),
event('MYOD',repress,'E2F'),
event('CAAT',bind,'CEBP'),
event('CAAT',bind,'CEBPA'),
event('CAAT',bind,'vitamin D analog'),
event('CAAT',bind,'GC'),
event('vitamin D analog',increase,'GC'),
event('GC',increase,'vitamin D analog'),
event('CAAT',bind,'CREB'),
event('progesterone analog',associate,'PPARA'),
event('vitamin D analog',bind,'MEF2'),
event('GC',bind,'MEF2'),
event('CAAT',bind,'MEF2'),
event('TATA',bind,'MEF2'),
event('MEF2',bind,'vitamin D analog'),
event('MEF2',bind,'GC'),
event('MEF2',bind,'CAAT'),
event('vitamin D analog',bind,'GATA'),
event('GC',bind,'GATA'),
event('TATA',bind,'GATA'),
event('TATA',bind,'vitamin D analog'),
event('TATA',bind,'GC'),
event('TATA',bind,'NF1'),
event('GATA1',induce,'GATA'),
event('GATA',induce,'GATA1'),
event('GATA',bind,'S8'),
event('GATA',bind,'XFD2'),
event('PPARA',induce,'progesterone analog'),
event('PPARA',bind,'CEBP'),
event('PPARA',bind,'CEBPA'),
event('fibrate',decrease,'PPARA'),
event('PPARA',decrease,'PPARG'),
event('PPARG',decrease,'PPARA'),
event('RSRFC4',increase,'MEF2'),
event('NR3C1',express,'PPARA'),
event('NR3C1',express,'PPARG'),
event('PPARA',repress,'PPARG'),
event('PPARG',repress,'PPARA'),
event('ABCB1',increase,'vitamin D analog'),
event('ABCB1',increase,'GC'),
event('progesterone analog',induce,'nqo1'),
event('progesterone analog',induce,'CHOP'),
event('SRY',increase,'OCT'),
event('OCT',activate,'SRY'),
event('SRY',decrease,'OCT'),
event('CAAT',bind,'ARNT'),
event('CAAT',bind,'SRY'),
event('TATA',bind,'ARNT'),
event('TATA',bind,'SRY'),
event('SRY',activate,'NR3C1'),
event('SRY',activate,'SP1'),
event('MEF2',activate,'NR3C1'),
event('MEF2',activate,'SP1'),
event('CAAT',bind,'GATA1'),
event('CAAT',bind,'GATA'),
event('TATA',bind,'GATA1'),
event('vitamin D analog',bind,'SRY'),
event('vitamin D analog',bind,'MZF1'),
event('GC',bind,'SRY'),
event('GC',bind,'MZF1'),
event('RARA',target,'TST1'),
event('SRY',target,'ARNT'),
event('SRY',target,'USF'),
event('SRY',target,'AP1'),
event('PPARA',bind,'SRY'),
event('PPARA',bind,'MZF1'),
event('PPARG',bind,'SRY'),
event('PPARG',bind,'MZF1'),
event('vitamin D analog',interact,'GC'),
event('GC',interact,'vitamin D analog'),
event('NR5A2',bind,'HNF4A      '),
event('GATA',bind,'HNF4A      '),
event('GATA',bind,'NR5A2'),
event('NR5A2',activate,'HNF4A      '),
event('NR5A2',activate,'GATA'),
event('HNF1A',bind,'HNF4A      '),
event('HNF1A',bind,'HNF3B'),
event('NF1',bind,'HNF4A      '),
event('NF1',bind,'HNF3B'),
event('HNF1',bind,'HNF4A      '),
event('HNF1',bind,'HNF3B'),
event('HNF1A',increase,'HNF3B'),
event('NF1',increase,'HNF3B'),
event('HNF1',increase,'HNF3B'),
event('HNF3B',bind,'GATA'),
event('HNF4A      ',express,'Phenobarbital'),
event('HNF4A      ',express,'cyp2b6'),
event('HNF4A      ',express,'HNF3B'),
event('NR0B2',decrease,'CYP7A1'),
event('NR0B2',decrease,'cholesterol'),
event('NR0B2',decrease,'cyp7a1'),
event('CAAT',bind,'CYP7A1'),
event('CAAT',bind,'androstane'),
event('CAAT',bind,'CYP3A7'),
event('CAAT',bind,'NR1I3'),
event('CAAT',bind,'HNF4A      '),
event('CAAT',bind,'cyp3a4'),
event('CAAT',bind,'cyp7a1'),
event('androstane',induce,'Phenobarbital'),
event('androstane',induce,'cyp2b6'),
event('androstane',induce,'cyp2c9'),
event('androstane',induce,'cyp2c19'),
event('androstane',induce,'cyp3a4'),
event('NR1I3',induce,'Phenobarbital'),
event('NR1I3',induce,'cyp2b6'),
event('NR1I3',induce,'cyp2c9'),
event('NR1I3',induce,'cyp2c19'),
event('NR1I3',induce,'cyp3a4'),
event('CYP2A6',inhibit,'cyp2c19'),
event('STAT',enhance,'HNF4A      '),
event('HNF4A      ',enhance,'CYP2A6'),
event('STAT',enhance,'CYP2A6'),
event('HNF3B',bind,'CYP2A6'),
event('HNF3B',bind,'ABCB1'),
event('NR1I2',associate,'cyp3a4'),
event('ABCB1',associate,'cyp3a4'),
event('androstane',bind,'vitamin D analog'),
event('androstane',bind,'GC'),
event('NR1I3',bind,'vitamin D analog'),
event('NR1I3',bind,'GC'),
event('NR1I2',bind,'vitamin D analog'),
event('NR1I2',bind,'GC'),
event('NR1I2',bind,'cyp3a4'),
event('abca1',bind,'TATA'),
event('HNF3B',bind,'abca1'),
event('HNF3B',inhibit,'oxysterol'),
event('HNF3B',inhibit,'abca1'),
event('PPARA',stimulate,'progesterone analog'),
event('PPARA',increase,'progesterone analog'),
event('progesterone analog',phosphorylate,'PPARA'),
event('progesterone analog',phosphorylate,'CREB'),
event('NR1I2',associate,'HNF3B'),
event('HNF1A',decrease,'vitamin D analog'),
event('HNF1A',decrease,'GC'),
event('HNF1A',decrease,'NF1'),
event('HNF1A',decrease,'HNF1'),
event('HNF4A      ',decrease,'vitamin D analog'),
event('HNF4A      ',decrease,'HNF1A'),
event('HNF4A      ',decrease,'GC'),
event('HNF4A      ',decrease,'NF1'),
event('HNF4A      ',decrease,'HNF1'),
event('NF1',decrease,'vitamin D analog'),
event('NF1',decrease,'HNF1A'),
event('NF1',decrease,'GC'),
event('NF1',decrease,'HNF1'),
event('HNF1',decrease,'vitamin D analog'),
event('HNF1',decrease,'HNF1A'),
event('HNF1',decrease,'GC'),
event('HNF1',decrease,'NF1'),
event('vitamin D analog',activate,'GC'),
event('GC',activate,'vitamin D analog'),
event('vitamin D analog',target,'TST1'),
event('vitamin D analog',target,'HNF3B'),
event('GC',target,'TST1'),
event('GC',target,'HNF3B'),
event('P300',modulate,'CEBP'),
event('P300',modulate,'HNF3B'),
event('P300',modulate,'CEBPB'),
event('P300',modulate,'CEBPA'),
event('STAT',bind,'HNF4A      '),
event('STAT',bind,'HNF3B'),
event('NR1H4',repress,'FXR'),
event('FXR',repress,'NR1H4'),
event('vitamin D analog',bind,'HNF3B'),
event('GC',bind,'HNF3B'),
event('vitamin D analog',increase,'CP2'),
event('GC',increase,'CP2'),
event('SREBP1',increase,'CP2'),
event('vitamin D analog',decrease,'CP2'),
event('GC',decrease,'CP2'),
event('HNF1A',induce,'HNF4A      '),
event('HNF1A',induce,'NF1'),
event('HNF1A',induce,'HNF1'),
event('NF1',induce,'HNF1A'),
event('NF1',induce,'HNF4A      '),
event('NF1',induce,'HNF1'),
event('HNF1',induce,'HNF1A'),
event('HNF1',induce,'HNF4A      '),
event('HNF1',induce,'NF1'),
event('HNF3B',suppress,'HNF4A      '),
event('USF',bind,'HNF4A      '),
event('USF',bind,'HNF3B'),
event('NR0B2',induce,'androstane'),
event('NR0B2',induce,'NR1I3'),
event('HNF3B',interact,'CREB'),
event('HNF3B',interact,'P300'),
event('PPARA',suppress,'STAT'),
event('AML1',suppress,'STAT'),
event('AML1',associate,'RARA'),
event('NR3C1',recruit,'vitamin D analog'),
event('NR3C1',recruit,'GC'),
event('NR3C1',bind,'vitamin D analog'),
event('NR3C1',bind,'GC'),
event('TST1',bind,'AML1'),
event('GATA1',induce,'AML1'),
event('GATA',induce,'AML1'),
event('AML1',increase,'androstane'),
event('AML1',increase,'NR1I3'),
event('PBX1',express,'progesterone analog'),
event('AML1',express,'progesterone analog'),
event('androstane',express,'AML1'),
event('NR1I3',express,'AML1'),
event('AML1',increase,'CYP1A1'),
event('AML1',participate,'vitamin D analog'),
event('AML1',participate,'GC'),
event('GATA',increase,'AML1'),
event('etoposide',induce,'AML1'),
event('AML1',associate,'progesterone analog'),
event('TST1',associate,'AML1'),
event('EVI1',express,'AML1'),
event('NR3C1',retain,'vitamin D analog'),
event('NR3C1',retain,'GC'),
event('NR3C1',retain,'SP1'),
event('CAAT',retain,'vitamin D analog'),
event('CAAT',retain,'GC'),
event('CAAT',retain,'SP1'),
event('TATA',retain,'vitamin D analog'),
event('TATA',retain,'GC'),
event('TATA',retain,'SP1'),
event('SP1',bind,'NR3C1'),
event('NR3C1',associate,'AML1'),
event('TATA',bind,'MZF1'),
event('vitamin D analog',bind,'AML1'),
event('GC',bind,'AML1'),
event('TATA',bind,'AP1'),
event('TATA',bind,'AML1'),
event('TATA',bind,'BRN2'),
event('progesterone analog',activate,'RARA'),
event('NR3C1',stimulate,'AML1'),
event('AML1',participate,'RARA'),
event('RARA',bind,'VDR'),
event('GATA',increase,'RARA'),
event('CAAT',bind,'AML1'),
event('HNF1A',decrease,'AP1'),
event('HNF1A',decrease,'AML1'),
event('HNF1',decrease,'AP1'),
event('HNF1',decrease,'AML1'),
event('NFE2L2',increase,'GATA1'),
event('NFE2L2',increase,'GATA'),
event('NFE2L2',increase,'VMYB'),
event('NFE2L2',increase,'AML1'),
event('NFE2L2',increase,'MYB'),
event('NRF2',increase,'GATA1'),
event('NRF2',increase,'GATA'),
event('NRF2',increase,'VMYB'),
event('NRF2',increase,'AML1'),
event('NRF2',increase,'MYB'),
event('AML1',express,'NR0B2'),
event('AML1',express,'RARA'),
event('AML1',induce,'RARA'),
event('RARA',induce,'AML1'),
event('PPARA',induce,'AML1'),
event('PPARG',induce,'AML1'),
event('ABCB1',induce,'AML1'),
event('RARA',lead,'P53'),
event('RARA',lead,'AML1'),
event('AML1',lead,'P53'),
event('CREB',inhibit,'AML1'),
event('MEF2',associate,'SRY'),
event('CDP',phosphorylate,'CLOX'),
event('CLOX',phosphorylate,'CDP'),
event('polycyclic aromatic hydrocarbon',target,'AHR'),
event('AHR',target,'polycyclic aromatic hydrocarbon'),
event('CYP1A1',involve,'cyp2c9'),
event('CYP1A1',involve,'cyp2c19'),
event('CYP1A1',involve,'cyp2d6'),
event('CYP1A1',involve,'cyp3a4'),
event('CYP1A2',involve,'cyp2c9'),
event('CYP1A2',involve,'cyp2c19'),
event('CYP1A2',involve,'cyp2d6'),
event('CYP1A2',involve,'cyp3a4'),
event('cyp2c19',involve,'cyp2c9'),
event('cyp2c19',involve,'cyp2d6'),
event('cyp2c19',involve,'cyp3a4'),
event('cyp2d6',involve,'cyp2c9'),
event('cyp2d6',involve,'cyp2c19'),
event('cyp2d6',involve,'cyp3a4'),
event('CYP1A1',decrease,'cyp2c19'),
event('CYP1A2',decrease,'cyp2c19'),
event('cyp3a4',decrease,'cyp2c19'),
event('CYP1A1',induce,'naphthoflavone'),
event('CYP1A1',induce,'Phenobarbital'),
event('CYP1A1',induce,'rifampin'),
event('CYP1A1',induce,'CYP2A6'),
event('CYP1A1',induce,'cyp2b6'),
event('CYP1A1',induce,'cyp2c9'),
event('CYP1A1',induce,'cyp2c19'),
event('CYP1A1',induce,'cyp2d6'),
event('CYP1A1',induce,'cyp3a4'),
event('CYP1A2',induce,'naphthoflavone'),
event('CYP1A2',induce,'Phenobarbital'),
event('CYP1A2',induce,'rifampin'),
event('CYP1A2',induce,'CYP2A6'),
event('CYP1A2',induce,'cyp2b6'),
event('CYP1A2',induce,'cyp2c9'),
event('CYP1A2',induce,'cyp2c19'),
event('CYP1A2',induce,'cyp2d6'),
event('CYP1A2',induce,'cyp3a4'),
event('naphthoflavone',induce,'Phenobarbital'),
event('naphthoflavone',induce,'rifampin'),
event('naphthoflavone',induce,'CYP1A1'),
event('naphthoflavone',induce,'CYP1A2'),
event('naphthoflavone',induce,'CYP2A6'),
event('naphthoflavone',induce,'cyp2b6'),
event('naphthoflavone',induce,'cyp2c19'),
event('CYP1A1',enhance,'polycyclic aromatic hydrocarbon'),
event('CYP1A1',enhance,'AHR'),
event('polycyclic aromatic hydrocarbon',activate,'AHR'),
event('AHR',activate,'polycyclic aromatic hydrocarbon'),
event('CYP1A1',inhibit,'naphthoflavone'),
event('CYP2A6',express,'Phenobarbital'),
event('CYP2A6',express,'cyp2b6'),
event('CYP2A6',express,'cyp2c19'),
event('troleandomycin',decrease,'cyp2c19'),
event('troleandomycin',decrease,'cyp2d6'),
event('cyp3a4',decrease,'cyp2d6'),
event('naphthoflavone',inhibit,'CYP1A1'),
event('naphthoflavone',inhibit,'cyp3a4'),
event('naphthoflavone',increase,'CYP1A1'),
event('CYP1A1',increase,'naphthoflavone'),
event('clotrimazole',increase,'troleandomycin'),
event('cyp2c19',inhibit,'cyp2d6'),
event('clotrimazole',lead,'progesterone analog'),
event('CYP7A1',associate,'ABCC1'),
event('CYP7A1',associate,'ABCC2'),
event('Bile acid',associate,'ABCC1'),
event('Bile acid',associate,'ABCC2'),
event('Lithocholic acid',associate,'ABCC1'),
event('Lithocholic acid',associate,'ABCC2'),
event('chenodeoxycholic acid',associate,'ABCC1'),
event('chenodeoxycholic acid',associate,'ABCC2'),
event('cyp7a1',associate,'ABCC1'),
event('cyp7a1',associate,'ABCC2'),
event('fibrate',increase,'Bile acid'),
event('fibrate',increase,'Lithocholic acid'),
event('fibrate',increase,'chenodeoxycholic acid'),
event('vitamin D analog',induce,'GW4064'),
event('vitamin D analog',induce,'NR1H4'),
event('vitamin D analog',induce,'NR0B2'),
event('vitamin D analog',induce,'FXR'),
event('GC',induce,'GW4064'),
event('GC',induce,'NR1H4'),
event('GC',induce,'NR0B2'),
event('GC',induce,'FXR'),
event('vitamin D analog',inhibit,'NR1H4'),
event('vitamin D analog',inhibit,'FXR'),
event('NR1H4',inhibit,'FXR'),
event('FXR',inhibit,'NR1H4'),
event('GC',inhibit,'NR1H4'),
event('GC',inhibit,'FXR'),
event('vitamin D analog',activate,'NR1H4'),
event('vitamin D analog',activate,'FXR'),
event('GC',activate,'NR1H4'),
event('GC',activate,'FXR'),
event('cholesterol',involve,'HNF4A      '),
event('HNF4A      ',decrease,'Bile acid'),
event('HNF4A      ',decrease,'Lithocholic acid'),
event('HNF4A      ',decrease,'chenodeoxycholic acid'),
event('Bile acid',express,'Lithocholic acid'),
event('Bile acid',express,'chenodeoxycholic acid'),
event('Lithocholic acid',express,'Bile acid'),
event('Lithocholic acid',express,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',express,'Bile acid'),
event('chenodeoxycholic acid',express,'Lithocholic acid'),
event('fibrate',induce,'Bile acid'),
event('fibrate',induce,'Lithocholic acid'),
event('fibrate',induce,'chenodeoxycholic acid'),
event('Bile acid',mediate,'NR1H4'),
event('Bile acid',mediate,'FXR'),
event('Lithocholic acid',mediate,'NR1H4'),
event('Lithocholic acid',mediate,'FXR'),
event('chenodeoxycholic acid',mediate,'NR1H4'),
event('chenodeoxycholic acid',mediate,'FXR'),
event('GW4064',increase,'Bile acid'),
event('GW4064',increase,'Lithocholic acid'),
event('GW4064',increase,'chenodeoxycholic acid'),
event('NR1H4',increase,'Bile acid'),
event('NR1H4',increase,'Lithocholic acid'),
event('NR1H4',increase,'chenodeoxycholic acid'),
event('FXR',increase,'Bile acid'),
event('FXR',increase,'Lithocholic acid'),
event('FXR',increase,'chenodeoxycholic acid'),
event('Bile acid',target,'Lithocholic acid'),
event('Bile acid',target,'chenodeoxycholic acid'),
event('Lithocholic acid',target,'Bile acid'),
event('Lithocholic acid',target,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',target,'Bile acid'),
event('chenodeoxycholic acid',target,'Lithocholic acid'),
event('Bile acid',activate,'Lithocholic acid'),
event('Bile acid',activate,'chenodeoxycholic acid'),
event('Bile acid',activate,'NR3C1'),
event('Lithocholic acid',activate,'Bile acid'),
event('Lithocholic acid',activate,'chenodeoxycholic acid'),
event('Lithocholic acid',activate,'NR3C1'),
event('chenodeoxycholic acid',activate,'Bile acid'),
event('chenodeoxycholic acid',activate,'Lithocholic acid'),
event('chenodeoxycholic acid',activate,'NR3C1'),
event('cyp3a4',target,'VDR'),
event('VDR',express,'CYP7A1'),
event('VDR',express,'cholesterol'),
event('VDR',express,'cyp7a1'),
event('VDR',activate,'CYP7A1'),
event('VDR',activate,'cyp7a1'),
event('VDR',activate,'CYP24'),
event('VDR',activate,'cyp3a4'),
event('GW4064',induce,'VDR'),
event('VDR',regulate,'NR1H4'),
event('VDR',regulate,'FXR'),
event('VDR',bind,'CYP24'),
event('cholesterol',mediate,'VDR'),
event('cholesterol',activate,'NR3C1'),
event('cholesterol',activate,'NR1H4'),
event('cholesterol',activate,'NR1I2'),
event('cholesterol',activate,'VDR'),
event('cholesterol',activate,'FXR'),
event('cholesterol',activate,'TST1'),
event('NR1H4',express,'cholesterol'),
event('FXR',express,'cholesterol'),
event('VDR',induce,'Phenobarbital'),
event('VDR',induce,'cyp2b6'),
event('VDR',induce,'cyp2c9'),
event('VDR',induce,'cyp2c19'),
event('VDR',induce,'cyp3a4'),
event('progesterone analog',regulate,'NR1I2'),
event('VDR',inhibit,'CYP7A1'),
event('VDR',inhibit,'cholesterol'),
event('VDR',inhibit,'cyp7a1'),
event('VDR',interact,'CYP7A1'),
event('VDR',interact,'HNF4A      '),
event('VDR',interact,'cyp7a1'),
event('dehydroepiandrosterone',decrease,'GW4064'),
event('dehydroepiandrosterone',decrease,'NR1H4'),
event('dehydroepiandrosterone',decrease,'NR0B2'),
event('dehydroepiandrosterone',decrease,'FXR'),
event('sult2a1',decrease,'GW4064'),
event('sult2a1',decrease,'NR1H4'),
event('sult2a1',decrease,'NR0B2'),
event('sult2a1',decrease,'FXR'),
event('NR1H4',target,'NR0B2'),
event('FXR',target,'NR0B2'),
event('NR1H4',bind,'cholesterol'),
event('FXR',bind,'cholesterol'),
event('VDR',inhibit,'NR1H4'),
event('VDR',inhibit,'FXR'),
event('fibrate',associate,'cholesterol'),
event('fibrate',mediate,'PPARA'),
event('NR1H4',regulate,'cholesterol'),
event('FXR',regulate,'cholesterol'),
event('GW4064',bind,'NR1H4'),
event('GW4064',bind,'FXR'),
event('NR1H4',bind,'GW4064'),
event('NR1H4',bind,'FXR'),
event('FXR',bind,'GW4064'),
event('FXR',bind,'NR1H4'),
event('NR1H4',decrease,'FXR'),
event('FXR',decrease,'NR1H4'),
event('NR1H4',induce,'FXR'),
event('FXR',induce,'NR1H4'),
event('NR1H4',target,'GW4064'),
event('NR1H4',target,'FXR'),
event('FXR',target,'GW4064'),
event('FXR',target,'NR1H4'),
event('NR1H4',activate,'NR0B2'),
event('NR1H4',activate,'FXR'),
event('FXR',activate,'NR1H4'),
event('FXR',activate,'NR0B2'),
event('ABCC1',regulate,'NR1H4'),
event('ABCC1',regulate,'FXR'),
event('ABCC1',regulate,'TST1'),
event('ABCC2',regulate,'NR1H4'),
event('ABCC2',regulate,'FXR'),
event('ABCC2',regulate,'TST1'),
event('ABCC1',induce,'GW4064'),
event('ABCC1',induce,'NR1H4'),
event('ABCC1',induce,'FXR'),
event('ABCC2',induce,'GW4064'),
event('ABCC2',induce,'NR1H4'),
event('ABCC2',induce,'FXR'),
event('androstane',bind,'NR2B1'),
event('NR1I3',bind,'NR2B1'),
event('NR1H4',bind,'NR2B1'),
event('NR1I2',bind,'NR2B1'),
event('FXR',bind,'NR2B1'),
event('GW4064',inhibit,'NR0B2'),
event('GW4064',inhibit,'STAT'),
event('GW4064',enhance,'vitamin D analog'),
event('GW4064',enhance,'ABCB11'),
event('GW4064',enhance,'ABCB1'),
event('GW4064',enhance,'GC'),
event('vitamin D analog',enhance,'GW4064'),
event('vitamin D analog',enhance,'ABCB11'),
event('vitamin D analog',enhance,'ABCB1'),
event('vitamin D analog',enhance,'GC'),
event('GC',enhance,'GW4064'),
event('GC',enhance,'vitamin D analog'),
event('GC',enhance,'ABCB11'),
event('GC',enhance,'ABCB1'),
event('NR1H4',increase,'GW4064'),
event('FXR',increase,'GW4064'),
event('NR1H4',induce,'GATA1'),
event('NR1H4',induce,'GATA'),
event('FXR',induce,'GATA1'),
event('FXR',induce,'GATA'),
event('GW4064',increase,'NR1H4'),
event('GW4064',increase,'FXR'),
event('GW4064',increase,'GATA1'),
event('GW4064',increase,'GATA'),
event('NR1H4',increase,'FXR'),
event('NR1H4',increase,'GATA1'),
event('NR1H4',increase,'GATA'),
event('FXR',increase,'NR1H4'),
event('FXR',increase,'GATA1'),
event('FXR',increase,'GATA'),
event('GATA1',increase,'GW4064'),
event('GATA',increase,'GW4064'),
event('GW4064',enhance,'GATA1'),
event('GW4064',enhance,'GATA'),
event('GATA1',enhance,'GATA'),
event('GATA',enhance,'GATA1'),
event('NR1H4',inhibit,'STAT'),
event('FXR',inhibit,'STAT'),
event('GW4064',target,'NR0B2'),
event('GW4064',target,'ABCB11'),
event('NR1H4',target,'ABCB11'),
event('FXR',target,'ABCB11'),
event('GW4064',decrease,'cyp2d6'),
event('NR1H4',mediate,'NR0B2'),
event('NR1H4',mediate,'FXR'),
event('FXR',mediate,'NR1H4'),
event('FXR',mediate,'NR0B2'),
event('GW4064',decrease,'NR0B2'),
event('GW4064',decrease,'cyp3a4'),
event('NR0B2',repress,'androstane'),
event('NR0B2',repress,'NR1I3'),
event('NR0B2',repress,'NR1I2'),
event('NR0B2',repress,'cyp3a4'),
event('GW4064',repress,'Phenobarbital'),
event('GW4064',repress,'androstane'),
event('GW4064',repress,'NR1I3'),
event('GW4064',repress,'NR1I2'),
event('GW4064',repress,'cyp2b6'),
event('GW4064',repress,'NR0B2'),
event('GW4064',repress,'cyp3a4'),
event('NR5A2',increase,'NR1H4'),
event('NR5A2',increase,'NR0B2'),
event('NR5A2',increase,'FXR'),
event('NR1H4',mediate,'NR5A2'),
event('NR0B2',mediate,'NR5A2'),
event('FXR',mediate,'NR5A2'),
event('NR1H4',increase,'STAT'),
event('FXR',increase,'STAT'),
event('NR1H4',express,'GW4064'),
event('NR1H4',express,'NR0B2'),
event('NR1H4',express,'PPARA'),
event('NR1H4',express,'FXR'),
event('FXR',express,'GW4064'),
event('FXR',express,'NR1H4'),
event('FXR',express,'NR0B2'),
event('FXR',express,'PPARA'),
event('GW4064',decrease,'NR1H4'),
event('GW4064',decrease,'FXR'),
event('NR1H4',induce,'NR0B2'),
event('FXR',induce,'NR0B2'),
event('ABCB11',associate,'NR1H4'),
event('ABCB11',associate,'FXR'),
event('ABCB1',associate,'NR1H4'),
event('ABCB1',associate,'FXR'),
event('GW4064',induce,'CYP7A1'),
event('GW4064',induce,'cyp7a1'),
event('GW4064',induce,'GATA1'),
event('GW4064',induce,'GATA'),
event('NR1H4',induce,'CYP7A1'),
event('NR1H4',induce,'cyp7a1'),
event('FXR',induce,'CYP7A1'),
event('FXR',induce,'cyp7a1'),
event('GATA1',repress,'CYP7A1'),
event('GATA1',repress,'NR0B2'),
event('GATA1',repress,'cyp7a1'),
event('GATA',repress,'CYP7A1'),
event('GATA',repress,'NR0B2'),
event('GATA',repress,'cyp7a1'),
event('GATA1',inhibit,'CYP7A1'),
event('GATA1',inhibit,'NR0B2'),
event('GATA1',inhibit,'cyp7a1'),
event('GATA',inhibit,'CYP7A1'),
event('GATA',inhibit,'NR0B2'),
event('GATA',inhibit,'cyp7a1'),
event('vitamin D analog',induce,'GC'),
event('GC',induce,'vitamin D analog'),
event('vitamin D analog',induce,'CYP7A1'),
event('vitamin D analog',induce,'cyp7a1'),
event('GC',induce,'CYP7A1'),
event('GC',induce,'cyp7a1'),
event('vitamin D analog',repress,'NR0B2'),
event('NR5A2',repress,'NR0B2'),
event('GC',repress,'NR0B2'),
event('GW4064',induce,'vitamin D analog'),
event('GW4064',induce,'NR0B2'),
event('GW4064',induce,'GC'),
event('GW4064',increase,'CYP7A1'),
event('GW4064',increase,'cyp7a1'),
event('NR0B2',associate,'CYP7A1'),
event('NR0B2',associate,'cyp7a1'),
event('CYP7A1',target,'cholesterol'),
event('cyp7a1',target,'cholesterol'),
event('NR3C1',interact,'vitamin D analog'),
event('NR3C1',interact,'GC'),
event('Glucocorticoid',modulate,'vitamin D analog'),
event('Glucocorticoid',modulate,'GC'),
event('NR3C1',modulate,'vitamin D analog'),
event('NR3C1',modulate,'GC'),
event('vitamin D analog',express,'GC'),
event('GC',express,'vitamin D analog'),
event('Glucocorticoid',associate,'vitamin D analog'),
event('Glucocorticoid',associate,'GC'),
event('NR3C1',associate,'Glucocorticoid'),
event('NR3C1',associate,'vitamin D analog'),
event('NR3C1',associate,'GC'),
event('vitamin D analog',bind,'NR3C1'),
event('GC',bind,'NR3C1'),
event('NR3C1',increase,'cholesterol'),
event('PPARA',decrease,'NR3C1'),
event('PPARG',decrease,'NR3C1'),
event('vitamin D analog',enhance,'NR3C1'),
event('GC',enhance,'NR3C1'),
event('Glucocorticoid',involve,'vitamin D analog'),
event('Glucocorticoid',involve,'NR3C1'),
event('Glucocorticoid',involve,'GC'),
event('vitamin D analog',involve,'NR3C1'),
event('vitamin D analog',involve,'GC'),
event('GC',involve,'vitamin D analog'),
event('GC',involve,'NR3C1'),
event('NR3C1',increase,'paclitaxel'),
event('Glucocorticoid',mediate,'vitamin D analog'),
event('Glucocorticoid',mediate,'NR3C1'),
event('Glucocorticoid',mediate,'GC'),
event('vitamin D analog',mediate,'NR3C1'),
event('vitamin D analog',mediate,'GC'),
event('GC',mediate,'vitamin D analog'),
event('GC',mediate,'NR3C1'),
event('oxysterol',target,'cholesterol'),
event('oxysterol',regulate,'cholesterol'),
event('oxysterol',promote,'cholesterol'),
event('cholesterol',inhibit,'oxysterol'),
event('cholesterol',interact,'oxysterol'),
event('vitamin D analog',regulate,'GC'),
event('GC',regulate,'vitamin D analog'),
event('PPARA',induce,'cholesterol'),
event('T0901317',lead,'cholesterol'),
event('PPARA',lead,'cholesterol'),
event('cholesterol',increase,'Phenobarbital'),
event('cholesterol',increase,'CYP4A'),
event('cholesterol',increase,'CYP1A1'),
event('cholesterol',increase,'cyp2b6'),
event('ABCG1',bind,'cholesterol'),
event('ABCG1',regulate,'PPARA'),
event('PPARA',stimulate,'ABCG1'),
event('PPARA',increase,'ABCG1'),
event('PPARA',inhibit,'SREBP1'),
event('PPARA',bind,'SREBP1'),
event('WY-14',increase,'PPARA'),
event('WY-14',increase,'OCT'),
event('WY-14',stimulate,'OCT'),
event('OCT',regulate,'PPARA'),
event('STAT',induce,'PPARA'),
event('PPARA',induce,'STAT'),
event('NR3C1',induce,'CREB'),
event('etoposide',express,'ABCC1'),
event('STAT',target,'vitamin D analog'),
event('STAT',target,'GC'),
event('TATA',bind,'progesterone analog'),
event('GATA1',target,'GATA'),
event('GATA',target,'GATA1'),
event('vitamin D analog',prevent,'GC'),
event('GC',prevent,'vitamin D analog'),
event('CREB',bind,'E2F'),
event('PPARG',induce,'progesterone analog'),
event('abca1',promote,'AP1'),
event('PPARA',express,'PPARG'),
event('TST1',bind,'vitamin D analog'),
event('TST1',bind,'GC'),
event('progesterone analog',regulate,'cholesterol'),
event('progesterone analog',express,'NR3C1'),
event('NR3C1',express,'progesterone analog'),
event('P300',increase,'Bile acid'),
event('P300',increase,'Lithocholic acid'),
event('P300',increase,'chenodeoxycholic acid'),
event('HSF1',induce,'Bile acid'),
event('HSF1',induce,'Lithocholic acid'),
event('HSF1',induce,'chenodeoxycholic acid'),
event('CREB',increase,'Bile acid'),
event('CREB',increase,'Lithocholic acid'),
event('CREB',increase,'chenodeoxycholic acid'),
event('Bile acid',increase,'Lithocholic acid'),
event('Bile acid',increase,'chenodeoxycholic acid'),
event('Lithocholic acid',increase,'Bile acid'),
event('Lithocholic acid',increase,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',increase,'Bile acid'),
event('chenodeoxycholic acid',increase,'Lithocholic acid'),
event('NR1H4',associate,'Bile acid'),
event('NR1H4',associate,'Lithocholic acid'),
event('NR1H4',associate,'chenodeoxycholic acid'),
event('FXR',associate,'Bile acid'),
event('FXR',associate,'Lithocholic acid'),
event('FXR',associate,'chenodeoxycholic acid'),
event('fatty acid',express,'Bile acid'),
event('fatty acid',express,'Lithocholic acid'),
event('fatty acid',express,'chenodeoxycholic acid'),
event('Bile acid',involve,'Lithocholic acid'),
event('Bile acid',involve,'chenodeoxycholic acid'),
event('Lithocholic acid',involve,'Bile acid'),
event('Lithocholic acid',involve,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',involve,'Bile acid'),
event('chenodeoxycholic acid',involve,'Lithocholic acid'),
event('CREB',regulate,'rifampin'),
event('NR1I2',involve,'CYP7A1'),
event('NR1I2',involve,'cholesterol'),
event('NR1I2',involve,'cyp7a1'),
event('vitamin D analog',enhance,'NR1I2'),
event('GC',enhance,'NR1I2'),
event('vitamin D analog',bind,'NR1I2'),
event('vitamin D analog',bind,'GC'),
event('GC',bind,'vitamin D analog'),
event('GC',bind,'NR1I2'),
event('hyperforin',activate,'NR1I2'),
event('NR1I2',target,'hyperforin'),
event('NR1I2',bind,'CYP24'),
event('NR1I2',activate,'Phenobarbital'),
event('NR1I2',activate,'androstane'),
event('NR1I2',activate,'NR1I3'),
event('NR1I2',activate,'cyp2b6'),
event('Phenobarbital',regulate,'NR1I2'),
event('cyp2b6',regulate,'NR1I2'),
event('hyperforin',suppress,'OCT1'),
event('hyperforin',suppress,'OCT'),
event('NR1I2',suppress,'OCT1'),
event('NR1I2',suppress,'OCT'),
event('HNF4A      ',decrease,'OCT1'),
event('HNF4A      ',decrease,'OCT'),
event('NR1I2',decrease,'OCT1'),
event('NR1I2',decrease,'OCT'),
event('OCT1',decrease,'OCT'),
event('OCT',decrease,'OCT1'),
event('USF',decrease,'OCT1'),
event('USF',decrease,'OCT'),
event('cyp3a4',mediate,'androstane'),
event('cyp3a4',mediate,'NR1I3'),
event('cyp3a4',mediate,'NR1I2'),
event('cyp3a4',mediate,'hyperforin'),
event('hyperforin',activate,'ABCB1'),
event('NR1I2',mediate,'hyperforin'),
event('NR1I2',mediate,'cyp2c9'),
event('NR1I2',mediate,'cyp2c19'),
event('NR1I2',bind,'cyp2c9'),
event('NR1I2',bind,'cyp2c19'),
event('cyp2c9',bind,'androstane'),
event('cyp2c9',bind,'NR1I3'),
event('cyp2c19',bind,'androstane'),
event('cyp2c19',bind,'NR1I3'),
event('hyperforin',bind,'NR1I2'),
event('NR1I2',involve,'ABCB1'),
event('hyperforin',induce,'cyp2d6'),
event('hyperforin',promote,'cyp3a4'),
event('NR1I2',promote,'cyp3a4'),
event('NR1I2',enhance,'hyperforin'),
event('paclitaxel',decrease,'STAT'),
event('paclitaxel',inhibit,'STAT'),
event('paclitaxel',suppress,'STAT'),
event('progesterone analog',induce,'paclitaxel'),
event('progesterone analog',induce,'androstane'),
event('progesterone analog',induce,'NR1I3'),
event('androstane',increase,'paclitaxel'),
event('NR1I3',increase,'paclitaxel'),
event('Phenobarbital',decrease,'cyp2b6'),
event('cyp2b6',decrease,'Phenobarbital'),
event('cyp2c9',decrease,'Phenobarbital'),
event('cyp2c9',decrease,'cyp2b6'),
event('cyp2c19',decrease,'Phenobarbital'),
event('cyp2c19',decrease,'cyp2b6'),
event('cyp2d6',decrease,'Phenobarbital'),
event('cyp2d6',decrease,'cyp2b6'),
event('CYP1A1',inhibit,'cyp2c19'),
event('CYP1A1',inhibit,'cyp2d6'),
event('CYP1A1',inhibit,'ABCB1'),
event('CYP1A2',inhibit,'cyp2c19'),
event('CYP1A2',inhibit,'cyp2d6'),
event('CYP1A2',inhibit,'ABCB1'),
event('cyp2c9',inhibit,'cyp2c19'),
event('cyp2c9',inhibit,'cyp2d6'),
event('cyp2c9',inhibit,'ABCB1'),
event('cyp2c19',inhibit,'ABCB1'),
event('nelfinavir',suppress,'cyp3a4'),
event('rifampin',induce,'cyp3a4'),
event('cyp2c19',induce,'cyp2d6'),
event('SRY',suppress,'cholesterol'),
event('Phenobarbital',enhance,'cyp2b6'),
event('efavirenz',enhance,'Phenobarbital'),
event('efavirenz',enhance,'cyp2b6'),
event('cyp2b6',enhance,'Phenobarbital'),
event('simvastatin',modulate,'cholesterol'),
event('simvastatin',increase,'vitamin D analog'),
event('simvastatin',increase,'GC'),
event('SLCO1A2',inhibit,'vitamin D analog'),
event('SLCO1A2',inhibit,'GC'),
event('SLCO1B1',inhibit,'vitamin D analog'),
event('SLCO1B1',inhibit,'GC'),
event('SLCO1B3',inhibit,'vitamin D analog'),
event('SLCO1B3',inhibit,'GC'),
event('cyp2d6',associate,'simvastatin'),
event('cyp3a5',associate,'simvastatin'),
event('SLCO1B1',associate,'simvastatin'),
event('SLCO1A2',associate,'simvastatin'),
event('SLCO1B1',increase,'simvastatin'),
event('troglitazone',decrease,'fibrate'),
event('PPARA',modulate,'OCT'),
event('troglitazone',mediate,'PPARA'),
event('cyproterone acetate',involve,'ABCB1'),
event('troleandomycin',inhibit,'cyp3a4'),
event('naphthoflavone',induce,'ABCC1'),
event('naphthoflavone',induce,'ABCC2'),
event('troleandomycin',induce,'ABCC1'),
event('troleandomycin',induce,'ABCC2'),
event('vitamin D analog',increase,'NR3C1'),
event('GC',increase,'NR3C1'),
event('RU486',bind,'progesterone analog'),
event('progesterone analog',mediate,'NR3C1'),
event('NR3C1',mediate,'progesterone analog'),
event('progesterone analog',associate,'NR3C1'),
event('NR3C1',associate,'progesterone analog'),
event('progesterone analog',promote,'NR3C1'),
event('NR3C1',promote,'progesterone analog'),
event('IRF1',increase,'paclitaxel'),
event('IRF1',increase,'KH1060'),
event('VDR',bind,'KH1060'),
event('KH1060',bind,'VDR'),
event('KH1060',stimulate,'VDR'),
event('KH1060',increase,'VDR'),
event('cholesterol',bind,'vitamin D analog'),
event('cholesterol',bind,'GC'),
event('VDR',prevent,'EB1089'),
event('OCT',increase,'CAP'),
event('OCT',induce,'CAP'),
event('NR1H2',bind,'NR3C1'),
event('vitamin D analog',suppress,'GC'),
event('GC',suppress,'vitamin D analog'),
event('vitamin D analog',decrease,'GC'),
event('GC',decrease,'vitamin D analog'),
event('paclitaxel',target,'vitamin D analog'),
event('paclitaxel',target,'GC'),
event('vitamin D analog',target,'GC'),
event('GC',target,'vitamin D analog'),
event('vitamin D analog',associate,'GC'),
event('GC',associate,'vitamin D analog'),
event('NR3C1',induce,'vitamin D analog'),
event('NR3C1',induce,'GC'),
event('vitamin D analog',express,'NR3C1'),
event('GC',express,'NR3C1'),
event('SLC10A2',activate,'VDR'),
event('vitamin D analog',associate,'cholesterol'),
event('GC',associate,'cholesterol'),
event('vitamin D analog',lead,'GC'),
event('GC',lead,'vitamin D analog'),
event('vitamin D analog',increase,'CYP1A1'),
event('GC',increase,'CYP1A1'),
event('STAT',prevent,'RARA'),
event('retinoic acid',induce,'STAT'),
event('vitamin D analog',involve,'STAT'),
event('GC',involve,'STAT'),
event('RARA',regulate,'VDR'),
event('VDR',repress,'RARA'),
event('RARA',lead,'VDR'),
event('RARA',interact,'NR3C1'),
event('abca1',stimulate,'NR2B1'),
event('abca1',stimulate,'RARA'),
event('abca1',stimulate,'RARB'),
event('abca1',stimulate,'RARG'),
event('OCT',require,'RARA'),
event('androstane',target,'NR1I3'),
event('NR1I3',target,'androstane'),
event('fibrate',target,'Phenobarbital'),
event('fibrate',target,'CYP2B1'),
event('fibrate',target,'cyp2b6'),
event('androstane',target,'Phenobarbital'),
event('androstane',target,'CYP2B1'),
event('androstane',target,'cyp2b6'),
event('NR1I3',target,'Phenobarbital'),
event('NR1I3',target,'CYP2B1'),
event('NR1I3',target,'cyp2b6'),
event('PPARA',target,'Phenobarbital'),
event('PPARA',target,'CYP2B1'),
event('PPARA',target,'cyp2b6'),
event('Phenobarbital',increase,'PPARA'),
event('androstane',increase,'PPARA'),
event('NR1I3',increase,'PPARA'),
event('CYP2B1',increase,'PPARA'),
event('cyp2b6',increase,'PPARA'),
event('Phenobarbital',induce,'androstane'),
event('Phenobarbital',induce,'NR1I3'),
event('Phenobarbital',induce,'PPARA'),
event('CYP2B1',induce,'androstane'),
event('CYP2B1',induce,'NR1I3'),
event('CYP2B1',induce,'PPARA'),
event('cyp2b6',induce,'androstane'),
event('cyp2b6',induce,'NR1I3'),
event('cyp2b6',induce,'PPARA'),
event('PPARA',increase,'Phenobarbital'),
event('PPARA',increase,'androstane'),
event('PPARA',increase,'NR1I3'),
event('PPARA',increase,'cyp2b6'),
event('guggulsterone',repress,'androstane'),
event('guggulsterone',repress,'NR1I3'),
event('guggulsterone',repress,'NR1I2'),
event('guggulsterone',repress,'Cyp2b10'),
event('PPARA',target,'fibrate'),
event('androstane',modulate,'PPARA'),
event('androstane',modulate,'cyp2c19'),
event('androstane',modulate,'cyp3a4'),
event('NR1I3',modulate,'PPARA'),
event('NR1I3',modulate,'cyp2c19'),
event('NR1I3',modulate,'cyp3a4'),
event('NR1I2',modulate,'PPARA'),
event('NR1I2',modulate,'cyp2c19'),
event('NR1I2',modulate,'cyp3a4'),
event('CITCO',decrease,'CHOP'),
event('androstane',inhibit,'NR1I3'),
event('NR1I3',inhibit,'androstane'),
event('androstane',lead,'NR1I3'),
event('NR1I3',lead,'androstane'),
event('androstane',regulate,'clotrimazole'),
event('NR1I3',regulate,'clotrimazole'),
event('androstane',regulate,'ABCC1'),
event('androstane',regulate,'ABCC2'),
event('NR1I3',regulate,'ABCC1'),
event('NR1I3',regulate,'ABCC2'),
event('androstane',express,'NR1I3'),
event('NR1I3',express,'androstane'),
event('androstane',heterodimerize,'NR1I3'),
event('NR1I3',heterodimerize,'androstane'),
event('androstane',mediate,'NR1I3'),
event('NR1I3',mediate,'androstane'),
event('androstane',enhance,'NR1I3'),
event('NR1I3',enhance,'androstane'),
event('Phenobarbital',enhance,'androstane'),
event('Phenobarbital',enhance,'NR1I3'),
event('cyp2b6',enhance,'androstane'),
event('cyp2b6',enhance,'NR1I3'),
event('NR1I2',repress,'Phenobarbital'),
event('NR1I2',repress,'cyp2b6'),
event('androstane',target,'cyp3a4'),
event('NR1I3',target,'cyp3a4'),
event('NR1I2',target,'Phenobarbital'),
event('NR1I2',target,'cyp2b6'),
event('NR1I2',target,'cyp3a4'),
event('cyp3a4',increase,'rifampin'),
event('androstane',bind,'NR1I3'),
event('NR1I3',bind,'androstane'),
event('androstane',bind,'HNF4A      '),
event('androstane',bind,'VMYB'),
event('androstane',bind,'MYB'),
event('NR1I3',bind,'HNF4A      '),
event('NR1I3',bind,'VMYB'),
event('NR1I3',bind,'MYB'),
event('androstane',modulate,'NR1I3'),
event('NR1I3',modulate,'androstane'),
event('cyp2c19',regulate,'androstane'),
event('cyp2c19',regulate,'NR1I3'),
event('cyp2c19',suppress,'androstane'),
event('cyp2c19',suppress,'NR1I3'),
event('androstane',involve,'cyp2c19'),
event('NR1I3',involve,'cyp2c19'),
event('androstane',associate,'omeprazole'),
event('NR1I3',associate,'omeprazole'),
event('TCPOBOP',decrease,'PPARA'),
event('cholesterol',interact,'AP1'),
event('spiro',increase,'cholesterol'),
event('abca1',increase,'cholesterol'),
event('CREB',increase,'cholesterol'),
event('cholesterol',decrease,'CREB'),
event('abca1',associate,'cholesterol'),
event('Glucocorticoid',trigger,'NR3C1'),
event('vitamin D analog',trigger,'Glucocorticoid'),
event('vitamin D analog',trigger,'NR3C1'),
event('GC',trigger,'Glucocorticoid'),
event('GC',trigger,'NR3C1'),
event('vitamin D analog',involve,'cyp3a4'),
event('vitamin D analog',involve,'cyp3a5'),
event('NR3C1',involve,'vitamin D analog'),
event('NR3C1',involve,'cyp3a4'),
event('NR3C1',involve,'cyp3a5'),
event('NR3C1',involve,'GC'),
event('ABCB1',involve,'vitamin D analog'),
event('ABCB1',involve,'cyp3a4'),
event('ABCB1',involve,'cyp3a5'),
event('ABCB1',involve,'GC'),
event('GC',involve,'cyp3a4'),
event('GC',involve,'cyp3a5'),
event('NR3C1',decrease,'cholesterol'),
event('NR0B2',associate,'PLCG1'),
event('PLCG1',prevent,'NR0B2'),
event('PLCG1',regulate,'SP1'),
event('RARA',bind,'RARG'),
event('RARG',bind,'RARA'),
event('RARA',require,'NR2B1'),
event('Bile acid',increase,'RARA'),
event('Lithocholic acid',increase,'RARA'),
event('chenodeoxycholic acid',increase,'RARA'),
event('RARA',interact,'HNF4A      '),
event('progesterone analog',bind,'RARA'),
event('RARA',enhance,'NR2B1'),
event('cholesterol',involve,'NR2B1'),
event('CYP24',bind,'vitamin D analog'),
event('CYP24',bind,'NR2B1'),
event('CYP24',bind,'GC'),
event('androstane',increase,'NR2B1'),
event('NR1I3',increase,'NR2B1'),
event('NR1I2',increase,'NR2B1'),
event('PPARA',bind,'NR2B1'),
event('PPARG',bind,'NR2B1'),
event('PPARG',bind,'CEBP'),
event('PPARG',bind,'CEBPA'),
event('CAAT',bind,'NR2B1'),
event('vitamin D analog',interact,'NR1H4'),
event('vitamin D analog',interact,'FXR'),
event('GC',interact,'NR1H4'),
event('GC',interact,'FXR'),
event('PPARA',target,'fatty acid'),
event('PPARA',target,'SREBP1'),
event('PPARG',target,'fatty acid'),
event('PPARG',target,'SREBP1'),
event('NR3C1',bind,'VDR'),
event('CYP7A1',regulate,'NR0B2'),
event('cholesterol',regulate,'NR0B2'),
event('cyp7a1',regulate,'NR0B2'),
event('NR1I2',bind,'cyp3a5'),
event('CYP7A1',repress,'NR1H4'),
event('CYP7A1',repress,'NR0B2'),
event('CYP7A1',repress,'FXR'),
event('CYP7A1',repress,'GATA1'),
event('CYP7A1',repress,'GATA'),
event('cyp7a1',repress,'NR1H4'),
event('cyp7a1',repress,'NR0B2'),
event('cyp7a1',repress,'FXR'),
event('cyp7a1',repress,'GATA1'),
event('cyp7a1',repress,'GATA'),
event('NR1H4',increase,'CYP7A1'),
event('NR1H4',increase,'cyp7a1'),
event('FXR',increase,'CYP7A1'),
event('FXR',increase,'cyp7a1'),
event('GSTM',increase,'CYP1A1'),
event('CYP1A1',increase,'GSTM'),
event('ABCB11',express,'ABCB1'),
event('ABCB11',express,'ABCC1'),
event('ABCB11',express,'ABCC2'),
event('ABCB1',express,'ABCC1'),
event('ABCB1',express,'ABCC2'),
event('NFE2L2',target,'P53'),
event('NRF2',target,'P53'),
event('GSTM',associate,'GSTP1'),
event('GSTP1',associate,'GSTM'),
event('gsta1',associate,'GSTM'),
event('gsta1',associate,'GSTP1'),
event('GSTP1',activate,'PPARA'),
event('gsta1',activate,'PPARA'),
event('NFE2L2',target,'NRF2'),
event('NRF2',target,'NFE2L2'),
event('fibrate',enhance,'CYP4A'),
event('fibrate',increase,'PPARA'),
event('vitamin D analog',increase,'PPARA'),
event('CYP4A',increase,'PPARA'),
event('GC',increase,'PPARA'),
event('NR0B2',bind,'VDR'),
event('VDR',bind,'NR0B2'),
event('VDR',repress,'CYP7A1'),
event('VDR',repress,'cholesterol'),
event('VDR',repress,'NR0B2'),
event('VDR',repress,'cyp7a1'),
event('rifampin',increase,'cyp3a4'),
event('rifampin',mediate,'cyp2d6'),
event('rifampin',mediate,'cyp3a4'),
event('NR1I2',decrease,'CYP3A7'),
event('NR1I2',decrease,'cyp3a4'),
event('NR1I2',decrease,'cyp3a5'),
event('CYP4A',decrease,'PPARA'),
event('CYP1A1',involve,'CYP1A2'),
event('CYP1A2',involve,'CYP1A1'),
event('NR1I2',involve,'cyp3a4'),
event('CYP3A7',inhibit,'troleandomycin'),
event('CYP3A7',inhibit,'CYP1A1'),
event('CYP3A7',inhibit,'CYP1A2'),
event('CYP3A7',inhibit,'cyp3a4'),
event('CYP1A1',inhibit,'troleandomycin'),
event('CYP1A1',inhibit,'CYP1A2'),
event('CYP1A1',inhibit,'cyp3a4'),
event('CYP1A2',inhibit,'troleandomycin'),
event('CYP1A2',inhibit,'CYP1A1'),
event('CYP1A2',inhibit,'cyp3a4'),
event('cyp3a4',inhibit,'troleandomycin'),
event('cyp3a4',inhibit,'CYP1A1'),
event('cyp3a4',inhibit,'CYP1A2'),
event('cyp3a5',inhibit,'troleandomycin'),
event('cyp3a5',inhibit,'CYP1A1'),
event('cyp3a5',inhibit,'CYP1A2'),
event('cyp3a5',inhibit,'cyp3a4'),
event('SP1',activate,'progesterone analog'),
event('SP1',activate,'MEF2'),
event('CLOX',activate,'progesterone analog'),
event('CLOX',activate,'MEF2'),
event('cholesterol',mediate,'ABCG5'),
event('CYP3A7',regulate,'HNF4A      '),
event('ugt1a1',regulate,'HNF4A      '),
event('CYP3A7',express,'cyp3a4'),
event('CYP7A1',inhibit,'NR0B2'),
event('cyp7a1',inhibit,'NR0B2'),
event('vitamin D analog',decrease,'CYP7A1'),
event('vitamin D analog',decrease,'cholesterol'),
event('vitamin D analog',decrease,'cyp7a1'),
event('GC',decrease,'CYP7A1'),
event('GC',decrease,'cholesterol'),
event('GC',decrease,'cyp7a1'),
event('vitamin D analog',increase,'NR0B2'),
event('GC',increase,'NR0B2'),
event('CYP24',increase,'VDR'),
event('VDR',increase,'CYP24'),
event('NR5A2',target,'CYP24'),
event('VDR',suppress,'CYP24'),
event('polycyclic aromatic hydrocarbon',trigger,'AHR'),
event('polycyclic aromatic hydrocarbon',trigger,'ARNT'),
event('AHR',trigger,'polycyclic aromatic hydrocarbon'),
event('AHR',trigger,'ARNT'),
event('ARNT',express,'CYP1A1'),
event('ARNT',express,'CYP1B1'),
event('CYP1A1',express,'CYP1B1'),
event('CYP1A2',express,'CYP1A1'),
event('CYP1A2',express,'CYP1B1'),
event('polycyclic aromatic hydrocarbon',induce,'AHR'),
event('AHR',induce,'polycyclic aromatic hydrocarbon'),
event('polycyclic aromatic hydrocarbon',regulate,'AHR'),
event('AHR',regulate,'polycyclic aromatic hydrocarbon'),
event('polycyclic aromatic hydrocarbon',increase,'AHR'),
event('AHR',increase,'polycyclic aromatic hydrocarbon'),
event('polycyclic aromatic hydrocarbon',activate,'ARNT'),
event('AHR',activate,'ARNT'),
event('polycyclic aromatic hydrocarbon',inhibit,'AHR'),
event('AHR',inhibit,'polycyclic aromatic hydrocarbon'),
event('polycyclic aromatic hydrocarbon',prevent,'AHR'),
event('polycyclic aromatic hydrocarbon',prevent,'ARNT'),
event('AHR',prevent,'polycyclic aromatic hydrocarbon'),
event('AHR',prevent,'ARNT'),
event('ARNT',prevent,'polycyclic aromatic hydrocarbon'),
event('ARNT',prevent,'AHR'),
event('polycyclic aromatic hydrocarbon',suppress,'ARNT'),
event('AHR',suppress,'ARNT'),
event('CREB',bind,'ARNT'),
event('polycyclic aromatic hydrocarbon',involve,'AHR'),
event('polycyclic aromatic hydrocarbon',involve,'ARNT'),
event('AHR',involve,'polycyclic aromatic hydrocarbon'),
event('AHR',involve,'ARNT'),
event('NR1H4',suppress,'FXR'),
event('FXR',suppress,'NR1H4'),
event('NR1H4',regulate,'FXR'),
event('FXR',regulate,'NR1H4'),
event('GATA',regulate,'HNF1A'),
event('GATA',regulate,'NF1'),
event('GATA',regulate,'HNF1'),
event('HNF1A',bind,'vitamin D analog'),
event('HNF1A',bind,'GC'),
event('NF1',bind,'vitamin D analog'),
event('NF1',bind,'GC'),
event('HNF1',bind,'vitamin D analog'),
event('HNF1',bind,'GC'),
event('HNF1A',modulate,'HNF1'),
event('HNF1',modulate,'HNF1A'),
event('HNF1A',stimulate,'NF1'),
event('HNF1A',stimulate,'HNF1'),
event('NF1',stimulate,'HNF1A'),
event('NF1',stimulate,'HNF1'),
event('HNF1',stimulate,'HNF1A'),
event('HNF1',stimulate,'NF1'),
event('HNF1A',require,'NF1'),
event('HNF1A',require,'HNF1'),
event('NF1',require,'HNF1A'),
event('NF1',require,'HNF1'),
event('HNF1',require,'HNF1A'),
event('HNF1',require,'NF1'),
event('HNF1A',activate,'NF1'),
event('HNF1A',activate,'HNF1'),
event('NF1',activate,'HNF1A'),
event('NF1',activate,'HNF1'),
event('HNF1',activate,'HNF1A'),
event('HNF1',activate,'NF1'),
event('HNF1A',bind,'NF1'),
event('HNF1A',bind,'HNF1'),
event('NF1',bind,'HNF1A'),
event('NF1',bind,'HNF1'),
event('HNF1',bind,'HNF1A'),
event('HNF1',bind,'NF1'),
event('HNF1A',involve,'NF1'),
event('HNF1A',involve,'HNF1'),
event('NF1',involve,'HNF1A'),
event('NF1',involve,'HNF1'),
event('HNF1',involve,'HNF1A'),
event('HNF1',involve,'NF1'),
event('HNF4A      ',target,'progesterone analog'),
event('HNF4A      ',target,'NR3C1'),
event('HNF1A',regulate,'HNF4A      '),
event('NF1',regulate,'HNF4A      '),
event('HNF1',regulate,'HNF4A      '),
event('vitamin D analog',lead,'HNF4A      '),
event('GC',lead,'HNF4A      '),
event('HNF4A      ',involve,'HNF1A'),
event('HNF4A      ',involve,'NF1'),
event('HNF4A      ',involve,'HNF1'),
event('HNF4A      ',express,'OCT'),
event('HNF1A',increase,'NF1'),
event('HNF1A',increase,'HNF1'),
event('HNF4A      ',increase,'HNF1A'),
event('HNF4A      ',increase,'NF1'),
event('HNF4A      ',increase,'HNF1'),
event('NF1',increase,'HNF1A'),
event('NF1',increase,'HNF1'),
event('HNF1',increase,'HNF1A'),
event('HNF1',increase,'NF1'),
event('androstane',inhibit,'HNF4A      '),
event('NR1I3',inhibit,'HNF4A      '),
event('HNF4A      ',bind,'progesterone analog'),
event('HNF4A      ',bind,'GSTM'),
event('HNF4A      ',bind,'ABCC3'),
event('HNF4A      ',modulate,'vitamin D analog'),
event('HNF4A      ',modulate,'androstane'),
event('HNF4A      ',modulate,'NR3C1'),
event('HNF4A      ',modulate,'NR1I3'),
event('HNF4A      ',modulate,'NR1I2'),
event('HNF4A      ',modulate,'GC'),
event('NR1I2',increase,'HNF4A      '),
event('HNF4A      ',decrease,'NR1I2'),
event('vitamin D analog',increase,'androstane'),
event('vitamin D analog',increase,'NR1I3'),
event('GC',increase,'androstane'),
event('GC',increase,'NR1I3'),
event('NR1I2',inhibit,'CYP7A1'),
event('NR1I2',inhibit,'cyp7a1'),
event('NR1I2',interact,'HNF4A      '),
event('NR1I2',interact,'CYP7A1'),
event('NR1I2',interact,'vitamin D analog'),
event('NR1I2',interact,'cyp7a1'),
event('NR1I2',interact,'GC'),
event('vitamin D analog',bind,'CYP7A1'),
event('vitamin D analog',bind,'cyp7a1'),
event('HNF4A      ',bind,'CYP7A1'),
event('HNF4A      ',bind,'vitamin D analog'),
event('HNF4A      ',bind,'cyp7a1'),
event('HNF4A      ',bind,'GC'),
event('NR1I2',bind,'CYP7A1'),
event('NR1I2',bind,'cyp7a1'),
event('GC',bind,'CYP7A1'),
event('GC',bind,'cyp7a1'),
event('PPARA',regulate,'vitamin D analog'),
event('PPARA',regulate,'GC'),
event('HNF4A      ',bind,'TST1'),
event('TST1',decrease,'HNF4A      '),
event('HNF4A      ',associate,'TST1'),
event('AML1',target,'HNF4A      '),
event('TST1',bind,'NR1H4'),
event('TST1',bind,'HNF4A      '),
event('TST1',bind,'NR1I2'),
event('TST1',bind,'FXR'),
event('HNF4A      ',target,'TST1'),
event('HNF4A      ',target,'HNF1A'),
event('HNF4A      ',target,'NF1'),
event('HNF4A      ',target,'HNF1'),
event('NR3C1',induce,'HNF4A      '),
event('NR3C1',induce,'OCT1'),
event('NR3C1',induce,'OCT'),
event('HNF4A      ',bind,'OCT1'),
event('HNF4A      ',bind,'OCT'),
event('CAAT',bind,'OCT1'),
event('CAAT',bind,'OCT'),
event('CYP7A1',induce,'cyp7a1'),
event('cyp7a1',induce,'CYP7A1'),
event('vitamin D analog',increase,'cyp3a4'),
event('GC',increase,'cyp3a4'),
event('PPARA',induce,'abca1'),
event('vitamin D analog',bind,'PPARA'),
event('GC',bind,'PPARA'),
event('cyp3a4',induce,'clotrimazole'),
event('cyp3a4',induce,'RU486'),
event('cyp3a4',induce,'NR1I2'),
event('NR1I2',increase,'cyp3a4'),
event('HNF4A      ',increase,'NR0B2'),
event('androstane',induce,'NR1I3'),
event('NR1I3',induce,'androstane'),
event('androstane',inhibit,'CYP7A1'),
event('androstane',inhibit,'cyp7a1'),
event('NR1I3',inhibit,'CYP7A1'),
event('NR1I3',inhibit,'cyp7a1'),
event('androstane',bind,'CYP7A1'),
event('androstane',bind,'cyp7a1'),
event('NR1I3',bind,'CYP7A1'),
event('NR1I3',bind,'cyp7a1'),
event('TCPOBOP',increase,'androstane'),
event('TCPOBOP',increase,'NR1I3'),
event('androstane',increase,'NR1I3'),
event('NR1I3',increase,'androstane'),
event('androstane',increase,'vitamin D analog'),
event('androstane',increase,'NR3C1'),
event('androstane',increase,'GC'),
event('NR1I3',increase,'vitamin D analog'),
event('NR1I3',increase,'NR3C1'),
event('NR1I3',increase,'GC'),
event('TCPOBOP',decrease,'androstane'),
event('TCPOBOP',decrease,'NR1I3'),
event('CYP7A1',mediate,'NR0B2'),
event('cyp7a1',mediate,'NR0B2'),
event('vitamin D analog',regulate,'NR1H4'),
event('vitamin D analog',regulate,'FXR'),
event('GC',regulate,'NR1H4'),
event('GC',regulate,'FXR'),
event('vitamin D analog',increase,'NR1H4'),
event('vitamin D analog',increase,'HNF4A      '),
event('vitamin D analog',increase,'PPARG'),
event('vitamin D analog',increase,'FXR'),
event('GC',increase,'NR1H4'),
event('GC',increase,'HNF4A      '),
event('GC',increase,'PPARG'),
event('GC',increase,'FXR'),
event('vitamin D analog',interact,'HNF4A      '),
event('GC',interact,'HNF4A      '),
event('vitamin D analog',activate,'HNF4A      '),
event('GC',activate,'HNF4A      '),
event('vitamin D analog',induce,'HNF4A      '),
event('GC',induce,'HNF4A      '),
event('HNF4A      ',bind,'CREB'),
event('CREB',bind,'HNF4A      '),
event('SREBP1',interact,'vitamin D analog'),
event('SREBP1',interact,'GC'),
event('SREBP1',inhibit,'vitamin D analog'),
event('SREBP1',inhibit,'androstane'),
event('SREBP1',inhibit,'GC'),
event('carbaldehyde',induce,'CYP2A6'),
event('androstane',induce,'CYP2A6'),
event('NR1I3',induce,'CYP2A6'),
event('NR1I2',induce,'CYP2A6'),
event('androstane',activate,'CYP2A6'),
event('NR1I3',activate,'CYP2A6'),
event('NR1I2',activate,'CYP2A6'),
event('vitamin D analog',bind,'CYP2A6'),
event('NR1I2',bind,'CYP2A6'),
event('GC',bind,'CYP2A6'),
event('vitamin D analog',stimulate,'HNF4A      '),
event('GC',stimulate,'HNF4A      '),
event('HNF1A',require,'HNF4A      '),
event('NF1',require,'HNF4A      '),
event('HNF1',require,'HNF4A      '),
event('vitamin D analog',bind,'HNF4A      '),
event('GC',bind,'HNF4A      '),
event('vitamin D analog',mediate,'HNF4A      '),
event('GC',mediate,'HNF4A      '),
event('vitamin D analog',mediate,'CYP2A6'),
event('GC',mediate,'CYP2A6'),
event('HNF4A      ',target,'vitamin D analog'),
event('HNF4A      ',target,'GC'),
event('PPARA',target,'NR1H4'),
event('PPARA',target,'NR0B2'),
event('PPARA',target,'FXR'),
event('NR0B2',enhance,'NR5A2'),
event('PPARA',repress,'NR0B2'),
event('NR0B2',bind,'NR5A2'),
event('vitamin K2',recruit,'NR5A2'),
event('vitamin K2',recruit,'NR0B2'),
event('progesterone analog',recruit,'NR5A2'),
event('progesterone analog',recruit,'NR0B2'),
event('vitamin D analog',recruit,'NR5A2'),
event('vitamin D analog',recruit,'NR0B2'),
event('GC',recruit,'NR5A2'),
event('GC',recruit,'NR0B2'),
event('vitamin K2',enhance,'progesterone analog'),
event('vitamin K2',enhance,'vitamin D analog'),
event('vitamin K2',enhance,'NR0B2'),
event('vitamin K2',enhance,'GC'),
event('NR5A2',stimulate,'cholesterol'),
event('NR5A2',target,'cholesterol'),
event('cholesterol',mediate,'NR1H2'),
event('cholesterol',mediate,'NR1H3'),
event('NR0B2',interact,'NR1H2'),
event('NR0B2',interact,'NR1H3'),
event('NR0B2',inhibit,'abca1'),
event('SREBP1',increase,'fatty acid'),
event('SREBP1',increase,'NR1H3'),
event('SREBP1',increase,'PPARA'),
event('SREBP1',increase,'PPARG'),
event('NR1H3',regulate,'dehydroepiandrosterone'),
event('NR1H3',regulate,'sult2a1'),
event('dehydroepiandrosterone',bind,'sult2a1'),
event('sult2a1',bind,'dehydroepiandrosterone'),
event('NR0B2',bind,'cyproterone acetate'),
event('NR1H4',target,'ABCB1'),
event('NR1H4',target,'ABCB4'),
event('FXR',target,'ABCB1'),
event('FXR',target,'ABCB4'),
event('NR0B2',involve,'PPARA'),
event('NR0B2',increase,'PPARA'),
event('NR0B2',recruit,'TST1'),
event('NR0B2',decrease,'progesterone analog'),
event('NR5A2',stimulate,'NR0B2'),
event('NR0B2',repress,'NR5A2'),
event('NR5A2',regulate,'NR0B2'),
event('NR0B2',inhibit,'NR5A2'),
event('NR0B2',interact,'NR5A2'),
event('NR0B2',regulate,'NR1H4'),
event('NR0B2',regulate,'NR5A2'),
event('NR0B2',regulate,'FXR'),
event('NR0B2',bind,'GATA'),
event('NR0B2',induce,'NR1H4'),
event('NR0B2',induce,'FXR'),
event('NR0B2',interact,'STAT'),
event('NR0B2',involve,'STAT'),
event('STAT',repress,'NR0B2'),
event('NR0B2',inhibit,'STAT'),
event('THRB',increase,'THRA'),
event('RARA',increase,'P53'),
event('RARB',increase,'P53'),
event('RARA',stimulate,'CYP1A1'),
event('RARB',stimulate,'CYP1A1'),
event('RARA',associate,'RARB'),
event('RARB',associate,'RARA'),
event('RARA',increase,'progesterone analog'),
event('progesterone analog',inhibit,'RARA'),
event('HNF4A      ',target,'PPARA'),
event('HNF4A      ',repress,'PPARA'),
event('PPARA',associate,'cyp2c19'),
event('PPARA',associate,'cyp3a4'),
event('vitamin D analog',modulate,'PPARA'),
event('GC',modulate,'PPARA'),
event('PPARA',stimulate,'vitamin D analog'),
event('PPARA',stimulate,'GC'),
event('androstane',induce,'PPARA'),
event('NR1I3',induce,'PPARA'),
event('PPARA',activate,'progesterone analog'),
event('PPARA',target,'PPARG'),
event('PPARG',target,'PPARA'),
event('fibrate',associate,'vitamin D analog'),
event('fibrate',associate,'GC'),
event('fibrate',activate,'vitamin D analog'),
event('fibrate',activate,'PPARA'),
event('fibrate',activate,'GC'),
event('fibrate',prevent,'vitamin D analog'),
event('fibrate',prevent,'PPARA'),
event('fibrate',prevent,'GC'),
event('fibrate',enhance,'PPARA'),
event('NR1H4',enhance,'FXR'),
event('FXR',enhance,'NR1H4'),
event('fibrate',target,'PPARA'),
event('PPARA',increase,'WY-14'),
event('CYP4A',stimulate,'progesterone analog'),
event('PPARA',mediate,'fibrate'),
event('PPARA',increase,'CYP4A'),
event('fibrate',increase,'TST1'),
event('PPARA',target,'androstane'),
event('PPARA',target,'NR1I3'),
event('dichloropyridyloxy',decrease,'PPARA'),
event('fibrate',bind,'PPARA'),
event('fibrate',bind,'PPARG'),
event('PPARA',bind,'progesterone analog'),
event('PPARA',involve,'cholesterol'),
event('cholesterol',increase,'abca1'),
event('abca1',promote,'PPARA'),
event('fibrate',induce,'PPARA'),
event('GATA1',induce,'NR1H4'),
event('GATA1',induce,'FXR'),
event('GATA',induce,'NR1H4'),
event('GATA',induce,'FXR'),
event('progesterone analog',enhance,'vitamin D analog'),
event('progesterone analog',enhance,'GC'),
event('androstane',enhance,'vitamin D analog'),
event('androstane',enhance,'GC'),
event('NR1I3',enhance,'vitamin D analog'),
event('NR1I3',enhance,'GC'),
event('progesterone analog',suppress,'Phenobarbital'),
event('progesterone analog',suppress,'cyp2b6'),
event('progesterone analog',suppress,'cyp2c9'),
event('progesterone analog',suppress,'cyp2c19'),
event('progesterone analog',suppress,'cyp3a4'),
event('androstane',suppress,'Phenobarbital'),
event('androstane',suppress,'cyp2b6'),
event('androstane',suppress,'cyp2c9'),
event('androstane',suppress,'cyp2c19'),
event('androstane',suppress,'cyp3a4'),
event('NR1I3',suppress,'Phenobarbital'),
event('NR1I3',suppress,'cyp2b6'),
event('NR1I3',suppress,'cyp2c9'),
event('NR1I3',suppress,'cyp2c19'),
event('NR1I3',suppress,'cyp3a4'),
event('PPARA',decrease,'cyp3a4'),
event('progesterone analog',associate,'PPARD'),
event('progesterone analog',associate,'GATA1'),
event('progesterone analog',associate,'GATA'),
event('TATA',associate,'PPARA'),
event('TATA',associate,'PPARD'),
event('TATA',associate,'GATA1'),
event('TATA',associate,'GATA'),
event('PPARA',enhance,'progesterone analog'),
event('PPARA',induce,'PPARG'),
event('PPARG',induce,'PPARA'),
event('progesterone analog',activate,'PPARA'),
event('progesterone analog',activate,'PPARD'),
event('progesterone analog',activate,'PPARG'),
event('PPARA',interact,'progesterone analog'),
event('PPARA',suppress,'PPARG'),
event('PPARG',suppress,'PPARA'),
event('PPARA',enhance,'PPARG'),
event('PPARG',enhance,'PPARA'),
event('PPARA',express,'TST1'),
event('PPARG',express,'TST1'),
event('CYP1A1',associate,'vitamin D analog'),
event('CYP1A1',associate,'PPARA'),
event('CYP1A1',associate,'PPARG'),
event('CYP1A1',associate,'GC'),
event('vitamin D analog',bind,'CP2'),
event('GC',bind,'CP2'),
event('NR1H4',modulate,'PPARA'),
event('FXR',modulate,'PPARA'),
event('PPARA',increase,'PPARG'),
event('PPARG',increase,'PPARA'),
event('PPARA',associate,'vitamin D analog'),
event('PPARA',associate,'GC'),
event('PPARG',associate,'vitamin D analog'),
event('PPARG',associate,'GC'),
event('PPARA',trigger,'progesterone analog'),
event('PPARG',trigger,'progesterone analog'),
event('CAAT',bind,'PPARA'),
event('CAAT',bind,'PPARG'),
event('CEBP',enhance,'PPARA'),
event('CEBP',enhance,'PPARG'),
event('CEBPA',enhance,'PPARA'),
event('CEBPA',enhance,'PPARG'),
event('PPARA',bind,'PPARG'),
event('PPARG',bind,'PPARA'),
event('vitamin D analog',require,'PPARA'),
event('vitamin D analog',require,'PPARG'),
event('vitamin D analog',require,'GC'),
event('PPARA',require,'vitamin D analog'),
event('PPARA',require,'PPARG'),
event('PPARA',require,'GC'),
event('PPARG',require,'vitamin D analog'),
event('PPARG',require,'PPARA'),
event('PPARG',require,'GC'),
event('GC',require,'vitamin D analog'),
event('GC',require,'PPARA'),
event('GC',require,'PPARG'),
event('vitamin D analog',mediate,'PPARA'),
event('vitamin D analog',mediate,'PPARG'),
event('GC',mediate,'PPARA'),
event('GC',mediate,'PPARG'),
event('PPARA',promote,'PPARG'),
event('PPARG',promote,'PPARA'),
event('HLF',activate,'PPARA'),
event('PPARA',activate,'PPARG'),
event('PPARG',activate,'PPARA'),
event('CAAT',bind,'CEBPB'),
event('E2F',target,'PPARA'),
event('androstane',suppress,'vitamin D analog'),
event('androstane',suppress,'GC'),
event('NR1I3',suppress,'vitamin D analog'),
event('NR1I3',suppress,'GC'),
event('androstane',recruit,'vitamin D analog'),
event('androstane',recruit,'GC'),
event('NR1I3',recruit,'vitamin D analog'),
event('NR1I3',recruit,'GC'),
event('vitamin D analog',lead,'androstane'),
event('vitamin D analog',lead,'NR1I3'),
event('androstane',lead,'vitamin D analog'),
event('androstane',lead,'GC'),
event('NR1I3',lead,'vitamin D analog'),
event('NR1I3',lead,'GC'),
event('GC',lead,'androstane'),
event('GC',lead,'NR1I3'),
event('CREB',require,'CAAT'),
event('vitamin D analog',involve,'polycyclic aromatic hydrocarbon'),
event('vitamin D analog',involve,'AHR'),
event('GC',involve,'polycyclic aromatic hydrocarbon'),
event('GC',involve,'AHR'),
event('vitamin D analog',require,'VDR'),
event('GC',require,'VDR'),
event('NR0B2',inhibit,'CYP7A1'),
event('NR0B2',inhibit,'cyp7a1'),
event('NR0B2',increase,'cholesterol'),
event('NR0B2',inhibit,'polycyclic aromatic hydrocarbon'),
event('NR0B2',inhibit,'AHR'),
event('NR0B2',inhibit,'CYP1A1'),
event('NR0B2',inhibit,'ugt1a1'),
event('NR0B2',inhibit,'ugt1a6'),
event('ARNT',interact,'polycyclic aromatic hydrocarbon'),
event('ARNT',interact,'AHR'),
event('ARNT',interact,'NR0B2'),
event('NR0B2',inhibit,'ARNT'),
event('CYP7A1',increase,'NR0B2'),
event('NR1I2',increase,'NR0B2'),
event('cyp3a4',increase,'NR0B2'),
event('cyp7a1',increase,'NR0B2'),
event('NR1H4',inhibit,'CYP7A1'),
event('NR1H4',inhibit,'cholesterol'),
event('NR1H4',inhibit,'NR0B2'),
event('NR1H4',inhibit,'cyp7a1'),
event('FXR',inhibit,'CYP7A1'),
event('FXR',inhibit,'cholesterol'),
event('FXR',inhibit,'NR0B2'),
event('FXR',inhibit,'cyp7a1'),
event('NR1H4',recruit,'CYP7A1'),
event('NR1H4',recruit,'NR0B2'),
event('NR1H4',recruit,'cyp7a1'),
event('FXR',recruit,'CYP7A1'),
event('FXR',recruit,'NR0B2'),
event('FXR',recruit,'cyp7a1'),
event('CYP7A1',regulate,'cholesterol'),
event('cyp7a1',regulate,'cholesterol'),
event('cholesterol',decrease,'CYP7A1'),
event('cholesterol',decrease,'cyp7a1'),
event('cyp2c9',increase,'HNF4A      '),
event('cyp2c19',increase,'HNF4A      '),
event('HNF4A      ',bind,'cyp2c9'),
event('HNF4A      ',bind,'cyp2c19'),
event('vitamin D analog',activate,'cyp2d6'),
event('vitamin D analog',activate,'cyp3a4'),
event('vitamin D analog',activate,'cyp3a5'),
event('GC',activate,'cyp2d6'),
event('GC',activate,'cyp3a4'),
event('GC',activate,'cyp3a5'),
event('NR0B2',increase,'progesterone analog'),
event('progesterone analog',decrease,'NR0B2'),
event('NR0B2',repress,'cyp2d6'),
event('cyp2d6',induce,'HNF4A      '),
event('CYP1A1',mediate,'CYP2A6'),
event('CYP1B1',mediate,'CYP2A6'),
event('CYP1A1',decrease,'CYP1A2'),
event('CYP1A2',decrease,'CYP1A1'),
event('cyp2d6',increase,'NR0B2'),
event('NR0B2',repress,'HNF4A      '),
event('NR0B2',lead,'cyp2d6'),
event('CYP1A1',decrease,'Phenobarbital'),
event('CYP1A1',decrease,'CYP2A6'),
event('CYP1A1',decrease,'cyp2b6'),
event('CYP1A1',decrease,'cyp3a4'),
event('CYP1A2',decrease,'Phenobarbital'),
event('CYP1A2',decrease,'CYP2A6'),
event('CYP1A2',decrease,'cyp2b6'),
event('CYP1A2',decrease,'cyp3a4'),
event('cyp2c19',decrease,'CYP2A6'),
event('cyp2c19',decrease,'cyp3a4'),
event('Phenobarbital',inhibit,'efavirenz'),
event('cyp2b6',inhibit,'efavirenz'),
event('cyp2c19',induce,'fibrate'),
event('cyp2c19',increase,'fibrate'),
event('cyp2c19',increase,'PPARA'),
event('cyp2c19',regulate,'PPARA'),
event('vitamin D analog',induce,'AKR1C4'),
event('vitamin D analog',induce,'cyp2c19'),
event('GC',induce,'AKR1C4'),
event('GC',induce,'cyp2c19'),
event('Phenobarbital',activate,'cyp2b6'),
event('cyp2b6',activate,'Phenobarbital'),
event('Phenobarbital',stimulate,'CYP2A6'),
event('Phenobarbital',stimulate,'cyp2d6'),
event('Phenobarbital',stimulate,'cyp3a4'),
event('cyp2b6',stimulate,'CYP2A6'),
event('cyp2b6',stimulate,'cyp2d6'),
event('cyp2b6',stimulate,'cyp3a4'),
event('AKR1C4',induce,'Phenobarbital'),
event('AKR1C4',induce,'CYP1A1'),
event('AKR1C4',induce,'CYP2B1'),
event('AKR1C4',induce,'cyp2b6'),
event('CYP1A1',induce,'CYP2B1'),
event('CYP1A2',induce,'CYP1A1'),
event('CYP1A2',induce,'CYP2B1'),
event('androstane',mediate,'Phenobarbital'),
event('androstane',mediate,'CYP2B1'),
event('androstane',mediate,'cyp2b6'),
event('NR1I3',mediate,'Phenobarbital'),
event('NR1I3',mediate,'CYP2B1'),
event('NR1I3',mediate,'cyp2b6'),
event('CITCO',increase,'androstane'),
event('CITCO',increase,'NR1I3'),
event('cyp2d6',decrease,'AKR1C4'),
event('cyp2d6',decrease,'cyp2c19'),
event('cyp2d6',mediate,'Phenobarbital'),
event('cyp2d6',mediate,'cyp2b6'),
event('progesterone analog',suppress,'CYP2B1'),
event('Phenobarbital',inhibit,'CYP2B1'),
event('Phenobarbital',inhibit,'cyp2b6'),
event('CYP2B1',inhibit,'Phenobarbital'),
event('CYP2B1',inhibit,'cyp2b6'),
event('cyp2b6',inhibit,'Phenobarbital'),
event('cyp2b6',inhibit,'CYP2B1'),
event('Phenobarbital',increase,'androstane'),
event('Phenobarbital',increase,'NR1I3'),
event('cyp2b6',increase,'androstane'),
event('cyp2b6',increase,'NR1I3'),
event('fibrate',activate,'androstane'),
event('fibrate',activate,'NR1I3'),
event('CYP1A1',involve,'CYP4A'),
event('CYP1B1',involve,'CYP4A'),
event('fibrate',induce,'Phenobarbital'),
event('fibrate',induce,'AKR1C4'),
event('fibrate',induce,'CYP4A'),
event('fibrate',induce,'CYP2B1'),
event('fibrate',induce,'CYP2B2'),
event('fibrate',induce,'cyp2b6'),
event('fibrate',induce,'cyp2c19'),
event('CYP1A1',increase,'Phenobarbital'),
event('CYP1A1',increase,'CYP2B1'),
event('CYP1A1',increase,'cyp2b6'),
event('CAP',mediate,'Phenobarbital'),
event('CAP',mediate,'CYP2B1'),
event('CAP',mediate,'cyp2b6'),
event('NR0B2',repress,'CYP7A1'),
event('NR0B2',repress,'cholesterol'),
event('NR0B2',repress,'cyp7a1'),
event('NR0B2',target,'CYP7A1'),
event('NR0B2',target,'cholesterol'),
event('NR0B2',target,'cyp7a1'),
event('androstane',regulate,'cyp2c19'),
event('NR3C1',regulate,'cyp2c19'),
event('NR1I3',regulate,'cyp2c19'),
event('HNF4A      ',regulate,'cyp2c19'),
event('NR1I2',regulate,'cyp2c19'),
event('Phenobarbital',increase,'cyp2b6'),
event('Phenobarbital',increase,'cyp2c19'),
event('cyp2b6',increase,'Phenobarbital'),
event('cyp2b6',increase,'cyp2c19'),
event('Phenobarbital',express,'cyp2c19'),
event('CYP1A1',express,'cyp2c19'),
event('CYP1A2',express,'cyp2c19'),
event('cyp2b6',express,'cyp2c19'),
event('cyp3a4',express,'cyp2c19'),
event('CYP7A1',associate,'cholesterol'),
event('cyp7a1',associate,'cholesterol'),
event('ABCG8',associate,'cholesterol'),
event('cyp2c9',inhibit,'vitamin D analog'),
event('cyp2c9',inhibit,'CYP1A1'),
event('cyp2c9',inhibit,'CYP1A2'),
event('cyp2c9',inhibit,'GC'),
event('cyp2c19',inhibit,'vitamin D analog'),
event('cyp2c19',inhibit,'CYP1A1'),
event('cyp2c19',inhibit,'CYP1A2'),
event('cyp2c19',inhibit,'GC'),
event('cyp2c9',mediate,'CYP2A6'),
event('cyp2c9',mediate,'cyp3a4'),
event('cyp2c19',mediate,'CYP2A6'),
event('cyp2c19',mediate,'cyp3a4'),
event('cyp2d6',mediate,'CYP2A6'),
event('cyp2d6',mediate,'cyp3a4'),
event('progesterone analog',decrease,'cyp2d6'),
event('spiro',increase,'cyp2d6'),
event('dehydroepiandrosterone',express,'cyp3a5'),
event('cyp3a4',express,'cyp3a5'),
event('cyp2c19',stimulate,'CYP1A1'),
event('Phenobarbital',induce,'SLCO1B1'),
event('cyp3a4',decrease,'simvastatin'),
event('NR1I2',increase,'paclitaxel'),
event('cyp3a4',increase,'paclitaxel'),
event('ABCB1',increase,'paclitaxel'),
event('NR1I2',suppress,'paclitaxel'),
event('NR1I2',suppress,'ABCB1'),
event('progesterone analog',associate,'nqo1'),
event('nqo1',associate,'progesterone analog'),
event('NFE2L2',target,'nqo1'),
event('AP1',target,'nqo1'),
event('NRF2',target,'nqo1'),
event('nqo1',express,'NFE2L2'),
event('nqo1',express,'AP1'),
event('nqo1',express,'NRF2'),
event('TST1',express,'nqo1'),
event('HNF4A      ',decrease,'Phenobarbital'),
event('HNF4A      ',decrease,'dehydroepiandrosterone'),
event('HNF4A      ',decrease,'androstane'),
event('HNF4A      ',decrease,'NR1I3'),
event('HNF4A      ',decrease,'CYP2A6'),
event('HNF4A      ',decrease,'SLCO1A2'),
event('HNF4A      ',decrease,'cyp2b6'),
event('HNF4A      ',decrease,'cyp2c9'),
event('HNF4A      ',decrease,'cyp2c19'),
event('HNF4A      ',decrease,'cyp2d6'),
event('HNF4A      ',decrease,'cyp3a4'),
event('HNF4A      ',decrease,'ugt1a1'),
event('HNF4A      ',decrease,'ugt1a9'),
event('HNF4A      ',decrease,'sult2a1'),
event('HNF4A      ',decrease,'ABCB11'),
event('HNF4A      ',decrease,'ABCB1'),
event('HNF4A      ',decrease,'ABCC2'),
event('HNF4A      ',decrease,'SLCO1B1'),
event('NR1H4',lead,'NR0B2'),
event('NR1H4',lead,'ABCB11'),
event('NR1H4',lead,'FXR'),
event('FXR',lead,'NR1H4'),
event('FXR',lead,'NR0B2'),
event('FXR',lead,'ABCB11'),
event('androstane',induce,'NR1I2'),
event('NR1I3',induce,'NR1I2'),
event('androstane',stimulate,'Cyp2b10'),
event('NR1I3',stimulate,'Cyp2b10'),
event('NR1I2',stimulate,'Cyp2b10'),
event('ABCG5',promote,'cholesterol'),
event('ABCG8',promote,'cholesterol'),
event('ABCG5',regulate,'cholesterol'),
event('ABCG8',mediate,'cholesterol'),
event('progesterone analog',decrease,'ABCG5'),
event('progesterone analog',decrease,'ABCG8'),
event('progesterone analog',increase,'cholesterol'),
event('ABCG5',mediate,'cholesterol'),
event('cholesterol',involve,'ABCG5'),
event('cholesterol',involve,'ABCG8'),
event('cholesterol',involve,'ABCB11'),
event('cholesterol',involve,'ABCB1'),
event('cholesterol',involve,'ABCB4'),
event('cholesterol',regulate,'PPARA'),
event('ABCB4',regulate,'cholesterol'),
event('abca1',involve,'cholesterol'),
event('ABCG5',involve,'cholesterol'),
event('ABCG8',involve,'cholesterol'),
event('ABCG1',involve,'cholesterol'),
event('cholesterol',mediate,'abca1'),
event('cholesterol',mediate,'ABCG1'),
event('ABCG5',suppress,'cholesterol'),
event('ABCG8',suppress,'cholesterol'),
event('ABCG5',prevent,'cholesterol'),
event('T0901317',decrease,'cholesterol'),
event('abca1',decrease,'NR1H2'),
event('abca1',decrease,'NR1H3'),
event('abca1',decrease,'ABCG8'),
event('abca1',decrease,'ABCG1'),
event('oxysterol',induce,'abca1'),
event('oxysterol',induce,'ABCG5'),
event('oxysterol',induce,'ABCG8'),
event('oxysterol',induce,'ABCG1'),
event('ABCG5',express,'ABCB1'),
event('ABCG8',express,'ABCB1'),
event('ABCG1',express,'ABCB1'),
event('ABCC3',express,'ABCB1'),
event('ABCG1',promote,'cholesterol'),
event('ABCG1',regulate,'cholesterol'),
event('ABCG1',associate,'NR1H4'),
event('ABCG1',associate,'FXR'),
event('FABP6',participate,'cholesterol'),
event('fatty acid',express,'FABP6'),
event('NR3C1',activate,'NR1H4'),
event('NR3C1',activate,'FXR'),
event('NR3C1',activate,'TST1'),
event('NR1H4',regulate,'NR0B2'),
event('FXR',regulate,'NR0B2'),
event('NR1H4',mediate,'NR3C1'),
event('FXR',mediate,'NR3C1'),
event('NR1H4',regulate,'NR3C1'),
event('FXR',regulate,'NR3C1'),
event('NR3C1',bind,'NR1H4'),
event('NR3C1',bind,'FXR'),
event('NR1H4',bind,'NR3C1'),
event('FXR',bind,'NR3C1'),
event('NR1H4',repress,'cholesterol'),
event('FXR',repress,'cholesterol'),
event('NR1H4',increase,'NR0B2'),
event('FXR',increase,'NR0B2'),
event('NR1H4',associate,'FXR'),
event('FXR',associate,'NR1H4'),
event('RU486',mediate,'NR3C1'),
event('NR1H4',modulate,'NR0B2'),
event('FXR',modulate,'NR0B2'),
event('NR1H4',prevent,'NR0B2'),
event('FXR',prevent,'NR0B2'),
event('HNF1A',increase,'cholesterol'),
event('NF1',increase,'cholesterol'),
event('HNF1',increase,'cholesterol'),
event('CYP7A1',activate,'NR1H4'),
event('CYP7A1',activate,'NR0B2'),
event('CYP7A1',activate,'FXR'),
event('cyp7a1',activate,'NR1H4'),
event('cyp7a1',activate,'NR0B2'),
event('cyp7a1',activate,'FXR'),
event('paclitaxel',stimulate,'ABCB1'),
event('cyp3a5',bind,'ABCB1'),
event('NR5A2',increase,'guggulsterone'),
event('NR0B2',increase,'guggulsterone'),
event('NR0B2',increase,'NR5A2'),
event('abca1',increase,'guggulsterone'),
event('abca1',increase,'NR5A2'),
event('abca1',increase,'NR0B2'),
event('guggulsterone',enhance,'NR5A2'),
event('guggulsterone',enhance,'NR0B2'),
event('vitamin D analog',express,'GSTP1'),
event('vitamin D analog',express,'ABCB1'),
event('GC',express,'GSTP1'),
event('GC',express,'ABCB1'),
event('ABCC2',increase,'abca1'),
event('ABCC2',increase,'ABCB4'),
event('ABCC4',increase,'abca1'),
event('ABCC4',increase,'ABCB4'),
event('ABCB4',decrease,'cholesterol'),
event('ABCC2',modulate,'ABCC1'),
event('ABCC3',modulate,'ABCC1'),
event('ABCC4',modulate,'ABCC1'),
event('CAAT',bind,'ABCC1'),
event('CAAT',bind,'STAT'),
event('STAT',bind,'ABCC1'),
event('ABCB1',associate,'ABCC1'),
event('CEBP',regulate,'ABCB1'),
event('CEBP',regulate,'ABCC2'),
event('CEBPA',regulate,'ABCB1'),
event('CEBPA',regulate,'ABCC2'),
event('CEBP',activate,'ABCB1'),
event('CEBP',activate,'ABCC2'),
event('CEBPA',activate,'ABCB1'),
event('CEBPA',activate,'ABCC2'),
event('cholesterol',associate,'abca1'),
event('etoposide',increase,'ABCB1'),
event('etoposide',increase,'ABCC3'),
event('ABCC1',inhibit,'vitamin D analog'),
event('ABCC1',inhibit,'GC'),
event('ABCC4',inhibit,'vitamin D analog'),
event('ABCC4',inhibit,'GC'),
event('ABCC1',decrease,'vitamin D analog'),
event('ABCC1',decrease,'GC'),
event('ABCC4',decrease,'vitamin D analog'),
event('ABCC4',decrease,'GC'),
event('HNF3B',associate,'progesterone analog'),
event('GATA2',bind,'CEBP'),
event('GATA2',bind,'CEBPA'),
event('GATA',bind,'CEBP'),
event('GATA',bind,'CEBPA'),
event('AML1',bind,'CEBP'),
event('AML1',bind,'CEBPA'),
event('VMYB',bind,'GATA'),
event('VMYB',bind,'AML1'),
event('VMYB',bind,'CREB'),
event('MYB',bind,'GATA'),
event('MYB',bind,'AML1'),
event('MYB',bind,'CREB'),
event('AML1',target,'TST1')
]).
