base([
event('NR1I3',bind,'Phenobarbital'),
event('Phenobarbital',induce,'ALAS1'),
event('fibrate',increase,'PPARA'),
event('fibrate',increase,'SLC10A2'),
event('NR1H4',induce,'ABCB11'),
event('FXR',induce,'ABCB11'),
event('NR1H4',bind,'ABCB11'),
event('FXR',bind,'ABCB11'),
event('ABCC1',increase,'NR1H4'),
event('ABCC1',increase,'FXR'),
event('ABCC4',increase,'NR1H4'),
event('ABCC4',increase,'FXR'),
event('NR1H4',activate,'NR0B2'),
event('NR1H4',activate,'SLCO1A2'),
event('NR1H4',activate,'ABCB11'),
event('NR1H4',activate,'SLCO1B3'),
event('FXR',activate,'NR0B2'),
event('FXR',activate,'SLCO1A2'),
event('FXR',activate,'ABCB11'),
event('FXR',activate,'SLCO1B3'),
event('NR0B2',mediate,'SLCO1A2'),
event('NR0B2',mediate,'SLCO1B1'),
event('Phenobarbital',mediate,'androstane'),
event('Phenobarbital',mediate,'NR1I3'),
event('cyp2b6',mediate,'androstane'),
event('cyp2b6',mediate,'NR1I3'),
event('NR1I3',bind,'cyp2b6'),
event('NR0B2',inhibit,'NR3C1'),
event('NR0B2',inhibit,'NR1I3'),
event('NR0B2',inhibit,'cyp2b6'),
event('NR0B2',bind,'Phenobarbital'),
event('NR0B2',bind,'NR3C1'),
event('NR0B2',bind,'NR1I3'),
event('NR0B2',inhibit,'Phenobarbital'),
event('HNF4A      ',activate,'cyp2d6'),
event('HNF4A      ',increase,'cyp2d6'),
event('HNF1A',bind,'retinoic acid'),
event('HNF4A      ',bind,'retinoic acid'),
event('retinoic acid',increase,'HNF1A'),
event('retinoic acid',increase,'HNF4A      '),
event('PPARA',involve,'cholesterol'),
event('fibrate',lead,'FABP6'),
event('PPARA',lead,'FABP6'),
event('FABP6',target,'PPARA'),
event('NR1H4',bind,'FXR'),
event('FXR',bind,'NR1H4'),
event('ABCB4',bind,'NR1H4'),
event('ABCB4',bind,'FXR'),
event('chenodeoxycholic acid',activate,'ABCB4'),
event('NR1H4',activate,'ABCB4'),
event('FXR',activate,'ABCB4'),
event('ABCB4',induce,'chenodeoxycholic acid'),
event('Lithocholic acid',bind,'VDR'),
event('retinoic acid',bind,'VDR'),
event('SLCO1A2',regulate,'NR1H4'),
event('SLCO1A2',regulate,'NR1I2'),
event('SLCO1A2',regulate,'FXR'),
event('SLCO1B3',regulate,'NR1H4'),
event('SLCO1B3',regulate,'NR1I2'),
event('SLCO1B3',regulate,'FXR'),
event('clotrimazole',induce,'SLCO1A2'),
event('clotrimazole',induce,'SLCO1B3'),
event('chenodeoxycholic acid',induce,'SLCO1A2'),
event('chenodeoxycholic acid',induce,'SLCO1B3'),
event('cholesterol',induce,'SLCO1A2'),
event('cholesterol',induce,'SLCO1B3'),
event('NR1H4',induce,'SLCO1A2'),
event('NR1H4',induce,'SLCO1B3'),
event('NR1I2',induce,'SLCO1A2'),
event('NR1I2',induce,'SLCO1B3'),
event('FXR',induce,'SLCO1A2'),
event('FXR',induce,'SLCO1B3'),
event('chenodeoxycholic acid',increase,'NR1H4'),
event('chenodeoxycholic acid',increase,'SLCO1A2'),
event('chenodeoxycholic acid',increase,'FXR'),
event('chenodeoxycholic acid',increase,'SLCO1B3')
event('NR1I3',bind,'Phenobarbital'),
event('Phenobarbital',induce,'ALAS1'),
event('fibrate',increase,'PPARA'),
event('fibrate',increase,'SLC10A2'),
event('NR1H4',induce,'ABCB11'),
event('FXR',induce,'ABCB11'),
event('NR1H4',bind,'ABCB11'),
event('FXR',bind,'ABCB11'),
event('ABCC1',increase,'NR1H4'),
event('ABCC1',increase,'FXR'),
event('ABCC4',increase,'NR1H4'),
event('ABCC4',increase,'FXR'),
event('NR1H4',activate,'NR0B2'),
event('NR1H4',activate,'SLCO1A2'),
event('NR1H4',activate,'ABCB11'),
event('NR1H4',activate,'SLCO1B3'),
event('FXR',activate,'NR0B2'),
event('FXR',activate,'SLCO1A2'),
event('FXR',activate,'ABCB11'),
event('FXR',activate,'SLCO1B3'),
event('NR0B2',mediate,'SLCO1A2'),
event('NR0B2',mediate,'SLCO1B1'),
event('Phenobarbital',mediate,'androstane'),
event('Phenobarbital',mediate,'NR1I3'),
event('cyp2b6',mediate,'androstane'),
event('cyp2b6',mediate,'NR1I3'),
event('NR1I3',bind,'cyp2b6'),
event('NR0B2',inhibit,'NR3C1'),
event('NR0B2',inhibit,'NR1I3'),
event('NR0B2',inhibit,'cyp2b6'),
event('NR0B2',bind,'Phenobarbital'),
event('NR0B2',bind,'NR3C1'),
event('NR0B2',bind,'NR1I3'),
event('NR0B2',inhibit,'Phenobarbital'),
event('HNF4A      ',activate,'cyp2d6'),
event('HNF4A      ',increase,'cyp2d6'),
event('HNF1A',bind,'retinoic acid'),
event('HNF4A      ',bind,'retinoic acid'),
event('retinoic acid',increase,'HNF1A'),
event('retinoic acid',increase,'HNF4A      '),
event('PPARA',involve,'cholesterol'),
event('fibrate',lead,'FABP6'),
event('PPARA',lead,'FABP6'),
event('FABP6',target,'PPARA'),
event('NR1H4',bind,'FXR'),
event('FXR',bind,'NR1H4'),
event('ABCB4',bind,'NR1H4'),
event('ABCB4',bind,'FXR'),
event('chenodeoxycholic acid',activate,'ABCB4'),
event('NR1H4',activate,'ABCB4'),
event('FXR',activate,'ABCB4'),
event('ABCB4',induce,'chenodeoxycholic acid'),
event('Lithocholic acid',bind,'VDR'),
event('retinoic acid',bind,'VDR'),
event('SLCO1A2',regulate,'NR1H4'),
event('SLCO1A2',regulate,'NR1I2'),
event('SLCO1A2',regulate,'FXR'),
event('SLCO1B3',regulate,'NR1H4'),
event('SLCO1B3',regulate,'NR1I2'),
event('SLCO1B3',regulate,'FXR'),
event('clotrimazole',induce,'SLCO1A2'),
event('clotrimazole',induce,'SLCO1B3'),
event('chenodeoxycholic acid',induce,'SLCO1A2'),
event('chenodeoxycholic acid',induce,'SLCO1B3'),
event('cholesterol',induce,'SLCO1A2'),
event('cholesterol',induce,'SLCO1B3'),
event('NR1H4',induce,'SLCO1A2'),
event('NR1H4',induce,'SLCO1B3'),
event('NR1I2',induce,'SLCO1A2'),
event('NR1I2',induce,'SLCO1B3'),
event('FXR',induce,'SLCO1A2'),
event('FXR',induce,'SLCO1B3'),
event('chenodeoxycholic acid',increase,'NR1H4'),
event('chenodeoxycholic acid',increase,'SLCO1A2'),
event('chenodeoxycholic acid',increase,'FXR'),
event('chenodeoxycholic acid',increase,'SLCO1B3')
]).
