%//[NR1H4, CYP7A1, NR0B2, cholesterol, bile acid, RXR, LXR, NR5A2, LRH, LCAT, NR1H3, oxysterols, FOXA2, NR1H2, RUNX1, PBX1, CLIP1, CLIP2, CLIP3, BAAT, CAP, NPC1, NPC2, NPC1L1, CH25H, NCEH1, NCBP2, NCBP1, TCAP, NRBF2, MDFIC, MDFI, FAF1, RIT1, SRY]
receptor('NR1H4').
transcription_factor('NR1H4').
protein('NR1H4').
protein('CYP7A1').
enzyme('CYP7A1').
receptor('NR0B2').
protein('NR0B2').
ligand('bile acid').
ligand('oxysterols').
ligand('cholesterol').
receptor('RXR').
protein('RXR').
receptor('NR5A2').
protein('NR5A2').
transcription_factor('NR5A2').
receptor('LRH').
protein('LRH').
receptor('NR1H3').
protein('NR1H3').
%receptor('oxysterols').
%protein('oxysterols').
transcription_factor('FOXA2').
protein('FOXA2').
receptor('NR1H2').
protein('NR1H2').
transcription_factor('NR1H2').
transcription_factor('RUNX1').
protein('RUNX1').
transcription_factor('PBX1').
protein('PBX1').
transcription_factor('CLIP1').
protein('CLIP1').
protein('CLIP2').
ligand('CLIP3').
protein('CLIP3').
enzyme('BAAT').
transcription_factor('CAP').
protein('CAP').
protein('NPC2').
protein('NPC1L1').
protein('CH25H').
enzyme('CH25H').
enzyme('NCEH1').
protein('NCBP2').
protein('NCBP1').
protein('TCAP').
enzyme('TCAP').
transcription_factor('NRBF2').
protein('NRBF2').
transcription_factor('MDFIC').
protein('MDFIC').
transcription_factor('MDFI').
protein('MDFI').
ligand('FAF1').
protein('FAF1').
ligand('RIT1').
protein('RIT1').
enzyme('RIT1').
transcription_factor('SRY').
protein('SRY').

%las siguientes lineas son para evitar errores en el proceso no deben ser modificadas
enzyme('').
protein('').
transcription_factor('').
receptor('').
ligand('').
