wkr_ligand('').
wkr_proteins('').
wkr_transcription_factors('').
wkr_adaptor_proteins('').
wkr_receptors('').
wkr_enzymes('').
wkr_cholesterol_7_alpha_hydroxylase(X):-wkr_cyp7a1_protein_human(X).
wkr_steroid_hydroxylases(X):-wkr_cholesterol_7_alpha_hydroxylase(X).
wkr_rna_binding_proteins(X):-wkr_rbm6_protein_human(X).
wkr_nucleoproteins(X):-wkr_rna_binding_proteins(X).
wkr_extracellular_matrix_proteins(X):-wkr_snep_protein_mouse(X).
wkr_brain_diseases_metabolic_inborn(X):-wkr_phenylketonurias(X).
wkr_metabolism_inborn_errors(X):-wkr_brain_diseases_metabolic_inborn(X).
wkr_metabolic_diseases(X):-wkr_metabolism_inborn_errors(X).
wkr_amino_acid_metabolism_inborn_errors(X):-wkr_phenylketonurias(X).
wkr_metabolism_inborn_errors(X):-wkr_amino_acid_metabolism_inborn_errors(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_nuclear_receptor_subfamily_0_group_b_member_2(X).
wkr_n_acetylglucosaminyltransferases(X):-wkr_large_protein_human(X).
wkr_n_terminal_acetyltransferase_a(X):-wkr_naa15_protein_human(X).
wkr_n_terminal_acetyltransferase_e(X):-wkr_naa15_protein_human(X).
wkr_receptor_muscarinic_m3(X):-wkr_chrm3_protein_human(X).
wkr_acyltransferases(X):-wkr_bile_acid_coa_amino_acid_n_acyltransferase(X).
