wkr_ligand('').
wkr_proteins('').
wkr_transcription_factors('').
wkr_adaptor_proteins('').
wkr_receptors('').
wkr_enzymes('').
wkr_carrier_proteins(X):-wkr_nudcl_protein_rat(X).
wkr_proteins(X):-wkr_carrier_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_proteins(X).
wkr_chemicals_and_drugs_category(X):-wkr_amino_acids_peptides_and_proteins(X).
wkr_ras_proteins(X):-wkr_rit1_protein_human(X).
wkr_monomeric_gtp_binding_proteins(X):-wkr_ras_proteins(X).
wkr_gtp_binding_proteins(X):-wkr_monomeric_gtp_binding_proteins(X).
wkr_gtp_phosphohydrolases(X):-wkr_gtp_binding_proteins(X).
wkr_acid_anhydride_hydrolases(X):-wkr_gtp_phosphohydrolases(X).
wkr_hydrolases(X):-wkr_acid_anhydride_hydrolases(X).
wkr_enzymes(X):-wkr_hydrolases(X).
wkr_enzymes_and_coenzymes(X):-wkr_enzymes(X).
wkr_chemicals_and_drugs_category(X):-wkr_enzymes_and_coenzymes(X).
wkr_carrier_proteins(X):-wkr_gtp_binding_proteins(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_monomeric_gtp_binding_proteins(X).
wkr_ligand(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_peptides(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_amino_acids_peptides_and_proteins(X):-wkr_peptides(X).
wkr_proteins(X):-wkr_intracellular_signaling_peptides_and_proteins(X).
wkr_eukaryotic_initiation_factor_4g(X):-wkr_eif4g3_protein_mouse(X).
wkr_eukaryotic_initiation_factor_4f(X):-wkr_eukaryotic_initiation_factor_4g(X).
wkr_rna_cap_binding_proteins(X):-wkr_eukaryotic_initiation_factor_4f(X).
wkr_rna_binding_proteins(X):-wkr_rna_cap_binding_proteins(X).
wkr_carrier_proteins(X):-wkr_rna_binding_proteins(X).
wkr_nucleoproteins(X):-wkr_rna_binding_proteins(X).
wkr_proteins(X):-wkr_nucleoproteins(X).
wkr_eukaryotic_initiation_factors(X):-wkr_eukaryotic_initiation_factor_4f(X).
wkr_peptide_initiation_factors(X):-wkr_eukaryotic_initiation_factors(X).
wkr_ribosomal_proteins(X):-wkr_peptide_initiation_factors(X).
wkr_proteins(X):-wkr_ribosomal_proteins(X).
wkr_amidohydrolases(X):-wkr_pm20d1_protein_mouse(X).
wkr_hydrolases(X):-wkr_amidohydrolases(X).
wkr_death_domain_receptor_signaling_adaptor_proteins(X):-wkr_tnf_receptor_associated_death_domain_protein(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_death_domain_receptor_signaling_adaptor_proteins(X).
wkr_adaptor_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_carrier_proteins(X):-wkr_adaptor_proteins_signal_transducing(X).
wkr_apoptosis_regulatory_proteins(X):-wkr_death_domain_receptor_signaling_adaptor_proteins(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_apoptosis_regulatory_proteins(X).
wkr_tumor_necrosis_factor_receptor_associated_peptides_and_proteins(X):-wkr_tnf_receptor_associated_death_domain_protein(X).
wkr_adaptor_proteins_signal_transducing(X):-wkr_tumor_necrosis_factor_receptor_associated_peptides_and_proteins(X).
wkr_core_binding_factor_alpha_subunits(X):-wkr_core_binding_factor_alpha_2_subunit(X).
wkr_core_binding_factors(X):-wkr_core_binding_factor_alpha_subunits(X).
wkr_transcription_factors(X):-wkr_core_binding_factors(X).
wkr_proteins(X):-wkr_transcription_factors(X).
wkr_guanine_nucleotide_exchange_factors(X):-wkr_dennd2d_protein_human(X).
wkr_gtp_binding_protein_regulators(X):-wkr_guanine_nucleotide_exchange_factors(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_gtp_binding_protein_regulators(X).
wkr_tumor_suppressor_proteins(X):-wkr_dennd2d_protein_human(X).
wkr_neoplasm_proteins(X):-wkr_tumor_suppressor_proteins(X).
wkr_proteins(X):-wkr_neoplasm_proteins(X).
wkr_nerve_tissue_proteins(X):-wkr_rabgap1l_protein_human(X).
wkr_proteins(X):-wkr_nerve_tissue_proteins(X).
wkr_gtpase_activating_proteins(X):-wkr_rabgap1l_protein_human(X).
wkr_gtp_binding_protein_regulators(X):-wkr_gtpase_activating_proteins(X).
wkr_cholesterol_7_alpha_hydroxylase(X):-wkr_cyp7a1_protein_human(X).
wkr_cytochrome_p450_family_7(X):-wkr_cholesterol_7_alpha_hydroxylase(X).
wkr_cytochrome_p_450_enzyme_system(X):-wkr_cytochrome_p450_family_7(X).
wkr_cytochromes(X):-wkr_cytochrome_p_450_enzyme_system(X).
wkr_enzymes_and_coenzymes(X):-wkr_cytochromes(X).
wkr_hemeproteins(X):-wkr_cytochromes(X).
wkr_proteins(X):-wkr_hemeproteins(X).
wkr_mixed_function_oxygenases(X):-wkr_cytochrome_p_450_enzyme_system(X).
wkr_oxygenases(X):-wkr_mixed_function_oxygenases(X).
wkr_oxidoreductases(X):-wkr_oxygenases(X).
wkr_enzymes(X):-wkr_oxidoreductases(X).
wkr_steroid_hydroxylases(X):-wkr_cholesterol_7_alpha_hydroxylase(X).
wkr_cytochrome_p_450_enzyme_system(X):-wkr_steroid_hydroxylases(X).
wkr_acyltransferases(X):-wkr_bile_acid_coa_amino_acid_n_acyltransferase(X).
wkr_transferases(X):-wkr_acyltransferases(X).
wkr_enzymes(X):-wkr_transferases(X).
wkr_cholestasis(X):-wkr_bile_acid_synthesis_defect_congenital_2(X).
wkr_bile_duct_diseases(X):-wkr_cholestasis(X).
wkr_biliary_tract_diseases(X):-wkr_bile_duct_diseases(X).
wkr_digestive_system_diseases(X):-wkr_biliary_tract_diseases(X).
wkr_diseases_category(X):-wkr_digestive_system_diseases(X).
wkr_oxidoreductases(X):-wkr_bile_acid_synthesis_defect_congenital_2(X).
wkr_deficiency(X):-wkr_bile_acid_synthesis_defect_congenital_2(X).
wkr_metabolism(X):-wkr_deficiency(X).
wkr_physiology(X):-wkr_metabolism(X).
wkr_subheadings_category(X):-wkr_physiology(X).
wkr_steroid_metabolism_inborn_errors(X):-wkr_bile_acid_synthesis_defect_congenital_2(X).
wkr_metabolism_inborn_errors(X):-wkr_steroid_metabolism_inborn_errors(X).
wkr_genetic_diseases_inborn(X):-wkr_metabolism_inborn_errors(X).
wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X):-wkr_genetic_diseases_inborn(X).
wkr_diseases_category(X):-wkr_congenital_hereditary_and_neonatal_diseases_and_abnormalities(X).
wkr_metabolic_diseases(X):-wkr_metabolism_inborn_errors(X).
wkr_nutritional_and_metabolic_diseases(X):-wkr_metabolic_diseases(X).
wkr_diseases_category(X):-wkr_nutritional_and_metabolic_diseases(X).
wkr_steroid_hydroxylases(X):-wkr_cholesterol_25_hydroxylase(X).
wkr_hypoalphalipoproteinemias(X):-wkr_lecithin_cholesterol_acyltransferase_deficiency(X).
wkr_hypolipoproteinemias(X):-wkr_hypoalphalipoproteinemias(X).
wkr_lipid_metabolism_inborn_errors(X):-wkr_hypolipoproteinemias(X).
wkr_metabolism_inborn_errors(X):-wkr_lipid_metabolism_inborn_errors(X).
wkr_lipid_metabolism_disorders(X):-wkr_lipid_metabolism_inborn_errors(X).
wkr_metabolic_diseases(X):-wkr_lipid_metabolism_disorders(X).
wkr_dyslipidemias(X):-wkr_hypolipoproteinemias(X).
wkr_lipid_metabolism_disorders(X):-wkr_dyslipidemias(X).
wkr_carboxylic_ester_hydrolases(X):-wkr_nceh1_protein_human(X).
wkr_esterases(X):-wkr_carboxylic_ester_hydrolases(X).
wkr_hydrolases(X):-wkr_esterases(X).
wkr_niemann_pick_diseases(X):-wkr_niemann_pick_disease_type_c(X).
wkr_sphingolipidoses(X):-wkr_niemann_pick_diseases(X).
wkr_lysosomal_storage_diseases_nervous_system(X):-wkr_sphingolipidoses(X).
wkr_brain_diseases_metabolic_inborn(X):-wkr_lysosomal_storage_diseases_nervous_system(X).
wkr_brain_diseases_metabolic(X):-wkr_brain_diseases_metabolic_inborn(X).
wkr_brain_diseases(X):-wkr_brain_diseases_metabolic(X).
wkr_central_nervous_system_diseases(X):-wkr_brain_diseases(X).
wkr_nervous_system_diseases(X):-wkr_central_nervous_system_diseases(X).
wkr_diseases_category(X):-wkr_nervous_system_diseases(X).
wkr_metabolic_diseases(X):-wkr_brain_diseases_metabolic(X).
wkr_metabolism_inborn_errors(X):-wkr_brain_diseases_metabolic_inborn(X).
wkr_lysosomal_storage_diseases(X):-wkr_lysosomal_storage_diseases_nervous_system(X).
wkr_metabolism_inborn_errors(X):-wkr_lysosomal_storage_diseases(X).
wkr_lipidoses(X):-wkr_sphingolipidoses(X).
wkr_lipid_metabolism_inborn_errors(X):-wkr_lipidoses(X).
wkr_lipid_metabolism_disorders(X):-wkr_lipidoses(X).
wkr_histiocytosis_non_langerhans_cell(X):-wkr_niemann_pick_diseases(X).
wkr_histiocytosis(X):-wkr_histiocytosis_non_langerhans_cell(X).
wkr_lymphatic_diseases(X):-wkr_histiocytosis(X).
wkr_hemic_and_lymphatic_diseases(X):-wkr_lymphatic_diseases(X).
wkr_diseases_category(X):-wkr_hemic_and_lymphatic_diseases(X).
wkr_membrane_transport_proteins(X):-wkr_npc1l1_protein_mouse(X).
wkr_carrier_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_membrane_proteins(X):-wkr_membrane_transport_proteins(X).
wkr_proteins(X):-wkr_membrane_proteins(X).
wkr_carrier_proteins(X):-wkr_npc2_protein_rat(X).
wkr_glycoproteins(X):-wkr_npc2_protein_rat(X).
wkr_glycoconjugates(X):-wkr_glycoproteins(X).
wkr_carbohydrates(X):-wkr_glycoconjugates(X).
wkr_chemicals_and_drugs_category(X):-wkr_carbohydrates(X).
wkr_proteins(X):-wkr_glycoproteins(X).
wkr_cell_membrane_structures(X):-wkr_membrane_microdomains(X).
wkr_cell_membrane(X):-wkr_cell_membrane_structures(X).
wkr_cellular_structures(X):-wkr_cell_membrane(X).
wkr_cells(X):-wkr_cellular_structures(X).
wkr_anatomy_category(X):-wkr_cells(X).
wkr_liver_x_receptors(X):-wkr_nr1h2_protein_rat(X).
wkr_dna_binding_proteins(X):-wkr_liver_x_receptors(X).
wkr_proteins(X):-wkr_dna_binding_proteins(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_liver_x_receptors(X).
wkr_receptors(X):-wkr_receptors_cytoplasmic_and_nuclear(X).
wkr_proteins(X):-wkr_receptors_cytoplasmic_and_nuclear(X).
wkr_liver_x_receptors(X):-wkr_nr1h3_protein_rat(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_nr5a2_protein_mouse(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_lrh_1_protein_zebrafish(X).
wkr_zebrafish_proteins(X):-wkr_lrh_1_protein_zebrafish(X).
wkr_fish_proteins(X):-wkr_zebrafish_proteins(X).
wkr_proteins(X):-wkr_fish_proteins(X).
wkr_liver_x_receptors(X):-wkr_nr1h3_protein_mouse(X).
wkr_sulfonamides(X):-wkr_t_0314407(X).
wkr_amides(X):-wkr_sulfonamides(X).
wkr_organic_chemicals(X):-wkr_amides(X).
wkr_chemicals_and_drugs_category(X):-wkr_organic_chemicals(X).
wkr_sulfones(X):-wkr_sulfonamides(X).
wkr_sulfur_compounds(X):-wkr_sulfones(X).
wkr_inorganic_chemicals(X):-wkr_sulfur_compounds(X).
wkr_chemicals_and_drugs_category(X):-wkr_inorganic_chemicals(X).
wkr_organic_chemicals(X):-wkr_sulfur_compounds(X).
wkr_transcription_factors(X):-wkr_nrbf2_protein_rat(X).
wkr_receptors_immunologic(X):-wkr_spalpha_protein_mouse(X).
wkr_receptors(X):-wkr_receptors_immunologic(X).
wkr_receptors_cell_surface(X):-wkr_receptors_immunologic(X).
wkr_receptors(X):-wkr_receptors_cell_surface(X).
wkr_membrane_proteins(X):-wkr_receptors_cell_surface(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_farnesoid_x_activated_receptor(X).
wkr_receptors_cytoplasmic_and_nuclear(X):-wkr_nuclear_receptor_subfamily_0_group_b_member_2(X).
wkr_myogenic_regulatory_factors(X):-wkr_mdfi_protein_mouse(X).
wkr_muscle_proteins(X):-wkr_myogenic_regulatory_factors(X).
wkr_contractile_proteins(X):-wkr_muscle_proteins(X).
wkr_proteins(X):-wkr_contractile_proteins(X).
wkr_basic_helix_loop_helix_transcription_factors(X):-wkr_myogenic_regulatory_factors(X).
wkr_dna_binding_proteins(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
wkr_transcription_factors(X):-wkr_basic_helix_loop_helix_transcription_factors(X).
wkr_homeodomain_proteins(X):-wkr_pknox1_protein_mouse(X).
wkr_dna_binding_proteins(X):-wkr_homeodomain_proteins(X).
wkr_sox_transcription_factors(X):-wkr_soxb2_transcription_factors(X).
wkr_dna_binding_proteins(X):-wkr_sox_transcription_factors(X).
wkr_high_mobility_group_proteins(X):-wkr_sox_transcription_factors(X).
wkr_chromosomal_proteins_non_histone(X):-wkr_high_mobility_group_proteins(X).
wkr_nuclear_proteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_proteins(X):-wkr_nuclear_proteins(X).
wkr_nucleoproteins(X):-wkr_chromosomal_proteins_non_histone(X).
wkr_transcription_factors(X):-wkr_sox_transcription_factors(X).
wkr_microtubule_associated_proteins(X):-wkr_cytoplasmic_linker_protein_115(X).
wkr_microtubule_proteins(X):-wkr_microtubule_associated_proteins(X).
wkr_biopolymers(X):-wkr_microtubule_proteins(X).
wkr_polymers(X):-wkr_biopolymers(X).
wkr_macromolecular_substances(X):-wkr_polymers(X).
wkr_chemicals_and_drugs_category(X):-wkr_macromolecular_substances(X).
wkr_biomedical_and_dental_materials(X):-wkr_polymers(X).
wkr_chemicals_and_drugs_category(X):-wkr_biomedical_and_dental_materials(X).
wkr_specialty_uses_of_chemicals(X):-wkr_biomedical_and_dental_materials(X).
wkr_chemical_actions_and_uses(X):-wkr_specialty_uses_of_chemicals(X).
wkr_chemicals_and_drugs_category(X):-wkr_chemical_actions_and_uses(X).
wkr_manufactured_materials(X):-wkr_biomedical_and_dental_materials(X).
wkr_technology_industry_and_agriculture(X):-wkr_manufactured_materials(X).
wkr_technology_and_food_and_beverages_category(X):-wkr_technology_industry_and_agriculture(X).
wkr_cytoskeletal_proteins(X):-wkr_microtubule_proteins(X).
wkr_proteins(X):-wkr_cytoskeletal_proteins(X).
wkr_nerve_tissue_proteins(X):-wkr_microtubule_associated_proteins(X).
wkr_intracellular_signaling_peptides_and_proteins(X):-wkr_clip3_protein_rat(X).
wkr_carrier_proteins(X):-wkr_clip4_protein_human(X).
wkr_eukaryotic_initiation_factors(X):-wkr_ctif_protein_human(X).
wkr_rna_cap_binding_proteins(X):-wkr_nuclear_cap_binding_protein_complex(X).
wkr_connectin(X):-wkr_tcap_protein_mouse(X).
wkr_protein_kinases(X):-wkr_connectin(X).
wkr_phosphotransferases_alcohol_group_acceptor_(X):-wkr_protein_kinases(X).
wkr_phosphotransferases(X):-wkr_phosphotransferases_alcohol_group_acceptor_(X).
wkr_transferases(X):-wkr_phosphotransferases(X).
wkr_muscle_proteins(X):-wkr_connectin(X).
wkr_hepatocyte_nuclear_factors(X):-wkr_hepatocyte_nuclear_factor_3_beta(X).
wkr_dna_binding_proteins(X):-wkr_hepatocyte_nuclear_factors(X).
wkr_nuclear_proteins(X):-wkr_hepatocyte_nuclear_factors(X).
wkr_transcription_factors(X):-wkr_hepatocyte_nuclear_factors(X).
wkr_forkhead_transcription_factors(X):-wkr_hepatocyte_nuclear_factor_3_beta(X).
wkr_winged_helix_transcription_factors(X):-wkr_forkhead_transcription_factors(X).
wkr_dna_binding_proteins(X):-wkr_winged_helix_transcription_factors(X).
wkr_transcription_factors(X):-wkr_winged_helix_transcription_factors(X).
