base([
event('NR1H4',decrease,'NR1H4'),
event('cholesterol',involve,'bile acid'),
event('cholesterol',involve,'cholesterol'),
event('NR0B2',mediate,'NR0B2'),
event('NR0B2',bind,'NR0B2'),
event('NR0B2',repress,'bile acid'),
event('NR0B2',repress,'NR0B2'),
event('NR0B2',regulate,'NR0B2'),
event('CYP7A1',regulate,'NR0B2'),
event('cholesterol',regulate,'NR0B2'),
event('NR5A2',increase,'NR0B2'),
event('NR5A2',increase,'NR0B2'),
event('NR0B2',inhibit,'CYP7A1'),
event('NR0B2',induce,'NR0B2'),
event('NR0B2',prevent,'NR0B2'),
event('bile acid',activate,'NR1H4'),
event('NR0B2',involve,'NR0B2'),
event('bile acid',induce,'bile acid'),
event('bile acid',enhance,'bile acid'),
event('NR1H4',induce,'NR0B2'),
event('NR1H4',bind,'NR0B2'),
event('NR1H4',involve,'bile acid'),
event('NR0B2',involve,'bile acid'),
event('bile acid',increase,'bile acid'),
event('NR0B2',promote,'NR1H2'),
event('BAAT',increase,'NRBF2'),
event('bile acid',increase,'NRBF2'),
event('BAAT',enhance,'NRBF2'),
event('bile acid',involve,'NR1H4'),
event('BAAT',increase,'bile acid'),
event('cholesterol',increase,'bile acid'),
event('bile acid',regulate,'NR1H4'),
event('cholesterol',regulate,'bile acid'),
event('cholesterol',enhance,'bile acid'),
event('NR5A2',express,'NR5A2'),
event('NR5A2',express,'NR5A2'),
event('NR5A2',express,'NR5A2'),
event('NR5A2',express,'NR5A2'),
event('NR5A2',regulate,'NR5A2'),
event('CYP7A1',regulate,'bile acid'),
event('CYP7A1',regulate,'cholesterol'),
event('cholesterol',regulate,'cholesterol'),
event('CYP7A1',activate,'CYP7A1'),
event('CYP7A1',regulate,'CYP7A1'),
event('NR5A2',target,'NR5A2'),
event('NR5A2',target,'NR5A2'),
event('NR5A2',target,'NR5A2'),
event('NR5A2',target,'NR5A2'),
event('NR5A2',bind,'NR5A2'),
event('NR5A2',bind,'NR5A2'),
event('NR5A2',bind,'NR5A2'),
event('NR5A2',bind,'NR5A2'),
event('CYP7A1',activate,'bile acid'),
event('CYP7A1',activate,'cholesterol'),
event('NR5A2',activate,'CYP7A1'),
event('NR5A2',activate,'bile acid'),
event('NR5A2',activate,'cholesterol'),
event('NR5A2',promote,'NR5A2'),
event('NPC2',involve,'cholesterol'),
event('NPC2',bind,'cholesterol'),
event('cholesterol',bind,'cholesterol'),
event('NPC2',regulate,'cholesterol'),
event('NPC2',induce,'NPC2'),
event('NPC2',increase,'cholesterol'),
event('NPC2',decrease,'cholesterol'),
event('LCAT',decrease,'LCAT'),
event('cholesterol',increase,'cholesterol'),
event('LCAT',bind,'LCAT'),
event('NCEH1',involve,'cholesterol'),
event('NCEH1',stimulate,'cholesterol'),
event('cholesterol',modulate,'cholesterol'),
event('cholesterol',induce,'cholesterol'),
event('cholesterol',inhibit,'cholesterol'),
event('NR1H4',target,'NR0B2'),
event('NR1H2',regulate,'cholesterol'),
event('oxysterols',bind,'bile acid'),
event('oxysterols',bind,'cholesterol'),
event('NRBF2',enhance,'bile acid'),
event('NR1H4',enhance,'bile acid'),
event('cholesterol',enhance,'cholesterol'),
event('NR1H2',enhance,'cholesterol'),
event('NRBF2',enhance,'cholesterol'),
event('bile acid',lead,'bile acid'),
event('NR5A2',mediate,'NR5A2'),
event('NR5A2',mediate,'NR5A2'),
event('NR5A2',mediate,'NR5A2'),
event('NR5A2',mediate,'NR5A2'),
event('NR5A2',interact,'NR5A2'),
event('NR5A2',interact,'NR5A2'),
event('NR5A2',interact,'NR5A2'),
event('NR5A2',interact,'NR5A2'),
event('NR5A2',mediate,'cholesterol'),
event('NR5A2',mediate,'cholesterol'),
event('NR5A2',involve,'NR5A2'),
event('NR5A2',involve,'NR5A2'),
event('NR5A2',involve,'NR5A2'),
event('NR5A2',involve,'NR5A2'),
event('bile acid',decrease,'cholesterol'),
event('NR5A2',involve,'bile acid'),
event('NR5A2',involve,'NR0B2'),
event('NR5A2',recognize,'NR5A2'),
event('NR5A2',translate,'NR5A2'),
event('NR5A2',activate,'NR5A2'),
event('bile acid',repress,'CYP7A1'),
event('bile acid',repress,'bile acid'),
event('bile acid',repress,'cholesterol'),
event('NR1H4',repress,'CYP7A1'),
event('NR1H4',require,'CYP7A1'),
event('NR1H4',require,'bile acid'),
event('NR1H4',require,'NR1H4'),
event('NR1H4',repress,'NR5A2'),
event('NR1H4',repress,'NR0B2'),
event('NR5A2',repress,'CYP7A1'),
event('NR5A2',repress,'NR0B2'),
event('NR1H4',stimulate,'NR5A2'),
event('NR1H4',stimulate,'NR0B2'),
event('NR5A2',induce,'CYP7A1'),
event('NR5A2',induce,'NR1H4'),
event('NR5A2',induce,'NR0B2'),
event('NR0B2',involve,'NR1H4'),
event('bile acid',decrease,'NR0B2'),
event('NR5A2',stimulate,'NR5A2'),
event('NR0B2',inhibit,'NR5A2'),
event('bile acid',activate,'NR5A2'),
event('CYP7A1',decrease,'cholesterol'),
event('cholesterol',decrease,'cholesterol'),
event('CYP7A1',bind,'NR5A2'),
event('CYP7A1',bind,'NR1H3'),
event('CYP7A1',bind,'NR1H2'),
event('CYP7A1',bind,'NR0B2'),
event('NR5A2',enhance,'NR0B2'),
event('NR0B2',enhance,'NR0B2'),
event('CYP7A1',increase,'NR1H3'),
event('CYP7A1',increase,'NR1H2'),
event('CYP7A1',increase,'NR0B2'),
event('cholesterol',increase,'NR1H3'),
event('cholesterol',increase,'NR1H2'),
event('cholesterol',increase,'NR0B2'),
event('cholesterol',express,'NR5A2'),
event('CYP7A1',increase,'NR5A2'),
event('NR5A2',activate,'NR0B2'),
event('NR5A2',increase,'cholesterol'),
event('NR0B2',interact,'NR0B2'),
event('CYP7A1',repress,'NR0B2'),
event('NR5A2',repress,'NR0B2'),
event('NR0B2',recruit,'NR5A2'),
event('NR0B2',recruit,'NR5A2'),
event('NR5A2',regulate,'NR5A2'),
event('NR5A2',regulate,'NR5A2'),
event('NR5A2',regulate,'NR5A2'),
event('NR5A2',promote,'NR5A2'),
event('NR5A2',promote,'NR5A2'),
event('NR5A2',promote,'NR5A2'),
event('NR1H4',activate,'NRBF2'),
event('NRBF2',target,'NR0B2'),
event('NR5A2',increase,'NRBF2'),
event('NR5A2',increase,'NR1H4'),
event('NR5A2',increase,'NRBF2'),
event('NR5A2',increase,'NR1H4'),
event('NR1H4',mediate,'NR5A2'),
event('NR1H4',mediate,'NR5A2'),
event('NR0B2',mediate,'NR5A2'),
event('NR0B2',mediate,'NR5A2'),
event('NR0B2',involve,'CYP7A1'),
event('NR0B2',involve,'cholesterol'),
event('NR0B2',bind,'bile acid'),
event('NR5A2',promote,'NR0B2'),
event('NR5A2',promote,'NR0B2'),
event('CH25H',inhibit,'CH25H'),
event('CH25H',target,'CH25H'),
event('cholesterol',target,'cholesterol'),
event('cholesterol',suppress,'cholesterol'),
event('CH25H',enhance,'CH25H'),
event('oxysterols',induce,'CH25H'),
event('NR1H2',induce,'CH25H'),
event('NR1H2',activate,'CH25H'),
event('NR1H2',activate,'NR1H2'),
event('oxysterols',regulate,'CYP7A1'),
event('oxysterols',regulate,'CH25H'),
event('CH25H',induce,'cholesterol'),
event('cholesterol',increase,'LCAT'),
event('LCAT',require,'LCAT'),
event('bile acid',prevent,'bile acid'),
event('NRBF2',repress,'CYP7A1'),
event('NRBF2',repress,'bile acid'),
event('NRBF2',repress,'NR5A2'),
event('NRBF2',repress,'NR5A2'),
event('NRBF2',repress,'NR1H2'),
event('NRBF2',repress,'NRBF2'),
event('NRBF2',repress,'NR0B2'),
event('NR1H4',repress,'bile acid'),
event('NR1H4',repress,'NR5A2'),
event('NR1H4',repress,'NR1H2'),
event('NR1H4',repress,'NRBF2'),
event('bile acid',regulate,'bile acid'),
event('NR1H2',regulate,'NR1H2'),
event('NRBF2',regulate,'NR1H2'),
event('cholesterol',bind,'bile acid'),
event('bile acid',mediate,'bile acid'),
event('NR5A2',activate,'NR5A2'),
event('NPC1',involve,'cholesterol'),
event('NPC1L1',involve,'cholesterol'),
event('cholesterol',prevent,'cholesterol'),
event('NPC1',express,'cholesterol'),
event('NPC1L1',express,'cholesterol'),
event('cholesterol',express,'cholesterol'),
event('NPC1',recognize,'cholesterol'),
event('NPC1L1',recognize,'cholesterol'),
event('NPC1',mediate,'cholesterol'),
event('NPC1L1',mediate,'cholesterol'),
event('cholesterol',associate,'cholesterol'),
event('NPC2',enhance,'cholesterol'),
event('NPC2',decrease,'NPC2'),
event('NPC2',induce,'cholesterol'),
event('NPC2',mediate,'cholesterol'),
event('NPC1',require,'cholesterol'),
event('cholesterol',require,'cholesterol'),
event('NPC1',increase,'NPC1'),
event('cholesterol',target,'NPC2'),
event('cholesterol',require,'NPC1'),
event('cholesterol',require,'NPC2'),
event('NPC2',bind,'NPC1'),
event('NPC1',bind,'NPC2'),
event('cholesterol',increase,'NPC2'),
event('NPC2',bind,'NPC2'),
event('NPC1',associate,'NPC1'),
event('NPC1',express,'NPC1'),
event('NPC1',express,'NPC1L1'),
event('NPC1',express,'NPC2'),
event('NPC1L1',express,'NPC1'),
event('NPC1L1',express,'NPC1L1'),
event('NPC1L1',express,'NPC2'),
event('NPC2',express,'NPC1'),
event('NPC2',express,'NPC1L1'),
event('NPC2',express,'NPC2'),
event('cholesterol',lead,'cholesterol'),
event('NPC1',increase,'cholesterol'),
event('cholesterol',associate,'NPC1'),
event('cholesterol',mediate,'cholesterol'),
event('cholesterol',lead,'oxysterols'),
event('NPC1',lead,'cholesterol'),
event('NPC1L1',lead,'cholesterol'),
event('NPC1',associate,'cholesterol'),
event('NPC1L1',associate,'cholesterol'),
event('NPC1',decrease,'NR1H2'),
event('NPC1L1',decrease,'NR1H2'),
event('NPC1',bind,'CYP7A1'),
event('NPC1',bind,'cholesterol'),
event('NPC1',bind,'NR1H2'),
event('NPC1L1',bind,'CYP7A1'),
event('NPC1L1',bind,'cholesterol'),
event('NPC1L1',bind,'NR1H2'),
event('cholesterol',bind,'CYP7A1'),
event('cholesterol',bind,'NR1H2'),
event('cholesterol',bind,'NPC1'),
event('cholesterol',express,'NPC1'),
event('NPC1',target,'cholesterol'),
event('NPC2',target,'cholesterol'),
event('NPC1',involve,'NPC2'),
event('cholesterol',repress,'NR5A2'),
event('cholesterol',repress,'NR5A2'),
event('cholesterol',repress,'NR0B2'),
event('NR5A2',increase,'NR5A2'),
event('NR5A2',increase,'NR5A2'),
event('NR5A2',increase,'NR5A2'),
event('NR5A2',increase,'NR5A2'),
event('NR0B2',inhibit,'NR5A2'),
event('cholesterol',retain,'NPC1'),
event('FAF1',bind,'FAF1'),
event('FAF1',modulate,'FAF1'),
event('RABGAP1L',decrease,'RABGAP1L'),
event('NR1H4',activate,'CYP7A1'),
event('NR1H4',activate,'NR1H3'),
event('NR1H4',activate,'NR1H2'),
event('NR5A2',bind,'NR1H2'),
event('NR1H3',bind,'NR1H2'),
event('NR1H2',bind,'NR1H2'),
event('NR0B2',enhance,'NR5A2'),
event('NR5A2',bind,'CYP7A1'),
event('NR1H3',bind,'CYP7A1'),
event('NR1H2',bind,'CYP7A1'),
event('NR0B2',bind,'CYP7A1'),
event('NR5A2',bind,'NR1H3'),
event('NR1H2',bind,'NR1H3'),
event('NR0B2',bind,'NR1H3'),
event('NR0B2',bind,'NR1H2'),
event('CYP7A1',increase,'CYP7A1'),
event('NR1H3',increase,'CYP7A1'),
event('NR1H3',increase,'NR5A2'),
event('NR1H3',increase,'NR1H3'),
event('NR1H3',increase,'NR1H2'),
event('NR1H3',increase,'NR0B2'),
event('NR1H2',increase,'CYP7A1'),
event('NR1H2',increase,'NR5A2'),
event('NR1H2',increase,'NR1H3'),
event('NR1H2',increase,'NR1H2'),
event('NR1H2',increase,'NR0B2'),
event('NR1H4',increase,'CYP7A1'),
event('NR1H4',increase,'NR5A2'),
event('NR1H4',increase,'NR1H3'),
event('NR1H4',increase,'NR1H2'),
event('NR1H4',increase,'NR0B2'),
event('NR0B2',increase,'CYP7A1'),
event('NR0B2',increase,'NR5A2'),
event('NR0B2',increase,'NR1H3'),
event('NR0B2',increase,'NR1H2'),
event('NR0B2',increase,'NR0B2'),
event('NR5A2',mediate,'bile acid'),
event('cholesterol',decrease,'bile acid'),
event('NR0B2',interact,'NR5A2'),
event('NR0B2',interact,'NR5A2'),
event('bile acid',regulate,'CYP7A1'),
event('NR0B2',decrease,'NR0B2'),
event('NR1H3',target,'NR1H4'),
event('NR1H3',target,'NR0B2'),
event('NR1H2',target,'NR1H4'),
event('NR1H2',target,'NR0B2'),
event('bile acid',inhibit,'cholesterol'),
event('bile acid',inhibit,'oxysterols'),
event('bile acid',inhibit,'NR1H3'),
event('bile acid',inhibit,'NR1H2'),
event('bile acid',inhibit,'NR0B2'),
event('NR1H2',regulate,'NR1H4'),
event('NR1H4',regulate,'NR1H4'),
event('NR1H2',regulate,'NR0B2'),
event('NR1H4',induce,'RUNX1'),
event('cholesterol',increase,'NR1H2'),
event('cholesterol',increase,'NR1H4'),
event('NR0B2',interact,'NR1H2'),
event('NR0B2',interact,'NR1H3'),
event('NR0B2',interact,'NR1H2'),
event('NR0B2',inhibit,'NR1H2'),
event('bile acid',enhance,'CYP7A1'),
event('NR0B2',target,'NR1H3'),
event('NR0B2',target,'NR1H2'),
event('NR0B2',target,'NR1H4'),
event('CYP7A1',increase,'bile acid'),
event('NR1H4',activate,'bile acid'),
event('oxysterols',increase,'NR1H3'),
event('oxysterols',increase,'NR1H2'),
event('bile acid',increase,'NR0B2'),
event('bile acid',activate,'CYP7A1'),
event('bile acid',activate,'NR1H3'),
event('bile acid',activate,'NR1H2'),
event('CYP7A1',stimulate,'cholesterol'),
event('CYP7A1',stimulate,'NR1H3'),
event('CYP7A1',stimulate,'NR1H2'),
event('bile acid',stimulate,'cholesterol'),
event('bile acid',stimulate,'NR1H3'),
event('bile acid',stimulate,'NR1H2'),
event('cholesterol',stimulate,'cholesterol'),
event('cholesterol',stimulate,'NR1H3'),
event('cholesterol',stimulate,'NR1H2'),
event('NR0B2',regulate,'bile acid'),
event('NR0B2',regulate,'NR1H3'),
event('NR0B2',regulate,'NR1H2'),
event('NR1H2',induce,'CYP7A1'),
event('NR1H2',bind,'NR0B2'),
event('NR1H4',regulate,'NR1H2'),
event('cholesterol',stimulate,'CYP7A1'),
event('cholesterol',stimulate,'bile acid'),
event('cholesterol',stimulate,'NR1H4'),
event('cholesterol',stimulate,'NR0B2'),
event('NR1H2',regulate,'CYP7A1'),
event('NR1H4',regulate,'CYP7A1'),
event('NR1H4',regulate,'NR0B2'),
event('NRBF2',regulate,'NR1H4'),
event('RIT1',inhibit,'RIT1'),
event('NUDC',bind,'NUDC'),
event('NUDC',increase,'NUDC'),
event('NUDC',suppress,'NUDC'),
event('NUDC',express,'NUDC'),
event('NUDC',lead,'NUDC'),
event('NUDC',dimerize,'NUDC'),
event('NUDC',promote,'NUDC'),
event('NR1H2',stimulate,'NR1H4'),
event('NR0B2',decrease,'NR1H3'),
event('NR0B2',decrease,'NR1H2'),
event('NR0B2',decrease,'NRBF2'),
event('NR1H3',involve,'NR0B2'),
event('NR1H2',involve,'NR0B2'),
event('NR1H2',activate,'cholesterol'),
event('NR1H2',promote,'cholesterol'),
event('NR1H2',require,'CYP7A1'),
event('NR1H3',require,'CYP7A1'),
event('NR1H2',require,'CYP7A1'),
event('NR5A2',regulate,'bile acid'),
event('NR5A2',regulate,'bile acid'),
event('NR0B2',bind,'NR5A2'),
event('NR0B2',bind,'NR5A2'),
event('NR5A2',induce,'CYP7A1'),
event('cholesterol',promote,'cholesterol'),
event('bile acid',activate,'bile acid'),
event('bile acid',activate,'cholesterol'),
event('NR1H4',induce,'bile acid'),
event('NR1H4',inhibit,'CYP7A1'),
event('NR1H4',suppress,'NR1H4'),
event('NR5A2',require,'CYP7A1'),
event('NR5A2',require,'CYP7A1'),
event('NR5A2',require,'NR1H4'),
event('NR5A2',require,'NR1H4'),
event('NR5A2',activate,'NR1H4'),
event('NR5A2',activate,'NR1H4'),
event('NR5A2',express,'bile acid'),
event('NR5A2',express,'cholesterol'),
event('NR5A2',express,'bile acid'),
event('NR5A2',express,'cholesterol'),
event('bile acid',suppress,'NR5A2'),
event('bile acid',suppress,'NR5A2'),
event('bile acid',suppress,'NR0B2'),
event('NR5A2',stimulate,'cholesterol'),
event('NR5A2',stimulate,'NR5A2'),
event('NR5A2',stimulate,'cholesterol'),
event('NR5A2',stimulate,'NR5A2'),
event('NR5A2',stimulate,'NR5A2'),
event('NR5A2',target,'bile acid'),
event('NR5A2',target,'cholesterol'),
event('NR5A2',target,'bile acid'),
event('NR5A2',target,'cholesterol'),
event('FAF1',regulate,'FAF1'),
event('FAF1',prevent,'FAF1'),
event('bile acid',mediate,'NR5A2'),
event('bile acid',mediate,'NR5A2'),
event('bile acid',mediate,'NR1H4'),
event('bile acid',mediate,'NR0B2'),
event('cholesterol',mediate,'bile acid'),
event('cholesterol',mediate,'NR5A2'),
event('cholesterol',mediate,'NR5A2'),
event('cholesterol',mediate,'NR1H4'),
event('cholesterol',mediate,'NR0B2'),
event('NR1H4',suppress,'CYP7A1'),
event('NR1H4',suppress,'cholesterol'),
event('NR1H4',suppress,'NR5A2'),
event('NR1H4',suppress,'NR5A2'),
event('NR0B2',suppress,'CYP7A1'),
event('NR0B2',suppress,'cholesterol'),
event('NR0B2',suppress,'NR5A2'),
event('NR0B2',suppress,'NR5A2'),
event('NR1H4',regulate,'bile acid'),
event('NR0B2',repress,'CYP7A1'),
event('NR0B2',repress,'NR5A2'),
event('NR0B2',repress,'NR5A2'),
event('bile acid',regulate,'cholesterol'),
event('bile acid',regulate,'oxysterols'),
event('cholesterol',regulate,'CYP7A1'),
event('cholesterol',regulate,'oxysterols'),
event('CYP7A1',bind,'bile acid'),
event('CYP7A1',bind,'NR1H4'),
event('NR0B2',inactivate,'CYP7A1'),
event('NR0B2',inactivate,'NR5A2'),
event('NR0B2',inactivate,'NR5A2'),
event('NR0B2',inactivate,'NR0B2'),
event('NR5A2',target,'CYP7A1'),
event('NR5A2',target,'CYP7A1'),
event('NR5A2',involve,'cholesterol'),
event('NR5A2',involve,'bile acid'),
event('NR5A2',involve,'cholesterol'),
event('NR1H4',bind,'NR5A2'),
event('NR1H4',bind,'NR5A2'),
event('NR1H4',bind,'NR1H4'),
event('NR5A2',bind,'NR1H4'),
event('NR5A2',bind,'NR1H4'),
event('NR5A2',recruit,'NR1H4'),
event('NR5A2',recruit,'NR1H4'),
event('NR0B2',increase,'NR5A2'),
event('NR1H2',induce,'NR1H2'),
event('NR1H2',induce,'NR1H4'),
event('NR1H4',express,'NR1H2'),
event('NR1H4',bind,'NRBF2'),
event('NR5A2',regulate,'NR0B2'),
event('NR5A2',regulate,'NR0B2'),
event('NR1H2',enhance,'NR1H2'),
event('NR1H2',induce,'cholesterol'),
event('NR1H2',bind,'bile acid'),
event('NR1H2',bind,'cholesterol'),
event('cholesterol',inhibit,'NR1H2'),
event('NR1H2',increase,'cholesterol'),
event('NR1H2',suppress,'cholesterol'),
event('NR1H2',modulate,'NR1H2'),
event('oxysterols',modulate,'oxysterols'),
event('cholesterol',enhance,'oxysterols'),
event('cholesterol',enhance,'NR1H2'),
event('bile acid',stimulate,'bile acid'),
event('bile acid',associate,'bile acid'),
event('bile acid',target,'NR1H4'),
event('NR1H4',target,'NR1H4'),
event('cholesterol',lead,'NR1H2'),
event('cholesterol',regulate,'NR1H2'),
event('NPC1',require,'NR1H2'),
event('NPC1L1',require,'NR1H2'),
event('NR1H2',decrease,'NPC1'),
event('NR1H2',decrease,'NR1H2'),
event('NR1H3',decrease,'NR1H2'),
event('NR1H2',inhibit,'NR1H2'),
event('NR1H2',increase,'NPC1'),
event('NR1H2',increase,'NPC2'),
event('cholesterol',induce,'NPC1'),
event('cholesterol',induce,'NPC2'),
event('cholesterol',induce,'NR1H2'),
event('NR1H2',lead,'cholesterol'),
event('NR1H2',modulate,'cholesterol'),
event('NPC1',promote,'cholesterol'),
event('NR1H2',target,'NR1H2'),
event('cholesterol',decrease,'NPC1'),
event('cholesterol',decrease,'NPC1L1'),
event('NPC1',prevent,'NR1H2'),
event('NPC1L1',prevent,'NR1H2'),
event('cholesterol',prevent,'NR1H2'),
event('cholesterol',associate,'NR1H4'),
event('NR1H2',recognize,'cholesterol'),
event('NPC1',inhibit,'cholesterol'),
event('NPC1L1',inhibit,'cholesterol'),
event('NR1H3',associate,'cholesterol'),
event('NR1H2',associate,'cholesterol'),
event('NPC1',modulate,'NPC1'),
event('NPC1',modulate,'NPC1L1'),
event('NPC1',modulate,'cholesterol'),
event('NPC1L1',modulate,'NPC1'),
event('NPC1L1',modulate,'NPC1L1'),
event('NPC1L1',modulate,'cholesterol'),
event('cholesterol',modulate,'NPC1'),
event('cholesterol',modulate,'NPC1L1'),
event('CYP7A1',decrease,'NPC1'),
event('CYP7A1',decrease,'NPC1L1'),
event('NPC1',associate,'CYP7A1'),
event('NPC1L1',associate,'CYP7A1'),
event('NPC1',target,'NR1H2'),
event('NPC1L1',target,'cholesterol'),
event('NPC1L1',target,'NR1H2'),
event('NR1H2',target,'cholesterol'),
event('NPC1',bind,'NPC1'),
event('NPC1',bind,'NPC1L1'),
event('NPC1L1',bind,'NPC1'),
event('NPC1L1',bind,'NPC1L1'),
event('cholesterol',involve,'NR1H3'),
event('cholesterol',involve,'NR1H2'),
event('NPC2',lead,'cholesterol'),
event('NPC1',require,'oxysterols'),
event('NPC2',require,'cholesterol'),
event('NPC2',require,'oxysterols'),
event('cholesterol',require,'oxysterols'),
event('LCAT',increase,'cholesterol'),
event('NR1H3',involve,'cholesterol'),
event('NPC1',regulate,'cholesterol'),
event('cholesterol',increase,'NPC1'),
event('NPC1L1',increase,'cholesterol'),
event('NR1H2',promote,'NPC1'),
event('cholesterol',increase,'NRBF2'),
event('NRBF2',target,'NRBF2'),
event('NR1H2',decrease,'NPC1L1'),
event('NRBF2',decrease,'NPC1'),
event('NRBF2',decrease,'NPC1L1'),
event('LCAT',bind,'NR1H3'),
event('LCAT',bind,'NR1H2'),
event('cholesterol',mediate,'oxysterols'),
event('NPC1',lead,'NR1H2'),
event('NRBF2',target,'cholesterol'),
event('cholesterol',associate,'NR1H2'),
event('cholesterol',activate,'NR1H2'),
event('oxysterols',activate,'NR1H2'),
event('cholesterol',suppress,'NR1H2'),
event('cholesterol',suppress,'CAP'),
event('NRBF2',target,'NRBF2'),
event('CYP7A1',bind,'NPC1'),
event('CYP7A1',bind,'NPC1L1'),
event('cholesterol',associate,'NPC1L1'),
event('NRBF2',regulate,'NRBF2'),
event('cholesterol',inhibit,'bile acid'),
event('NR0B2',express,'NR0B2'),
event('bile acid',interact,'bile acid'),
event('NR0B2',decrease,'CYP7A1'),
event('NR0B2',decrease,'cholesterol'),
event('NR0B2',inhibit,'NR0B2'),
event('FOXA2',target,'FOXA2'),
event('FOXA2',bind,'FOXA2'),
event('NR1H2',regulate,'bile acid'),
event('CYP7A1',involve,'cholesterol'),
event('NR1H2',involve,'cholesterol'),
event('NR1H4',involve,'cholesterol'),
event('NR1H2',promote,'NR1H2'),
event('NR1H3',bind,'NRBF2'),
event('cholesterol',enhance,'NR1H3'),
event('NRBF2',regulate,'bile acid'),
event('NRBF2',regulate,'cholesterol'),
event('NR1H4',regulate,'cholesterol'),
event('NRBF2',bind,'NR1H4'),
event('NR1H4',heterodimerize,'cholesterol'),
event('NR1H4',heterodimerize,'NRBF2'),
event('NRBF2',inhibit,'NR1H4'),
event('NR1H4',inhibit,'NR1H4'),
event('CYP7A1',repress,'NRBF2'),
event('CYP7A1',repress,'NR1H4'),
event('NRBF2',increase,'CYP7A1'),
event('NRBF2',increase,'NRBF2'),
event('NRBF2',increase,'NR1H4'),
event('NR1H4',increase,'NRBF2'),
event('NR1H4',increase,'NR1H4'),
event('NR1H4',express,'bile acid'),
event('NR1H4',express,'NR1H4'),
event('NR1H4',activate,'NR1H4'),
event('NR1H4',involve,'NR1H4'),
event('NR0B2',bind,'NRBF2'),
event('NR0B2',inhibit,'NRBF2'),
event('NRBF2',suppress,'NRBF2'),
event('NRBF2',bind,'NRBF2'),
event('NR1H4',target,'bile acid'),
event('BAAT',mediate,'NRBF2'),
event('BAAT',mediate,'NR1H4'),
event('NR1H4',increase,'BAAT'),
event('BAAT',mediate,'BAAT'),
event('BAAT',bind,'BAAT'),
event('BAAT',enhance,'BAAT'),
event('NRBF2',bind,'BAAT'),
event('RIT1',enhance,'RIT1'),
event('RIT1',regulate,'RIT1'),
event('cholesterol',mediate,'NR1H3'),
event('cholesterol',mediate,'NR1H2'),
event('cholesterol',activate,'cholesterol'),
event('oxysterols',involve,'NR1H2'),
event('NR1H2',bind,'oxysterols'),
event('NR1H2',activate,'bile acid'),
event('NR1H2',activate,'oxysterols'),
event('NR1H2',target,'CYP7A1'),
event('bile acid',lead,'cholesterol'),
event('NR1H2',lead,'bile acid'),
event('NR1H2',target,'bile acid'),
event('FAF1',suppress,'FAF1'),
event('FAF1',interact,'FAF1'),
event('NRBF2',prevent,'NRBF2'),
event('NR1H2',lead,'NR1H2'),
event('NR1H2',stimulate,'cholesterol'),
event('NR1H2',stimulate,'NR1H2'),
event('bile acid',increase,'NR1H4'),
event('NR1H4',enhance,'NR1H4'),
event('NR1H4',enhance,'FOXA2'),
event('NR1H4',regulate,'FOXA2'),
event('cholesterol',regulate,'NR1H3'),
event('cholesterol',regulate,'NR1H4'),
event('bile acid',target,'NR0B2'),
event('cholesterol',target,'NR1H4'),
event('cholesterol',target,'NR0B2'),
event('NR1H3',target,'oxysterols'),
event('NR1H2',target,'oxysterols'),
event('cholesterol',activate,'oxysterols'),
event('NR1H3',activate,'oxysterols'),
event('NR1H4',activate,'oxysterols'),
event('cholesterol',activate,'CYP7A1'),
event('cholesterol',activate,'NR1H3'),
event('cholesterol',activate,'NR1H4'),
event('NR1H3',activate,'CYP7A1'),
event('NR1H3',activate,'NR1H3'),
event('NR1H3',activate,'NR1H2'),
event('NR1H3',activate,'NR1H4'),
event('NR1H2',activate,'CYP7A1'),
event('NR1H2',activate,'NR1H3'),
event('NR1H2',activate,'NR1H4'),
event('NR0B2',inhibit,'cholesterol'),
event('NR0B2',increase,'NR1H4'),
event('cholesterol',induce,'NR1H4'),
event('NR1H4',induce,'NR1H4'),
event('NR1H4',inhibit,'NR0B2'),
event('NR0B2',induce,'CYP7A1'),
event('NR0B2',induce,'NR1H4'),
event('NR0B2',express,'NR1H4'),
event('NR1H4',mediate,'NRBF2'),
event('NR1H4',mediate,'NR0B2'),
event('NRBF2',regulate,'NR0B2'),
event('NR0B2',regulate,'NR5A2'),
event('NR0B2',regulate,'NR5A2'),
event('NR0B2',regulate,'NR1H4'),
event('NR1H4',induce,'BAAT'),
event('CYP7A1',involve,'bile acid'),
event('NR0B2',associate,'NR0B2'),
event('bile acid',involve,'bile acid'),
event('BAAT',target,'BAAT'),
event('BAAT',activate,'BAAT'),
event('bile acid',target,'BAAT'),
event('NRBF2',enhance,'NR1H2'),
event('NRBF2',enhance,'NRBF2'),
event('NR1H2',involve,'NR1H2'),
event('NR1H2',involve,'NRBF2'),
event('NR1H2',induce,'NRBF2'),
event('NR1H2',heterodimerize,'NR1H2'),
event('NR1H2',heterodimerize,'NRBF2'),
event('NR1H4',activate,'NR0B2'),
event('NR1H4',increase,'cholesterol'),
event('NR1H4',inhibit,'bile acid'),
event('NR1H4',inhibit,'cholesterol'),
event('NR1H4',modulate,'NR0B2'),
event('NR1H4',prevent,'NR0B2'),
event('NR0B2',recruit,'bile acid'),
event('NR0B2',recruit,'NR0B2'),
event('bile acid',bind,'bile acid'),
event('NR1H4',bind,'bile acid'),
event('NR1H2',prevent,'cholesterol'),
event('NR1H3',prevent,'cholesterol'),
event('NR1H2',prevent,'cholesterol'),
event('NR1H3',involve,'NR1H2'),
event('NR1H3',involve,'NR1H2'),
event('NR1H2',involve,'NR1H2'),
event('NR1H3',express,'NR1H2'),
event('NR1H3',express,'NR1H2'),
event('NR1H2',express,'NR1H2'),
event('NR1H2',express,'NR1H2'),
event('NR1H2',interact,'cholesterol'),
event('NR1H2',interact,'NR1H2'),
event('NR1H3',express,'NR1H3'),
event('NR1H2',express,'NR1H3'),
event('cholesterol',decrease,'NR1H2'),
event('NRBF2',activate,'NR1H2'),
event('NR1H2',mediate,'NR1H2'),
event('NR1H2',mediate,'NRBF2'),
event('NRBF2',mediate,'NRBF2'),
event('NRBF2',express,'bile acid'),
event('NRBF2',express,'cholesterol'),
event('NR1H3',require,'NR1H3'),
event('NR1H3',require,'NR1H2'),
event('NR1H2',require,'NR1H3'),
event('NR1H2',require,'NR1H2'),
event('NR1H2',target,'NRBF2'),
event('NRBF2',target,'NR1H2'),
event('NRBF2',bind,'NR1H2'),
event('NR1H2',decrease,'cholesterol'),
event('NR1H3',suppress,'oxysterols'),
event('NR1H3',suppress,'NR1H3'),
event('NR1H3',suppress,'NR1H2'),
event('NR1H2',suppress,'oxysterols'),
event('NR1H2',suppress,'NR1H3'),
event('NR1H2',suppress,'NR1H2'),
event('NR1H2',regulate,'NRBF2'),
event('NR1H3',regulate,'NRBF2'),
event('NR1H2',regulate,'NRBF2'),
event('NR1H2',inhibit,'cholesterol'),
event('NR1H2',bind,'cholesterol'),
event('NRBF2',bind,'cholesterol'),
event('cholesterol',bind,'NR1H2'),
event('cholesterol',bind,'NRBF2'),
event('oxysterols',bind,'NR1H2'),
event('oxysterols',bind,'NR1H2'),
event('oxysterols',bind,'NRBF2'),
event('NRBF2',interact,'cholesterol'),
event('NR1H2',associate,'NR1H2'),
event('NRBF2',associate,'NR1H2'),
event('oxysterols',target,'cholesterol'),
event('oxysterols',target,'NR1H2'),
event('oxysterols',target,'NRBF2'),
event('NR1H3',regulate,'cholesterol'),
event('NR1H3',regulate,'oxysterols'),
event('NR1H2',regulate,'oxysterols'),
event('NR1H2',prevent,'NR1H2'),
event('cholesterol',mediate,'NR1H2'),
event('NR1H2',repress,'NR1H2'),
event('NRBF2',decrease,'NR1H2'),
event('NR1H2',target,'NPC1'),
event('NRBF2',enhance,'NRBF2'),
event('cholesterol',increase,'CAP'),
event('NR1H2',participate,'NR1H2'),
event('NR1H2',inhibit,'bile acid'),
event('bile acid',induce,'NR1H4'),
event('RUNX1',regulate,'RUNX1'),
event('bile acid',regulate,'NR1H2'),
event('NR1H2',regulate,'cholesterol'),
event('NR1H2',dimerize,'cholesterol'),
event('NR1H4',dimerize,'cholesterol'),
event('NR1H2',prevent,'bile acid'),
event('NR1H2',prevent,'NR1H4'),
event('oxysterols',regulate,'cholesterol'),
event('bile acid',decrease,'CYP7A1'),
event('cholesterol',decrease,'CYP7A1'),
event('NR1H2',activate,'NR1H4'),
event('FOXA2',decrease,'FOXA2'),
event('FOXA2',inhibit,'oxysterols'),
event('FOXA2',inhibit,'NR1H2'),
event('FOXA2',inhibit,'NRBF2'),
event('oxysterols',involve,'bile acid'),
event('oxysterols',involve,'cholesterol'),
event('NR1H2',involve,'cholesterol'),
event('bile acid',increase,'cholesterol'),
event('bile acid',synthesize,'cholesterol'),
event('bile acid',synthesize,'NR1H3'),
event('bile acid',synthesize,'NR1H2'),
event('cholesterol',promote,'bile acid'),
event('cholesterol',promote,'NR1H2'),
event('oxysterols',modulate,'cholesterol'),
event('FOXA2',mediate,'FOXA2'),
event('FOXA2',enhance,'FOXA2'),
event('bile acid',associate,'NR1H4'),
event('bile acid',associate,'NR0B2'),
event('FOXA2',associate,'FOXA2'),
event('FOXA2',express,'FOXA2'),
event('NR0B2',suppress,'NR0B2'),
event('FOXA2',increase,'FOXA2'),
event('bile acid',activate,'NR1H2'),
event('NR1H3',regulate,'NR1H4'),
event('NRBF2',regulate,'NRBF2'),
event('cholesterol',associate,'bile acid'),
event('NR1H4',activate,'cholesterol'),
event('cholesterol',synthesize,'cholesterol'),
event('cholesterol',increase,'CYP7A1'),
event('cholesterol',mediate,'CYP7A1'),
event('cholesterol',associate,'CYP7A1'),
event('cholesterol',enhance,'CYP7A1'),
event('NR1H4',induce,'cholesterol'),
event('NR1H4',repress,'NR1H4'),
event('CYP7A1',associate,'cholesterol'),
event('cholesterol',induce,'CYP7A1'),
event('cholesterol',suppress,'CYP7A1'),
event('cholesterol',bind,'NR1H3'),
event('CYP7A1',induce,'NR1H2'),
event('NR1H2',inhibit,'CYP7A1'),
event('CYP7A1',promote,'CYP7A1'),
event('CYP7A1',promote,'NR1H2'),
event('NR1H4',express,'cholesterol'),
event('NR1H2',trigger,'NR1H2'),
event('NR1H2',trigger,'NR1H2'),
event('NR1H4',associate,'bile acid'),
event('NR1H4',stimulate,'NR1H4'),
event('NR1H2',bind,'NRBF2'),
event('cholesterol',bind,'NR1H4'),
event('NR1H2',bind,'NR1H4'),
event('bile acid',involve,'cholesterol'),
event('NR1H4',suppress,'NR1H3'),
event('NR1H4',suppress,'NR1H2'),
event('NR1H4',bind,'NR1H3'),
event('NR1H4',bind,'NR1H2'),
event('NR1H4',associate,'NR1H4'),
event('NR1H4',target,'CYP7A1'),
event('NR1H4',target,'cholesterol'),
event('NPC1',bind,'NR1H4'),
event('NPC1L1',bind,'NR1H4'),
event('NR1H4',mediate,'NR1H4'),
event('cholesterol',mediate,'NPC1'),
event('cholesterol',mediate,'NPC1L1'),
event('bile acid',induce,'cholesterol'),
event('cholesterol',induce,'bile acid'),
event('NR1H4',suppress,'NPC1'),
event('NR1H4',suppress,'NPC1L1'),
event('cholesterol',inhibit,'NPC1'),
event('cholesterol',inhibit,'NPC1L1'),
event('CYP7A1',stimulate,'CYP7A1'),
event('NR1H4',stimulate,'CYP7A1'),
event('cholesterol',interact,'cholesterol'),
event('LCAT',associate,'cholesterol'),
event('LCAT',involve,'cholesterol'),
event('cholesterol',associate,'LCAT'),
event('LCAT',stimulate,'cholesterol'),
event('LCAT',promote,'cholesterol'),
event('cholesterol',induce,'LCAT'),
event('cholesterol',decrease,'LCAT'),
event('NR1H4',lead,'NR1H4'),
event('NR1H4',modulate,'bile acid'),
event('bile acid',decrease,'NR1H4'),
event('NR0B2',inhibit,'bile acid'),
event('NR1H4',recruit,'CYP7A1'),
event('NR1H4',recruit,'NR0B2'),
event('NR1H4',induce,'CYP7A1'),
event('NR0B2',increase,'cholesterol'),
event('CYP7A1',inhibit,'NR0B2'),
event('bile acid',repress,'NR1H4'),
event('NR0B2',repress,'cholesterol'),
event('NR0B2',repress,'NR1H4'),
event('NR1H4',increase,'bile acid'),
event('CYP7A1',activate,'NR1H4'),
event('CYP7A1',activate,'NR0B2'),
event('FOXA2',recognize,'FOXA2'),
event('NR1H3',regulate,'CYP7A1'),
event('NR1H3',decrease,'CYP7A1'),
event('NR1H3',decrease,'cholesterol'),
event('NR1H2',decrease,'CYP7A1'),
event('cholesterol',inhibit,'CYP7A1'),
event('cholesterol',inhibit,'NR1H3'),
event('CYP7A1',bind,'cholesterol'),
event('NR1H2',enhance,'FOXA2'),
event('SRY',regulate,'SRY'),
event('SRY',bind,'SRY'),
event('SRY',associate,'SRY'),
event('SRY',express,'SRY'),
event('NR5A2',enhance,'NR5A2'),
event('NR5A2',regulate,'cholesterol'),
event('NR5A2',regulate,'cholesterol'),
event('NPC1',regulate,'NR5A2'),
event('NPC1',regulate,'NR5A2'),
event('NPC1L1',regulate,'NR5A2'),
event('NPC1L1',regulate,'NR5A2'),
event('SRY',lead,'SRY'),
event('NR5A2',associate,'NR5A2'),
event('NR5A2',associate,'NR5A2'),
event('NR5A2',associate,'NR5A2'),
event('NR5A2',associate,'NR5A2'),
event('NRBF2',activate,'CYP7A1'),
event('NRBF2',activate,'oxysterols'),
event('CYP7A1',stimulate,'NRBF2'),
event('cholesterol',repress,'bile acid'),
event('bile acid',mediate,'CYP7A1'),
event('bile acid',mediate,'cholesterol'),
event('NR1H2',mediate,'CYP7A1'),
event('NR1H2',mediate,'bile acid'),
event('NR1H2',mediate,'cholesterol'),
event('NRBF2',mediate,'CYP7A1'),
event('NRBF2',mediate,'bile acid'),
event('NRBF2',mediate,'cholesterol'),
event('NR1H4',mediate,'CYP7A1'),
event('NR1H4',mediate,'bile acid'),
event('NR1H4',mediate,'cholesterol'),
event('bile acid',regulate,'NR1H3'),
event('NRBF2',stimulate,'CYP7A1'),
event('CYP7A1',bind,'CYP7A1'),
event('bile acid',enhance,'cholesterol'),
event('CYP7A1',associate,'NR1H2'),
event('CYP7A1',associate,'NR1H4'),
event('bile acid',associate,'cholesterol'),
event('NR1H4',modulate,'CYP7A1'),
event('NR1H4',modulate,'NR1H4'),
event('bile acid',promote,'bile acid'),
event('bile acid',promote,'NR1H4'),
event('NR5A2',involve,'NR0B2'),
event('NR5A2',stimulate,'NR0B2'),
event('NR5A2',stimulate,'NR0B2'),
event('NR5A2',bind,'NR0B2'),
event('NR5A2',bind,'NR0B2'),
event('NR0B2',interact,'cholesterol'),
event('NR0B2',enhance,'NR5A2'),
event('SRY',decrease,'cholesterol'),
event('SRY',suppress,'cholesterol'),
event('oxysterols',increase,'cholesterol'),
event('oxysterols',modulate,'NR1H2'),
event('oxysterols',bind,'NR1H3'),
event('NR1H3',bind,'NR1H3'),
event('NR1H2',involve,'bile acid'),
event('bile acid',involve,'CYP7A1'),
event('CYP7A1',repress,'bile acid'),
event('NR0B2',associate,'CYP7A1'),
event('NR0B2',associate,'bile acid'),
event('CYP7A1',target,'bile acid'),
event('CYP7A1',target,'cholesterol'),
event('cholesterol',promote,'NPC1'),
event('cholesterol',promote,'NPC1L1'),
event('cholesterol',bind,'NPC1L1'),
event('cholesterol',target,'bile acid'),
event('cholesterol',enhance,'NPC1'),
event('NPC2',increase,'bile acid'),
event('NPC2',increase,'NPC1'),
event('cholesterol',suppress,'NPC1'),
event('cholesterol',suppress,'NPC1L1'),
event('NPC1',associate,'NPC1L1'),
event('NPC1L1',associate,'NPC1'),
event('NPC1L1',associate,'NPC1L1'),
event('cholesterol',decrease,'BAAT'),
event('BAAT',increase,'BAAT'),
event('BAAT',prevent,'BAAT'),
event('NPC1L1',regulate,'cholesterol'),
event('LCAT',express,'BAAT'),
event('bile acid',express,'bile acid'),
event('cholesterol',activate,'LCAT'),
event('LCAT',increase,'bile acid'),
event('NCEH1',increase,'cholesterol'),
event('BAAT',induce,'BAAT'),
event('NR0B2',target,'NR0B2'),
event('NR0B2',associate,'NPC2'),
event('NCEH1',express,'cholesterol'),
event('BAAT',associate,'BAAT'),
event('BAAT',involve,'BAAT'),
event('NPC1',enhance,'NPC1'),
event('NPC1',enhance,'NPC2'),
event('NPC1',enhance,'cholesterol'),
event('NPC1',induce,'NPC1'),
event('bile acid',synthesize,'CYP7A1'),
event('bile acid',synthesize,'NR0B2'),
event('NPC1',mediate,'NPC1'),
event('NPC1',bind,'oxysterols'),
event('NPC1',activate,'cholesterol'),
event('NPC1',decrease,'cholesterol'),
event('NPC1L1',decrease,'cholesterol'),
event('NPC1',stimulate,'cholesterol'),
event('NPC1L1',stimulate,'cholesterol'),
event('cholesterol',increase,'NPC1L1'),
event('NPC2',bind,'oxysterols'),
event('cholesterol',bind,'NPC2'),
event('cholesterol',increase,'oxysterols'),
event('CH25H',trigger,'CH25H'),
event('CH25H',induce,'CH25H'),
event('oxysterols',synthesize,'CH25H'),
event('cholesterol',bind,'CH25H'),
event('NR1H2',decrease,'cholesterol'),
event('NR1H2',enhance,'NR1H2'),
event('cholesterol',associate,'NR1H2')
]).
