base([
event('LXR',bind,'CYP7A1'),
event('LRH',activate,'CYP7A1'),
event('GATA',increase,'CYP7A1'),
event('GATA1',increase,'CYP7A1'),
event('SHP',inhibit,'CYP7A1'),
event('cyp3a5',bind,'ABCB1'),
event('SHP',bind,'VDR'),
event('VDR',bind,'SHP'),
event('VDR',repress,'CYP7A1'),
event('VDR',repress,'SHP'),
event('FXR',increase,'FXR'),
event('FXR',increase,'FXR'),
event('CYP24',increase,'VDR'),
event('VDR',increase,'CYP24'),
event('GATA',decrease,'CYP1A1'),
event('GATA',decrease,'GATA1'),
event('GATA1',decrease,'CYP1A1'),
event('GATA1',decrease,'GATA'),
event('RBM6',target,'vitamin D analog'),
event('QDPR',increase,'progesterone analog'),
event('progesterone analog',increase,'QDPR'),
event('QDPR',involve,'TST1'),
event('progesterone analog',involve,'TST1'),
event('CYP7A1',associate,'PPAR'),
event('CYP7A1',associate,'PPARA'),
event('vitamin D analog',associate,'PPAR'),
event('vitamin D analog',associate,'PPARA'),
event('FXR',induce,'SHP'),
event('FXR',induce,'SHP'),
event('polycyclic aromatic hydrocarbon',increase,'AHR'),
event('AHR',increase,'polycyclic aromatic hydrocarbon'),
event('QDPR',induce,'progesterone analog'),
event('progesterone analog',induce,'QDPR'),
event('PPAR',bind,'PPARA'),
event('PPARA',bind,'PPAR'),
event('AKR1C4',increase,'CYP7A1'),
event('ABCG8',increase,'CYP7A1'),
event('SHP',repress,'CYP7A1'),
event('vitamin D analog',mediate,'NR3C1'),
event('RU486',mediate,'NR3C1'),
event('cyp3a4',mediate,'NR1I2'),
event('CYP7A1',increase,'SHP'),
event('NR1I2',increase,'SHP'),
event('cyp3a4',increase,'SHP'),
event('SHP',bind,'LRH'),
event('SHP',increase,'progesterone analog'),
event('progesterone analog',decrease,'SHP'),
event('CYP7A1',repress,'SHP'),
event('SHP',recruit,'TST1'),
event('FXR',inhibit,'CYP7A1'),
event('FXR',inhibit,'SHP'),
event('FXR',inhibit,'CYP7A1'),
event('FXR',inhibit,'SHP'),
event('FXR',recruit,'CYP7A1'),
event('FXR',recruit,'SHP'),
event('FXR',recruit,'CYP7A1'),
event('FXR',recruit,'SHP'),
event('WY-14',enhance,'RXR'),
event('WY-14',enhance,'RXRa'),
event('RXR',enhance,'RXRa'),
event('RXRa',enhance,'RXR'),
event('RXR',regulate,'WY-14'),
event('RXRa',regulate,'WY-14'),
event('bile acid',increase,'RXR'),
event('bile acid',increase,'RXRa'),
event('Lithocholic acid',increase,'RXR'),
event('Lithocholic acid',increase,'RXRa'),
event('chenodeoxycholic acid',increase,'RXR'),
event('chenodeoxycholic acid',increase,'RXRa'),
event('CYP7A1',associate,'ABCC1'),
event('CYP7A1',associate,'ABCC2'),
event('bile acid',associate,'ABCC1'),
event('bile acid',associate,'ABCC2'),
event('Lithocholic acid',associate,'ABCC1'),
event('Lithocholic acid',associate,'ABCC2'),
event('chenodeoxycholic acid',associate,'ABCC1'),
event('chenodeoxycholic acid',associate,'ABCC2'),
event('RXR',associate,'ABCC1'),
event('RXR',associate,'ABCC2'),
event('RXR',increase,'bile acid'),
event('RXR',increase,'Lithocholic acid'),
event('RXR',increase,'chenodeoxycholic acid'),
event('bile acid',enhance,'RXR'),
event('Lithocholic acid',enhance,'RXR'),
event('chenodeoxycholic acid',enhance,'RXR'),
event('vitamin D analog',induce,'GW4064'),
event('vitamin D analog',induce,'FXR'),
event('vitamin D analog',induce,'SHP'),
event('vitamin D analog',induce,'FXR'),
event('vitamin D analog',inhibit,'FXR'),
event('vitamin D analog',inhibit,'FXR'),
event('RXR',inhibit,'FXR'),
event('RXR',inhibit,'FXR'),
event('FXR',inhibit,'FXR'),
event('FXR',inhibit,'FXR'),
event('vitamin D analog',activate,'FXR'),
event('vitamin D analog',activate,'FXR'),
event('fibrate',increase,'PPAR'),
event('fibrate',increase,'PPARA'),
event('fibrate',increase,'SLC10A2'),
event('RXR',bind,'bile acid'),
event('RXR',bind,'Lithocholic acid'),
event('RXR',bind,'chenodeoxycholic acid'),
event('RXR',bind,'FXR'),
event('RXR',bind,'FXR'),
event('bile acid',decrease,'Lithocholic acid'),
event('bile acid',decrease,'chenodeoxycholic acid'),
event('bile acid',decrease,'RXR'),
event('Lithocholic acid',decrease,'bile acid'),
event('Lithocholic acid',decrease,'chenodeoxycholic acid'),
event('Lithocholic acid',decrease,'RXR'),
event('chenodeoxycholic acid',decrease,'bile acid'),
event('chenodeoxycholic acid',decrease,'Lithocholic acid'),
event('chenodeoxycholic acid',decrease,'RXR'),
event('fibrate',increase,'bile acid'),
event('fibrate',increase,'Lithocholic acid'),
event('fibrate',increase,'chenodeoxycholic acid'),
event('fibrate',regulate,'bile acid'),
event('fibrate',regulate,'Lithocholic acid'),
event('fibrate',regulate,'chenodeoxycholic acid'),
event('bile acid',involve,'Lithocholic acid'),
event('bile acid',involve,'chenodeoxycholic acid'),
event('Lithocholic acid',involve,'bile acid'),
event('Lithocholic acid',involve,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',involve,'bile acid'),
event('chenodeoxycholic acid',involve,'Lithocholic acid'),
event('FXR',bind,'FXR'),
event('FXR',bind,'FXR'),
event('GW4064',target,'SHP'),
event('GW4064',target,'ABCB11'),
event('RXR',target,'SHP'),
event('RXR',target,'ABCB11'),
event('FXR',target,'SHP'),
event('FXR',target,'ABCB11'),
event('FXR',target,'SHP'),
event('FXR',target,'ABCB11'),
event('GATA',increase,'SHP'),
event('GATA1',increase,'SHP'),
event('bile acid',enhance,'Lithocholic acid'),
event('bile acid',enhance,'chenodeoxycholic acid'),
event('bile acid',enhance,'vitamin D analog'),
event('Lithocholic acid',enhance,'bile acid'),
event('Lithocholic acid',enhance,'chenodeoxycholic acid'),
event('Lithocholic acid',enhance,'vitamin D analog'),
event('chenodeoxycholic acid',enhance,'bile acid'),
event('chenodeoxycholic acid',enhance,'Lithocholic acid'),
event('chenodeoxycholic acid',enhance,'vitamin D analog'),
event('oxysterol',bind,'LXR'),
event('oxysterol',bind,'LXRa'),
event('LXR',bind,'LXRa'),
event('LXRa',bind,'LXR'),
event('CYP7A1',stimulate,'oxysterol'),
event('CYP7A1',stimulate,'LXR'),
event('CYP7A1',stimulate,'LXRa'),
event('SHP',regulate,'LXR'),
event('SHP',regulate,'LXRa'),
event('FXR',regulate,'CYP7A1'),
event('FXR',regulate,'SHP'),
event('LXR',regulate,'CYP7A1'),
event('LXR',regulate,'SHP'),
event('FXR',regulate,'CYP7A1'),
event('FXR',regulate,'SHP'),
event('CYP7A1',decrease,'NR3C1'),
event('oxysterol',decrease,'NR3C1'),
event('LXR',inhibit,'CYP7A1'),
event('RXR',stimulate,'CYP7A1'),
event('RXR',stimulate,'oxysterol'),
event('RXRa',stimulate,'CYP7A1'),
event('RXRa',stimulate,'oxysterol'),
event('LXR',stimulate,'CYP7A1'),
event('LXR',stimulate,'oxysterol'),
event('LXRa',stimulate,'CYP7A1'),
event('LXRa',stimulate,'oxysterol'),
event('CYP7A1',bind,'RXR'),
event('CYP7A1',bind,'RXRa'),
event('CYP7A1',bind,'LXR'),
event('CYP7A1',bind,'LXRa'),
event('oxysterol',bind,'CYP7A1'),
event('vitamin D analog',increase,'oxysterol'),
event('VDR',repress,'LXR'),
event('VDR',repress,'LXRa'),
event('VDR',activate,'LXR'),
event('VDR',activate,'LXRa'),
event('CYP7A1',regulate,'oxysterol'),
event('fibrate',increase,'oxysterol'),
event('fibrate',increase,'LXR'),
event('fibrate',increase,'LXRa'),
event('fibrate',enhance,'LXR'),
event('fibrate',enhance,'LXRa'),
event('fibrate',enhance,'PPAR'),
event('fibrate',enhance,'PPARA'),
event('fibrate',enhance,'abca1'),
event('fibrate',increase,'abca1'),
event('abca1',regulate,'LXR'),
event('T0901317',inhibit,'LXR'),
event('abca1',inhibit,'LXR'),
event('LXR',recruit,'CYP1A1'),
event('oxysterol',mediate,'abca1'),
event('LXR',mediate,'abca1'),
event('LXRa',enhance,'LXR'),
event('oxysterol',activate,'LXR'),
event('LXR',target,'CYP7A1'),
event('vitamin D analog',stimulate,'CYP7A1'),
event('vitamin D analog',stimulate,'ABCG5'),
event('vitamin D analog',stimulate,'ABCG8'),
event('GATA',suppress,'CYP7A1'),
event('GATA1',suppress,'CYP7A1'),
event('LXR',induce,'CYP7A1'),
event('SHP',target,'FXR'),
event('SHP',target,'LXR'),
event('SHP',target,'LXRa'),
event('SHP',target,'abca1'),
event('SHP',target,'FXR'),
event('ABCB11',target,'FXR'),
event('ABCB11',target,'LXR'),
event('ABCB11',target,'LXRa'),
event('ABCB11',target,'abca1'),
event('ABCB11',target,'FXR'),
event('oxysterol',increase,'LXR'),
event('oxysterol',increase,'LXRa'),
event('oxysterol',increase,'abca1'),
event('LXR',increase,'LXRa'),
event('LXR',increase,'abca1'),
event('LXRa',increase,'LXR'),
event('LXRa',increase,'abca1'),
event('LXR',activate,'CYP7A1'),
event('LXR',activate,'FXR'),
event('LXR',activate,'FXR'),
event('LXRa',activate,'CYP7A1'),
event('LXRa',activate,'FXR'),
event('LXRa',activate,'FXR'),
event('CYP7A1',bind,'FXR'),
event('CYP7A1',bind,'SHP'),
event('CYP7A1',bind,'FXR'),
event('SHP',inactivate,'CYP7A1'),
event('SHP',inactivate,'LRH'),
event('FXR',target,'CYP7A1'),
event('FXR',target,'CYP7A1'),
event('LXR',increase,'CYP7A1'),
event('vitamin D analog',enhance,'RXR'),
event('vitamin D analog',recruit,'RXR'),
event('vitamin D analog',recruit,'RXRa'),
event('vitamin D analog',enhance,'RXRa'),
event('LXR',target,'abca1'),
event('LXR',promote,'PPAR'),
event('LXR',promote,'PPARA'),
event('LXR',target,'ABCG1'),
event('LXR',associate,'STAT'),
event('LXRa',decrease,'LXR'),
event('FXR',express,'LXRb'),
event('FXR',express,'LXRb'),
event('FXR',bind,'RXR'),
event('FXR',bind,'RAR'),
event('FXR',bind,'RARA'),
event('FXR',bind,'RXR'),
event('FXR',bind,'RAR'),
event('FXR',bind,'RARA'),
event('LXR',regulate,'LXRb'),
event('Glucocorticoid',regulate,'NR3C1'),
event('LXR',regulate,'abca1'),
event('NR1I2',increase,'LXR'),
event('NR1I2',increase,'cyp3a4'),
event('LXR',regulate,'NR1I2'),
event('LXR',regulate,'cyp3a4'),
event('PPAR',increase,'abca1'),
event('PPARA',increase,'abca1'),
event('fibrate',bind,'PPAR'),
event('fibrate',bind,'PPARA'),
event('LXR',target,'FXR'),
event('LXR',target,'FXR'),
event('GW3965',recruit,'LXR'),
event('GW3965',recruit,'LXRb'),
event('GW3965',recruit,'LXRa'),
event('LXR',regulate,'RXR'),
event('LXR',regulate,'RXRa'),
event('LXR',regulate,'RXRb'),
event('LXR',regulate,'RXRg'),
event('LXRb',regulate,'RXR'),
event('LXRb',regulate,'RXRa'),
event('LXRb',regulate,'RXRb'),
event('LXRb',regulate,'RXRg'),
event('LXRa',regulate,'RXR'),
event('LXRa',regulate,'RXRa'),
event('LXRa',regulate,'RXRb'),
event('LXRa',regulate,'RXRg'),
event('T0901317',activate,'FXR'),
event('T0901317',activate,'FXR'),
event('T0901317',activate,'TST1'),
event('LXR',activate,'TST1'),
event('LXRb',activate,'FXR'),
event('LXRb',activate,'FXR'),
event('LXRb',activate,'TST1'),
event('LXRa',activate,'TST1'),
event('FXR',activate,'FXR'),
event('FXR',activate,'FXR'),
event('FXR',regulate,'NR1I2'),
event('FXR',regulate,'NR1I2'),
event('oxysterol',involve,'LXR'),
event('FXR',regulate,'NR3C1'),
event('FXR',regulate,'NR3C1'),
event('LXR',bind,'FXR'),
event('LXR',bind,'FXR'),
event('GW3965',increase,'bile acid'),
event('GW3965',increase,'Lithocholic acid'),
event('GW3965',increase,'chenodeoxycholic acid'),
event('GW3965',increase,'LXR'),
event('T0901317',increase,'LXR'),
event('abca1',modulate,'LXR'),
event('abca1',modulate,'LXRb'),
event('abca1',modulate,'LXRa'),
event('ABCG1',modulate,'LXR'),
event('ABCG1',modulate,'LXRb'),
event('ABCG1',modulate,'LXRa'),
event('LXR',express,'LXRb'),
event('LXRa',express,'LXR'),
event('LXRa',express,'LXRb'),
event('PPAR',involve,'PPARA'),
event('PPAR',involve,'PPARB'),
event('PPARA',involve,'PPAR'),
event('PPARA',involve,'PPARB'),
event('PPARB',involve,'PPAR'),
event('PPARB',involve,'PPARA'),
event('LXRb',decrease,'simvastatin'),
event('paxilline',bind,'LXR'),
event('paxilline',bind,'abca1'),
event('oxysterol',target,'RXR'),
event('oxysterol',target,'LXR'),
event('LXR',target,'RXR'),
event('LXR',induce,'LXRa'),
event('LXR',regulate,'oxysterol'),
event('LXRa',regulate,'oxysterol'),
event('oxysterol',inhibit,'LXR'),
event('LXR',inhibit,'abca1'),
event('LXR',modulate,'LXRa'),
event('abca1',target,'ABCG1'),
event('oxysterol',enhance,'abca1'),
event('oxysterol',enhance,'ABCG1'),
event('GW3965',decrease,'LXR'),
event('oxysterol',involve,'abca1'),
event('oxysterol',regulate,'abca1'),
event('LXR',activate,'LXRb'),
event('LXR',activate,'LXRa'),
event('oxysterol',induce,'abca1'),
event('LXR',bind,'AKR1C4'),
event('LXRa',bind,'AKR1C4'),
event('LXR',modulate,'CYP7A1'),
event('LXRa',modulate,'CYP7A1'),
event('LXR',bind,'RXR'),
event('LXR',bind,'RXRa'),
event('LXR',bind,'PPAR'),
event('LXR',bind,'PPARA'),
event('LXRa',bind,'RXR'),
event('LXRa',bind,'RXRa'),
event('LXRa',bind,'PPAR'),
event('LXRa',bind,'PPARA'),
event('PPAR',bind,'RXR'),
event('PPAR',bind,'RXRa'),
event('PPAR',bind,'LXR'),
event('PPAR',bind,'LXRa'),
event('PPARA',bind,'RXR'),
event('PPARA',bind,'RXRa'),
event('PPARA',bind,'LXR'),
event('PPARA',bind,'LXRa'),
event('PPAR',target,'fatty acid'),
event('PPARA',target,'fatty acid'),
event('PPARG',target,'fatty acid'),
event('progesterone analog',decrease,'LXR'),
event('progesterone analog',decrease,'LXRa'),
event('progesterone analog',decrease,'ABCG5'),
event('progesterone analog',decrease,'ABCG8'),
event('progesterone analog',increase,'LXR'),
event('progesterone analog',increase,'LXRa'),
event('FXR',bind,'LXR'),
event('FXR',bind,'LXRa'),
event('FXR',bind,'LXR'),
event('FXR',bind,'LXRa'),
event('FXR',suppress,'LXR'),
event('FXR',suppress,'LXRa'),
event('FXR',suppress,'FXR'),
event('FXR',suppress,'FXR'),
event('FXR',suppress,'LXR'),
event('FXR',suppress,'LXRa'),
event('LXR',decrease,'GW3965'),
event('LXRa',decrease,'GW3965'),
event('FXR',express,'FXR'),
event('FXR',express,'FXR'),
event('LXR',regulate,'dehydroepiandrosterone'),
event('LXR',regulate,'sult2a1'),
event('LXRa',regulate,'dehydroepiandrosterone'),
event('LXRa',regulate,'sult2a1'),
event('LXR',induce,'dehydroepiandrosterone'),
event('LXR',induce,'sult2a1'),
event('dehydroepiandrosterone',bind,'sult2a1'),
event('LXR',bind,'dehydroepiandrosterone'),
event('LXR',bind,'sult2a1'),
event('sult2a1',bind,'dehydroepiandrosterone'),
event('LXR',increase,'ABCG1'),
event('LXRa',modulate,'LXR'),
event('LXR',involve,'LXRb'),
event('LXRa',involve,'LXR'),
event('LXRa',involve,'LXRb'),
event('GATA',induce,'FXR'),
event('GATA',induce,'FXR'),
event('GATA1',induce,'FXR'),
event('GATA1',induce,'FXR'),
event('GATA',inhibit,'CYP7A1'),
event('GATA',inhibit,'SHP'),
event('GATA1',inhibit,'CYP7A1'),
event('GATA1',inhibit,'SHP'),
event('SHP',bind,'GATA'),
event('SHP',bind,'GATA1'),
event('HNF4A      ',promote,'SHP'),
event('HNF4A      ',promote,'GATA'),
event('HNF4A      ',promote,'GATA1'),
event('LRH',promote,'SHP'),
event('LRH',promote,'GATA'),
event('LRH',promote,'GATA1'),
event('LRH',induce,'CYP7A1'),
event('vitamin D analog',induce,'CYP7A1'),
event('CYP7A1',mediate,'vitamin D analog'),
event('CYP7A1',mediate,'LRH'),
event('vitamin D analog',repress,'SHP'),
event('LRH',repress,'SHP'),
event('GW4064',induce,'CYP7A1'),
event('GW4064',induce,'vitamin D analog'),
event('GW4064',induce,'SHP'),
event('vitamin D analog',target,'CYP7A1'),
event('vitamin D analog',target,'LRH'),
event('LRH',target,'CYP7A1'),
event('LRH',target,'vitamin D analog'),
event('SHP',target,'CYP7A1'),
event('SHP',target,'vitamin D analog'),
event('SHP',target,'LRH'),
event('LRH',involve,'CYP7A1'),
event('LRH',involve,'FXR'),
event('LRH',involve,'FXR'),
event('LRH',require,'CYP7A1'),
event('LRH',involve,'ABCB11'),
event('LRH',require,'FXR'),
event('LRH',require,'ABCB11'),
event('LRH',require,'FXR'),
event('LRH',activate,'FXR'),
event('LRH',activate,'ABCB11'),
event('LRH',activate,'FXR'),
event('FXR',regulate,'ABCB11'),
event('LRH',regulate,'CYP7A1'),
event('LRH',regulate,'ABCB11'),
event('FXR',regulate,'ABCB11'),
event('RXR',repress,'CYP7A1'),
event('RXR',repress,'LRH'),
event('RXR',repress,'LXR'),
event('RXR',repress,'SHP'),
event('FXR',repress,'CYP7A1'),
event('FXR',repress,'RXR'),
event('FXR',repress,'LRH'),
event('FXR',repress,'LXR'),
event('FXR',repress,'SHP'),
event('FXR',repress,'CYP7A1'),
event('FXR',repress,'RXR'),
event('FXR',repress,'LRH'),
event('FXR',repress,'LXR'),
event('FXR',repress,'SHP'),
event('SHP',involve,'LRH'),
event('SHP',repress,'LRH'),
event('SHP',inhibit,'LRH'),
event('SHP',interact,'LRH'),
event('FXR',activate,'CYP7A1'),
event('FXR',activate,'LXR'),
event('FXR',activate,'LXRa'),
event('FXR',activate,'CYP7A1'),
event('FXR',activate,'LXR'),
event('FXR',activate,'LXRa'),
event('LRH',bind,'LXR'),
event('LRH',bind,'LXRa'),
event('SHP',enhance,'LRH'),
event('LRH',bind,'CYP7A1'),
event('LXRa',bind,'CYP7A1'),
event('SHP',bind,'CYP7A1'),
event('SHP',bind,'LXR'),
event('SHP',bind,'LXRa'),
event('CYP7A1',increase,'LRH'),
event('CYP7A1',increase,'LXR'),
event('CYP7A1',increase,'LXRa'),
event('FXR',increase,'CYP7A1'),
event('FXR',increase,'LRH'),
event('FXR',increase,'LXR'),
event('FXR',increase,'LXRa'),
event('FXR',increase,'SHP'),
event('LXR',increase,'LRH'),
event('LXR',increase,'SHP'),
event('LXRa',increase,'CYP7A1'),
event('LXRa',increase,'LRH'),
event('LXRa',increase,'SHP'),
event('SHP',increase,'CYP7A1'),
event('SHP',increase,'LRH'),
event('SHP',increase,'LXR'),
event('SHP',increase,'LXRa'),
event('FXR',increase,'CYP7A1'),
event('FXR',increase,'LRH'),
event('FXR',increase,'LXR'),
event('FXR',increase,'LXRa'),
event('FXR',increase,'SHP'),
event('CYP7A1',bind,'LRH'),
event('LRH',enhance,'SHP'),
event('LRH',enhance,'CYP7A1'),
event('SHP',involve,'FXR'),
event('SHP',involve,'FXR'),
event('LRH',activate,'SHP'),
event('LRH',activate,'RXR'),
event('LRH',activate,'LXR'),
event('FXR',require,'CYP7A1'),
event('FXR',require,'FXR'),
event('FXR',require,'CYP7A1'),
event('FXR',require,'FXR'),
event('LRH',repress,'CYP7A1'),
event('FXR',stimulate,'LRH'),
event('FXR',stimulate,'SHP'),
event('FXR',stimulate,'LRH'),
event('FXR',stimulate,'SHP'),
event('LRH',induce,'FXR'),
event('LRH',induce,'SHP'),
event('LRH',induce,'FXR'),
event('CYP7A1',regulate,'SHP'),
event('LRH',increase,'SHP'),
event('SHP',involve,'CYP7A1'),
event('FXR',suppress,'CYP7A1'),
event('FXR',suppress,'HNF4A      '),
event('FXR',suppress,'LRH'),
event('SHP',suppress,'CYP7A1'),
event('SHP',suppress,'HNF4A      '),
event('SHP',suppress,'LRH'),
event('FXR',suppress,'CYP7A1'),
event('FXR',suppress,'HNF4A      '),
event('FXR',suppress,'LRH'),
event('LRH',target,'CYP24'),
event('LRH',target,'STAT'),
event('progesterone analog',bind,'NR3C1'),
event('progesterone analog',bind,'LRH'),
event('progesterone analog',bind,'CEBPB'),
event('progesterone analog',bind,'enhancer-binding protein beta'),
event('vitamin D analog',bind,'NR3C1'),
event('vitamin D analog',bind,'LRH'),
event('vitamin D analog',bind,'CEBPB'),
event('vitamin D analog',bind,'enhancer-binding protein beta'),
event('androstane',bind,'NR3C1'),
event('androstane',bind,'LRH'),
event('androstane',bind,'CEBPB'),
event('androstane',bind,'enhancer-binding protein beta'),
event('NR3C1',bind,'LRH'),
event('NR3C1',bind,'CEBPB'),
event('NR3C1',bind,'enhancer-binding protein beta'),
event('NR1I3',bind,'NR3C1'),
event('NR1I3',bind,'LRH'),
event('NR1I3',bind,'CEBPB'),
event('NR1I3',bind,'enhancer-binding protein beta'),
event('CYP1A1',bind,'NR3C1'),
event('CYP1A1',bind,'LRH'),
event('CYP1A1',bind,'CEBPB'),
event('CYP1A1',bind,'enhancer-binding protein beta'),
event('abca1',bind,'NR3C1'),
event('abca1',bind,'LRH'),
event('abca1',bind,'CEBPB'),
event('abca1',bind,'enhancer-binding protein beta'),
event('ABCG1',bind,'NR3C1'),
event('ABCG1',bind,'LRH'),
event('ABCG1',bind,'CEBPB'),
event('ABCG1',bind,'enhancer-binding protein beta'),
event('LRH',involve,'SHP'),
event('RXR',regulate,'LXR'),
event('SLC10A2',associate,'LRH'),
event('SLC10A2',mediate,'LRH'),
event('LRH',decrease,'GW4064'),
event('FXR',activate,'RXR'),
event('FXR',activate,'RXR'),
event('LRH',increase,'RXR'),
event('LRH',increase,'FXR'),
event('LRH',increase,'FXR'),
event('FXR',mediate,'LRH'),
event('SHP',mediate,'LRH'),
event('FXR',mediate,'LRH'),
event('vitamin K2',recruit,'LRH'),
event('vitamin K2',recruit,'SHP'),
event('progesterone analog',recruit,'LRH'),
event('progesterone analog',recruit,'SHP'),
event('vitamin D analog',recruit,'LRH'),
event('vitamin D analog',recruit,'SHP'),
event('vitamin K2',enhance,'progesterone analog'),
event('vitamin K2',enhance,'vitamin D analog'),
event('vitamin K2',enhance,'SHP'),
event('vitamin K2',lead,'vitamin D analog'),
event('vitamin K2',lead,'SHP'),
event('vitamin K2',promote,'LRH'),
event('progesterone analog',promote,'LRH'),
event('vitamin D analog',promote,'LRH'),
event('LRH',regulate,'SHP'),
event('LRH',activate,'SLC10A2'),
event('LRH',involve,'SLC10A2'),
event('SLC10A2',associate,'FXR'),
event('SLC10A2',associate,'SHP'),
event('SLC10A2',associate,'FXR'),
event('LRH',stimulate,'SLC10A2'),
event('SHP',inhibit,'SLC10A2'),
event('FXR',repress,'SLC10A2'),
event('FXR',repress,'SLC10A2'),
event('SLC10A2',regulate,'LRH'),
event('ABCC1',increase,'ABCC3'),
event('ABCC3',increase,'ABCC1'),
event('ABCC1',increase,'LRH'),
event('ABCC3',increase,'LRH'),
event('LRH',enhance,'ABCC1'),
event('LRH',enhance,'ABCC3'),
event('LRH',decrease,'HNF4A      '),
event('LRH',decrease,'GATA'),
event('progesterone analog',trigger,'LXR'),
event('progesterone analog',trigger,'LXRb'),
event('LXR',trigger,'LXRb'),
event('GW3965',enhance,'abca1'),
event('RXR',involve,'abca1'),
event('LXR',involve,'abca1'),
event('LRH',increase,'guggulsterone'),
event('SHP',increase,'guggulsterone'),
event('abca1',increase,'guggulsterone'),
event('abca1',increase,'LRH'),
event('abca1',increase,'SHP'),
event('guggulsterone',enhance,'LRH'),
event('guggulsterone',enhance,'SHP'),
event('LXR',induce,'FXR'),
event('LXR',induce,'FXR'),
event('LRH',target,'SHP'),
event('LXR',target,'SHP'),
event('CYP7A1',associate,'FXR'),
event('CYP7A1',associate,'LXR'),
event('CYP7A1',associate,'FXR'),
event('CYP7A1',repress,'RXR'),
event('CYP7A1',repress,'FXR'),
event('CYP7A1',repress,'FXR'),
event('CYP7A1',repress,'GATA'),
event('CYP7A1',repress,'GATA1'),
event('RXR',increase,'CYP7A1'),
event('RXR',increase,'FXR'),
event('RXR',increase,'FXR'),
event('RXRa',increase,'CYP7A1'),
event('RXRa',increase,'RXR'),
event('RXRa',increase,'FXR'),
event('RXRa',increase,'FXR'),
event('FXR',increase,'RXR'),
event('FXR',increase,'RXR'),
event('RXR',activate,'CYP7A1'),
event('RXR',activate,'oxysterol'),
event('LXR',activate,'oxysterol'),
event('LXRa',activate,'oxysterol'),
event('CYP7A1',stimulate,'RXR'),
event('CYP7A1',decrease,'PPAR'),
event('CYP7A1',decrease,'PPARA'),
event('HNF4A      ',increase,'PPAR'),
event('HNF4A      ',increase,'PPARA'),
event('oxysterol',mediate,'CYP7A1'),
event('RXR',mediate,'CYP7A1'),
event('RXR',mediate,'abca1'),
event('FXR',mediate,'CYP7A1'),
event('FXR',mediate,'abca1'),
event('LXR',mediate,'CYP7A1'),
event('FXR',mediate,'CYP7A1'),
event('FXR',mediate,'abca1'),
event('cyp2c19',bind,'RXR'),
event('cyp2c19',bind,'RAR'),
event('cyp2c19',bind,'RARA'),
event('SHP',inhibit,'polycyclic aromatic hydrocarbon'),
event('SHP',inhibit,'AHR'),
event('SHP',inhibit,'CYP1A1'),
event('SHP',inhibit,'ugt1a1'),
event('SHP',inhibit,'ugt1a6'),
event('ARNT',interact,'polycyclic aromatic hydrocarbon'),
event('ARNT',interact,'AHR'),
event('ARNT',interact,'SHP'),
event('SHP',inhibit,'ARNT'),
event('RXR',enhance,'ABCB11'),
event('FXR',enhance,'ABCB11'),
event('FXR',enhance,'ABCB11'),
event('FXR',target,'FXR'),
event('FXR',target,'FXR'),
event('GW4064',induce,'GATA'),
event('GW4064',induce,'GATA1'),
event('FXR',induce,'CYP7A1'),
event('FXR',induce,'GATA'),
event('FXR',induce,'GATA1'),
event('FXR',induce,'CYP7A1'),
event('FXR',induce,'GATA'),
event('FXR',induce,'GATA1'),
event('GATA',repress,'CYP7A1'),
event('GATA',repress,'SHP'),
event('GATA1',repress,'CYP7A1'),
event('GATA1',repress,'SHP'),
event('GW4064',increase,'CYP7A1'),
event('SHP',associate,'CYP7A1'),
event('NR1I2',involve,'CYP7A1'),
event('vitamin D analog',enhance,'NR1I2'),
event('vitamin D analog',bind,'NR1I2'),
event('NR1I2',target,'vitamin D analog'),
event('NR1I2',target,'dehydroepiandrosterone'),
event('NR1I2',target,'sult2a1'),
event('cyp3a4',target,'dehydroepiandrosterone'),
event('cyp3a4',target,'sult2a1'),
event('HNF4A      ',bind,'dehydroepiandrosterone'),
event('HNF4A      ',bind,'sult2a1'),
event('NR1I2',suppress,'dehydroepiandrosterone'),
event('NR1I2',suppress,'HNF4A      '),
event('NR1I2',suppress,'sult2a1'),
event('dehydroepiandrosterone',suppress,'HNF4A      '),
event('dehydroepiandrosterone',suppress,'sult2a1'),
event('HNF4A      ',suppress,'dehydroepiandrosterone'),
event('HNF4A      ',suppress,'sult2a1'),
event('sult2a1',suppress,'dehydroepiandrosterone'),
event('sult2a1',suppress,'HNF4A      '),
event('dehydroepiandrosterone',mediate,'NR1I2'),
event('sult2a1',mediate,'NR1I2'),
event('GATA',express,'CYP7A1'),
event('GATA1',express,'CYP7A1'),
event('NR1I2',regulate,'cyp3a4'),
event('cyp3a4',regulate,'NR1I2'),
event('HNF3B',bind,'GATA'),
event('progesterone analog',regulate,'STAT'),
event('progesterone analog',decrease,'STAT'),
event('progesterone analog',lead,'STAT'),
event('STAT',bind,'vitamin D analog'),
event('NID1',interact,'RAR'),
event('NID1',interact,'RARA'),
event('NID1',interact,'RXR'),
event('PPAR',enhance,'RXR'),
event('PPAR',enhance,'PPARA'),
event('PPARA',enhance,'RXR'),
event('PPARA',enhance,'PPAR'),
event('RXR',associate,'VDR'),
event('TST1',bind,'RXR'),
event('Phenobarbital',regulate,'androstane'),
event('Phenobarbital',regulate,'NR1I3'),
event('Phenobarbital',regulate,'NR1I2'),
event('cyp2b6',regulate,'androstane'),
event('cyp2b6',regulate,'NR1I3'),
event('cyp2b6',regulate,'NR1I2'),
event('Phenobarbital',mediate,'cyp3a4'),
event('cyp2b6',mediate,'cyp3a4'),
event('progesterone analog',target,'RXR'),
event('progesterone analog',target,'RXRa'),
event('progesterone analog',target,'RAR'),
event('progesterone analog',target,'RARA'),
event('progesterone analog',target,'PPAR'),
event('progesterone analog',target,'PPARA'),
event('transcription factor Oct-1',require,'RXR'),
event('transcription factor Oct-1',require,'RAR'),
event('transcription factor Oct-1',require,'RARA'),
event('RXR',activate,'FXR'),
event('RXR',activate,'LXR'),
event('RXR',activate,'RAR'),
event('RXR',activate,'RARA'),
event('RXR',activate,'PPAR'),
event('RXR',activate,'PPARA'),
event('RXR',activate,'VDR'),
event('RXR',activate,'FXR'),
event('GATA',bind,'GATA1'),
event('GATA1',bind,'GATA'),
event('polycyclic aromatic hydrocarbon',regulate,'AHR'),
event('AHR',regulate,'polycyclic aromatic hydrocarbon'),
event('PPAR',increase,'PPARA'),
event('PPAR',increase,'PPARB'),
event('PPARA',increase,'PPAR'),
event('PPARA',increase,'PPARB'),
event('PPARB',increase,'PPAR'),
event('PPARB',increase,'PPARA'),
event('RXR',bind,'RAR'),
event('RXR',bind,'RARA'),
event('RAR',bind,'RXR'),
event('RAR',bind,'RARA'),
event('RARA',bind,'RXR'),
event('RARA',bind,'RAR'),
event('polycyclic aromatic hydrocarbon',stimulate,'AHR'),
event('AHR',stimulate,'polycyclic aromatic hydrocarbon'),
event('FXR',target,'ABCB1'),
event('FXR',target,'ABCB4'),
event('FXR',target,'ABCB1'),
event('FXR',target,'ABCB4'),
event('FXR',express,'GW4064'),
event('FXR',express,'GW4064'),
event('FXR',involve,'FXR'),
event('FXR',involve,'FXR'),
event('GW4064',target,'FXR'),
event('GW4064',target,'FXR'),
event('bile acid',mediate,'RXR'),
event('bile acid',mediate,'FXR'),
event('bile acid',mediate,'FXR'),
event('Lithocholic acid',mediate,'RXR'),
event('Lithocholic acid',mediate,'FXR'),
event('Lithocholic acid',mediate,'FXR'),
event('chenodeoxycholic acid',mediate,'RXR'),
event('chenodeoxycholic acid',mediate,'FXR'),
event('chenodeoxycholic acid',mediate,'FXR'),
event('GW4064',increase,'bile acid'),
event('GW4064',increase,'Lithocholic acid'),
event('GW4064',increase,'chenodeoxycholic acid'),
event('FXR',increase,'bile acid'),
event('FXR',increase,'Lithocholic acid'),
event('FXR',increase,'chenodeoxycholic acid'),
event('FXR',increase,'bile acid'),
event('FXR',increase,'Lithocholic acid'),
event('FXR',increase,'chenodeoxycholic acid'),
event('SHP',mediate,'GATA'),
event('SHP',mediate,'GATA1'),
event('FXR',regulate,'FXR'),
event('FXR',regulate,'FXR'),
event('bile acid',bind,'Lithocholic acid'),
event('bile acid',bind,'chenodeoxycholic acid'),
event('Lithocholic acid',bind,'bile acid'),
event('Lithocholic acid',bind,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',bind,'bile acid'),
event('chenodeoxycholic acid',bind,'Lithocholic acid'),
event('bile acid',mediate,'Lithocholic acid'),
event('bile acid',mediate,'chenodeoxycholic acid'),
event('bile acid',mediate,'progesterone analog'),
event('bile acid',mediate,'STAT'),
event('Lithocholic acid',mediate,'bile acid'),
event('Lithocholic acid',mediate,'chenodeoxycholic acid'),
event('Lithocholic acid',mediate,'progesterone analog'),
event('Lithocholic acid',mediate,'STAT'),
event('chenodeoxycholic acid',mediate,'bile acid'),
event('chenodeoxycholic acid',mediate,'Lithocholic acid'),
event('chenodeoxycholic acid',mediate,'progesterone analog'),
event('chenodeoxycholic acid',mediate,'STAT'),
event('ABCG1',activate,'LXR'),
event('RXR',induce,'ABCG1'),
event('LXR',induce,'ABCG1'),
event('ABCG1',associate,'FXR'),
event('ABCG1',associate,'LXR'),
event('ABCG1',associate,'FXR'),
event('VDR',inhibit,'RXR'),
event('LXR',induce,'RXR'),
event('LXR',induce,'RAR'),
event('LXR',induce,'RARA'),
event('abca1',induce,'RXR'),
event('NR3C1',bind,'vitamin D analog'),
event('NR3C1',interact,'vitamin D analog'),
event('LXR',activate,'PPAR'),
event('LXR',activate,'PPARA'),
event('LXR',activate,'abca1'),
event('PPAR',activate,'LXR'),
event('PPAR',activate,'PPARA'),
event('PPAR',activate,'abca1'),
event('PPARA',activate,'LXR'),
event('PPARA',activate,'PPAR'),
event('PPARA',activate,'abca1'),
event('abca1',activate,'LXR'),
event('abca1',activate,'PPAR'),
event('abca1',activate,'PPARA'),
event('RAR',regulate,'ABCG1'),
event('RARA',regulate,'ABCG1'),
event('RAR',increase,'ABCG1'),
event('RARA',increase,'ABCG1'),
event('ABCG1',regulate,'LXR'),
event('LXR',enhance,'RAR'),
event('LXR',enhance,'RARA'),
event('RAR',increase,'LXR'),
event('RAR',increase,'abca1'),
event('RARA',increase,'LXR'),
event('RARA',increase,'abca1'),
event('LXR',inhibit,'oxysterol'),
event('LXR',inhibit,'fibrate'),
event('abca1',regulate,'oxysterol'),
event('abca1',regulate,'RXR'),
event('RXR',bind,'abca1'),
event('LXR',bind,'abca1'),
event('LXRb',bind,'abca1'),
event('oxysterol',bind,'RXR'),
event('oxysterol',bind,'LXRb'),
event('oxysterol',bind,'abca1'),
event('LXRb',involve,'abca1'),
event('oxysterol',modulate,'RXR'),
event('oxysterol',modulate,'LXR'),
event('oxysterol',modulate,'abca1'),
event('abca1',modulate,'RXR'),
event('LXR',require,'LXRa'),
event('LXRa',require,'LXR'),
event('abca1',involve,'oxysterol'),
event('oxysterol',mediate,'PPAR'),
event('oxysterol',mediate,'PPARA'),
event('oxysterol',mediate,'PPARG'),
event('oxysterol',inhibit,'troglitazone'),
event('LXRa',regulate,'LXR'),
event('RXRa',bind,'FXR'),
event('RXRa',bind,'FXR'),
event('abca1',bind,'RXR'),
event('abca1',bind,'LXR'),
event('LXR',suppress,'oxysterol'),
event('LXR',suppress,'LXRa'),
event('LXR',suppress,'abca1'),
event('LXRa',suppress,'oxysterol'),
event('LXRa',suppress,'LXR'),
event('LXRa',suppress,'abca1'),
event('RXR',suppress,'abca1'),
event('oxysterol',regulate,'LXR'),
event('oxysterol',regulate,'LXRb'),
event('oxysterol',regulate,'LXRa'),
event('LXR',bind,'LXRb'),
event('LXR',increase,'RAR'),
event('LXR',increase,'RARA'),
event('LXR',promote,'RAR'),
event('LXR',promote,'RARA'),
event('RAR',enhance,'RARA'),
event('RARA',enhance,'RAR'),
event('LXR',express,'LXRa'),
event('LXRb',express,'LXR'),
event('LXRb',express,'LXRa'),
event('GW3965',inhibit,'oxysterol'),
event('LXR',mediate,'oxysterol'),
event('LXRa',mediate,'oxysterol'),
event('LXR',require,'LXRb'),
event('PPAR',mediate,'RXR'),
event('PPAR',mediate,'PPARA'),
event('PPAR',mediate,'PPARG'),
event('PPARA',mediate,'RXR'),
event('PPARA',mediate,'PPAR'),
event('PPARA',mediate,'PPARG'),
event('PPARG',mediate,'RXR'),
event('PPARG',mediate,'PPAR'),
event('PPARG',mediate,'PPARA'),
event('fibrate',bind,'PPARG'),
event('PPAR',heterodimerize,'RXR'),
event('PPARA',heterodimerize,'RXR'),
event('RXR',bind,'progesterone analog'),
event('PPAR',bind,'progesterone analog'),
event('PPARA',bind,'progesterone analog'),
event('NR3C1',express,'VDR'),
event('NR3C1',require,'VDR'),
event('NR3C1',enhance,'RXR'),
event('NR3C1',enhance,'VDR'),
event('VDR',enhance,'RXR'),
event('RAR',express,'RARA'),
event('RARA',express,'RAR'),
event('RAR',express,'RXR'),
event('RARA',express,'RXR'),
event('RXR',regulate,'androstane'),
event('RXR',regulate,'NR1I3'),
event('RXR',regulate,'FXR'),
event('RXR',regulate,'PPAR'),
event('RXR',regulate,'PPARA'),
event('RXR',regulate,'NR1I2'),
event('RXR',regulate,'FXR'),
event('GW3965',associate,'abca1'),
event('LXR',associate,'abca1'),
event('abca1',induce,'LXR'),
event('RXR',inhibit,'LXR'),
event('NR3C1',express,'vitamin D analog'),
event('vitamin D analog',require,'NR3C1'),
event('vitamin D analog',associate,'NR3C1'),
event('abca1',target,'GW3965'),
event('abca1',target,'vitamin D analog'),
event('abca1',target,'LXR'),
event('GW3965',inhibit,'vitamin D analog'),
event('GW3965',inhibit,'abca1'),
event('LXR',decrease,'vitamin D analog'),
event('LXR',repress,'STAT'),
event('dehydroepiandrosterone',trigger,'LXR'),
event('sult2a1',trigger,'LXR'),
event('LXR',bind,'ABCG1'),
event('RAR',activate,'LXRb'),
event('RAR',activate,'RARA'),
event('RAR',activate,'RARB'),
event('RARA',activate,'LXRb'),
event('RARA',activate,'RAR'),
event('RARA',activate,'RARB'),
event('RARB',activate,'LXRb'),
event('RARB',activate,'RAR'),
event('RARB',activate,'RARA'),
event('LRH',inhibit,'vitamin D analog'),
event('RXR',inhibit,'vitamin D analog'),
event('RXR',inhibit,'LRH'),
event('vitamin D analog',suppress,'RXR'),
event('LRH',suppress,'RXR'),
event('LRH',regulate,'vitamin D analog'),
event('transcription factor Oct-1',mediate,'LRH'),
event('LRH',regulate,'NR3C1'),
event('LRH',increase,'NR3C1'),
event('LRH',promote,'NR3C1'),
event('LRH',modulate,'SHP'),
event('GW4064',increase,'FXR'),
event('GW4064',increase,'FXR'),
event('GW4064',increase,'GATA'),
event('GW4064',increase,'GATA1'),
event('FXR',increase,'GATA'),
event('FXR',increase,'GATA1'),
event('FXR',increase,'GATA'),
event('FXR',increase,'GATA1'),
event('GATA',increase,'GW4064'),
event('GATA1',increase,'GW4064'),
event('GW4064',enhance,'GATA'),
event('GW4064',enhance,'GATA1'),
event('GATA',enhance,'GATA1'),
event('GATA1',enhance,'GATA'),
event('VDR',express,'CYP7A1'),
event('VDR',activate,'CYP7A1'),
event('VDR',activate,'RXR'),
event('VDR',activate,'RXRa'),
event('VDR',inhibit,'CYP7A1'),
event('VDR',interact,'CYP7A1'),
event('VDR',interact,'HNF4A      '),
event('FXR',activate,'PPAR'),
event('FXR',activate,'PPARA'),
event('FXR',activate,'PPAR'),
event('FXR',activate,'PPARA'),
event('FXR',decrease,'FXR'),
event('FXR',decrease,'FXR'),
event('SHP',repress,'FXR'),
event('SHP',repress,'FXR'),
event('androstane',enhance,'CYP1A1'),
event('NR1I3',enhance,'CYP1A1'),
event('androstane',bind,'NR1I3'),
event('NR1I3',bind,'androstane'),
event('CYP1A1',bind,'androstane'),
event('CYP1A1',bind,'NR1I3'),
event('androstane',increase,'CYP1A1'),
event('androstane',increase,'CYP1A2'),
event('NR1I3',increase,'CYP1A1'),
event('NR1I3',increase,'CYP1A2'),
event('NID1',require,'NR3C1'),
event('androstane',increase,'RXRa'),
event('NR1I3',increase,'RXRa'),
event('NR1I2',increase,'RXRa'),
event('ABCC1',regulate,'FXR'),
event('ABCC1',regulate,'FXR'),
event('ABCC1',regulate,'TST1'),
event('ABCC2',regulate,'FXR'),
event('ABCC2',regulate,'FXR'),
event('ABCC2',regulate,'TST1'),
event('ABCC1',induce,'GW4064'),
event('ABCC1',induce,'FXR'),
event('ABCC1',induce,'FXR'),
event('ABCC2',induce,'GW4064'),
event('ABCC2',induce,'FXR'),
event('ABCC2',induce,'FXR'),
event('androstane',bind,'RXR'),
event('androstane',bind,'RXRa'),
event('NR1I3',bind,'RXR'),
event('NR1I3',bind,'RXRa'),
event('FXR',bind,'RXRa'),
event('NR1I2',bind,'RXR'),
event('NR1I2',bind,'RXRa'),
event('FXR',bind,'RXRa'),
event('NR1I2',activate,'Phenobarbital'),
event('NR1I2',activate,'androstane'),
event('NR1I2',activate,'NR1I3'),
event('NR1I2',activate,'cyp2b6'),
event('PPAR',regulate,'RXR'),
event('PPARA',regulate,'RXR'),
event('PPARG',bind,'RXR'),
event('PPARG',bind,'RXRa'),
event('vitamin D analog',interact,'FXR'),
event('vitamin D analog',interact,'FXR'),
event('vitamin D analog',inhibit,'RXR'),
event('abca1',stimulate,'RXR'),
event('abca1',stimulate,'RXRa'),
event('abca1',stimulate,'RAR'),
event('abca1',stimulate,'RARA'),
event('abca1',stimulate,'RARB'),
event('abca1',stimulate,'RARG'),
event('RAR',increase,'RARA'),
event('RARA',increase,'RAR'),
event('VDR',increase,'NR1I2'),
event('NR3C1',bind,'RXR'),
event('RXR',bind,'RXRa'),
event('RXR',bind,'PPAR'),
event('RXR',bind,'PPARA'),
event('RXRa',bind,'RXR'),
event('RXRa',bind,'PPAR'),
event('RXRa',bind,'PPARA'),
event('PPAR',inhibit,'GATA'),
event('PPAR',inhibit,'GATA1'),
event('PPARA',inhibit,'GATA'),
event('PPARA',inhibit,'GATA1'),
event('PPARG',inhibit,'GATA'),
event('PPARG',inhibit,'GATA1'),
event('RXR',target,'RXRa'),
event('GW4064',increase,'NR1I2'),
event('GATA',activate,'FXR'),
event('GATA',activate,'FXR'),
event('GATA1',activate,'FXR'),
event('GATA1',activate,'FXR'),
event('FXR',bind,'GW4064'),
event('FXR',bind,'GW4064'),
event('bile acid',increase,'RAR'),
event('bile acid',increase,'RARA'),
event('Lithocholic acid',increase,'RAR'),
event('Lithocholic acid',increase,'RARA'),
event('chenodeoxycholic acid',increase,'RAR'),
event('chenodeoxycholic acid',increase,'RARA'),
event('androstane',retain,'NR1I3'),
event('NR1I3',retain,'androstane'),
event('Phenobarbital',increase,'androstane'),
event('Phenobarbital',increase,'NR1I3'),
event('LXRa',induce,'LXR'),
event('LXR',regulate,'LXRa'),
event('ABCG1',induce,'oxysterol'),
event('LXR',heterodimerize,'oxysterol'),
event('ABCG5',target,'oxysterol'),
event('ABCG5',target,'LXR'),
event('ABCG5',target,'LXRb'),
event('ABCG8',target,'oxysterol'),
event('ABCG8',target,'LXR'),
event('ABCG8',target,'LXRb'),
event('ABCG5',increase,'LXR'),
event('ABCG5',regulate,'LXR'),
event('TST1',lead,'progesterone analog'),
event('RXR',activate,'abca1'),
event('RXR',activate,'ABCG1'),
event('LXR',increase,'progesterone analog'),
event('LXR',increase,'PPAR'),
event('LXR',increase,'PPARA'),
event('PPAR',increase,'progesterone analog'),
event('PPARA',increase,'progesterone analog'),
event('LXR',bind,'CYP1A1'),
event('CYP1A1',increase,'GW3965'),
event('CYP1A1',increase,'LXR'),
event('CYP1A2',increase,'GW3965'),
event('CYP1A2',increase,'LXR'),
event('LXR',prevent,'androstane'),
event('RAR',enhance,'RXR'),
event('RARA',enhance,'RXR'),
event('RXR',bind,'polycyclic aromatic hydrocarbon'),
event('RXR',bind,'AHR'),
event('PPAR',bind,'polycyclic aromatic hydrocarbon'),
event('PPAR',bind,'AHR'),
event('PPARA',bind,'polycyclic aromatic hydrocarbon'),
event('PPARA',bind,'AHR'),
event('PPAR',target,'PPARA'),
event('PPARA',target,'PPAR'),
event('RXR',increase,'NFE2L2'),
event('RXR',interact,'NFE2L2'),
event('RXR',bind,'NFE2L2'),
event('RXR',bind,'cyp3a5'),
event('NR1I2',bind,'cyp3a5'),
event('STAT',interact,'RXR'),
event('PPAR',modulate,'PPARA'),
event('PPARA',modulate,'PPAR'),
event('PPAR',promote,'PPARA'),
event('PPARA',promote,'PPAR'),
event('VDR',repress,'RXR'),
event('RAR',bind,'RARG'),
event('RARA',bind,'RARG'),
event('RARG',bind,'RAR'),
event('RARG',bind,'RARA'),
event('RXR',inhibit,'RAR'),
event('RXR',inhibit,'RARA'),
event('RXR',inhibit,'RARG'),
event('RAR',bind,'RXRa'),
event('RARA',bind,'RXRa'),
event('RXRa',bind,'RAR'),
event('RXRa',bind,'RARA'),
event('RXR',involve,'RXRb'),
event('RXR',involve,'RXRg'),
event('RXRa',involve,'RXR'),
event('RXRa',involve,'RXRb'),
event('RXRa',involve,'RXRg'),
event('PPAR',bind,'PPARD'),
event('PPAR',bind,'PPARG'),
event('PPARA',bind,'PPARD'),
event('PPARA',bind,'PPARG'),
event('RAR',heterodimerize,'RXR'),
event('RARA',heterodimerize,'RXR'),
event('RXR',require,'RXRa'),
event('RXRa',require,'RXR'),
event('RXR',enhance,'RAR'),
event('RXR',enhance,'RARA'),
event('RAR',enhance,'RXRa'),
event('RARA',enhance,'RXRa'),
event('HNF4A      ',bind,'RXR'),
event('HNF4A      ',bind,'RXRa'),
event('HNF4A      ',bind,'PPAR'),
event('HNF4A      ',bind,'PPARA'),
event('RXR',dimerize,'PPAR'),
event('RXR',dimerize,'PPARA'),
event('RXR',inhibit,'PPAR'),
event('RXR',inhibit,'PPARA'),
event('RXR',bind,'vitamin D analog'),
event('VDR',bind,'vitamin D analog'),
event('PPAR',regulate,'vitamin D analog'),
event('PPARA',regulate,'vitamin D analog'),
event('RAR',decrease,'RARA'),
event('RARA',decrease,'RAR'),
event('RAR',increase,'RXR'),
event('RAR',increase,'RXRb'),
event('RAR',increase,'RXRg'),
event('RARA',increase,'RXR'),
event('RARA',increase,'RXRb'),
event('RARA',increase,'RXRg'),
event('RARB',increase,'RXR'),
event('RARB',increase,'RXRb'),
event('RARB',increase,'RXRg'),
event('RXRb',bind,'RXR'),
event('RXR',express,'RAR'),
event('RXR',express,'RARA'),
event('RXR',require,'progesterone analog'),
event('RXR',require,'PPAR'),
event('RXR',require,'PPARA'),
event('PPAR',require,'progesterone analog'),
event('PPAR',require,'PPARA'),
event('PPARA',require,'progesterone analog'),
event('PPARA',require,'PPAR'),
event('PPARG',require,'progesterone analog'),
event('PPARG',require,'PPAR'),
event('PPARG',require,'PPARA'),
event('RXR',prevent,'RXRa'),
event('troglitazone',bind,'RXR'),
event('troglitazone',bind,'RXRa'),
event('troglitazone',bind,'RAR'),
event('troglitazone',bind,'RARA'),
event('troglitazone',bind,'PPAR'),
event('troglitazone',bind,'PPARA'),
event('troglitazone',bind,'PPARG'),
event('RXR',regulate,'RXRa'),
event('RXRa',regulate,'RXR'),
event('RXRa',regulate,'FXR'),
event('RXRa',regulate,'FXR'),
event('LXR',regulate,'FXR'),
event('LXR',regulate,'FXR'),
event('LXRa',regulate,'FXR'),
event('LXRa',regulate,'FXR'),
event('vitamin D analog',bind,'VDR'),
event('dehydroepiandrosterone',require,'CEBPB'),
event('dehydroepiandrosterone',require,'enhancer-binding protein beta'),
event('VDR',require,'CEBPB'),
event('VDR',require,'enhancer-binding protein beta'),
event('sult2a1',require,'CEBPB'),
event('sult2a1',require,'enhancer-binding protein beta'),
event('FXR',induce,'FXR'),
event('FXR',induce,'FXR'),
event('T0901317',increase,'abca1'),
event('abca1',mediate,'RXR'),
event('abca1',mediate,'RXRb'),
event('RXR',heterodimerize,'RAR'),
event('RXR',heterodimerize,'RARA'),
event('RXRb',heterodimerize,'RAR'),
event('RXRb',heterodimerize,'RARA'),
event('LXR',induce,'abca1'),
event('PPAR',induce,'abca1'),
event('PPARA',induce,'abca1'),
event('PPAR',induce,'progesterone analog'),
event('PPARA',induce,'progesterone analog'),
event('PPAR',activate,'fibrate'),
event('PPARA',activate,'fibrate'),
event('RXR',increase,'abca1'),
event('RXR',increase,'ABCG1'),
event('RXR',induce,'RAR'),
event('RXR',induce,'RARA'),
event('RXR',associate,'PPAR'),
event('RXR',associate,'PPARA'),
event('RXR',associate,'PPARG'),
event('PPAR',associate,'RXR'),
event('PPAR',associate,'PPARA'),
event('PPAR',associate,'PPARG'),
event('PPARA',associate,'RXR'),
event('PPARA',associate,'PPAR'),
event('PPARA',associate,'PPARG'),
event('PPARG',associate,'RXR'),
event('PPARG',associate,'PPAR'),
event('PPARG',associate,'PPARA'),
event('RXR',regulate,'RXRb'),
event('RXR',regulate,'PPARD'),
event('RXRg',regulate,'RXR'),
event('RXRg',regulate,'RXRa'),
event('RXRg',regulate,'RXRb'),
event('RXRg',regulate,'PPAR'),
event('RXRg',regulate,'PPARA'),
event('RXRg',regulate,'PPARD'),
event('PPAR',regulate,'RXRa'),
event('PPAR',regulate,'RXRb'),
event('PPAR',regulate,'PPARA'),
event('PPAR',regulate,'PPARD'),
event('PPARA',regulate,'RXRa'),
event('PPARA',regulate,'RXRb'),
event('PPARA',regulate,'PPAR'),
event('PPARA',regulate,'PPARD'),
event('PPARG',regulate,'RXR'),
event('PPARG',regulate,'RXRa'),
event('PPARG',regulate,'RXRb'),
event('PPARG',regulate,'PPAR'),
event('PPARG',regulate,'PPARA'),
event('PPARG',regulate,'PPARD'),
event('PPAR',express,'PPARA'),
event('PPARA',express,'PPAR'),
event('PPAR',mediate,'RAR'),
event('PPAR',mediate,'RARA'),
event('PPARA',mediate,'RAR'),
event('PPARA',mediate,'RARA'),
event('PPAR',decrease,'PPARA'),
event('PPARA',decrease,'PPAR'),
event('PPAR',induce,'vitamin D analog'),
event('PPAR',induce,'PPARA'),
event('PPARA',induce,'vitamin D analog'),
event('PPARA',induce,'PPAR'),
event('RXR',bind,'VDR'),
event('RXR',induce,'VDR'),
event('vitamin D analog',induce,'RXR'),
event('progesterone analog',inhibit,'vitamin D analog'),
event('progesterone analog',interact,'NR3C1'),
event('TST1',interact,'NR3C1'),
event('PPAR',activate,'RXR'),
event('PPARA',activate,'RXR'),
event('RXR',prevent,'PPAR'),
event('RXR',prevent,'PPARA'),
event('RXR',involve,'PPAR'),
event('RXR',involve,'PPARA'),
event('PPAR',inhibit,'PPARA'),
event('PPARA',inhibit,'PPAR'),
event('LXR',activate,'RXR'),
event('RXR',regulate,'RAR'),
event('RXR',regulate,'RARA'),
event('RXR',regulate,'VDR'),
event('LXR',mediate,'RXR'),
event('FXR',induce,'FXRE'),
event('FXR',induce,'FXRE'),
event('RXR',bind,'FXRE'),
event('FXR',bind,'FXRE'),
event('FXR',bind,'FXRE'),
event('FXR',enhance,'vitamin D analog'),
event('FXR',enhance,'vitamin D analog'),
event('RXR',enhance,'vitamin D analog'),
event('RXRa',enhance,'vitamin D analog'),
event('SHP',enhance,'vitamin D analog'),
event('FXR',bind,'vitamin D analog'),
event('FXR',bind,'vitamin D analog'),
event('SHP',repress,'vitamin D analog'),
event('vitamin D analog',mediate,'FXR'),
event('vitamin D analog',mediate,'SHP'),
event('vitamin D analog',mediate,'FXR'),
event('ABCG1',regulate,'PPAR'),
event('ABCG1',regulate,'PPARA'),
event('LXR',stimulate,'ABCG1'),
event('PPAR',stimulate,'ABCG1'),
event('PPARA',stimulate,'ABCG1'),
event('PPAR',increase,'ABCG1'),
event('PPARA',increase,'ABCG1'),
event('RXR',involve,'LXR'),
event('RAR',involve,'LXR'),
event('RARA',involve,'LXR'),
event('RXR',modulate,'RAR'),
event('RXR',modulate,'RARA'),
event('TST1',express,'RXR'),
event('RXR',increase,'PPAR'),
event('RXR',increase,'PPARA'),
event('RXR',require,'RAR'),
event('RXR',require,'RARA'),
event('VDR',increase,'RXR'),
event('PPAR',target,'PPARG'),
event('PPARA',target,'PPARG'),
event('PPARG',target,'PPAR'),
event('PPARG',target,'PPARA'),
event('RXR',bind,'PPARG'),
event('RXR',lead,'RXRa'),
event('RXRa',lead,'RXR'),
event('progesterone analog',induce,'RAR'),
event('progesterone analog',induce,'RARA'),
event('progesterone analog',inhibit,'RAR'),
event('progesterone analog',inhibit,'RARA'),
event('vitamin D analog',increase,'PPAR'),
event('vitamin D analog',increase,'PPARA'),
event('PPAR',target,'RXR'),
event('PPARA',target,'RXR'),
event('PPAR',stimulate,'progesterone analog'),
event('PPARA',stimulate,'progesterone analog'),
event('PPARG',stimulate,'progesterone analog'),
event('PPAR',activate,'progesterone analog'),
event('PPARA',activate,'progesterone analog'),
event('GW4064',induce,'FXR'),
event('GW4064',induce,'FXR'),
event('GW4064',induce,'ABCC1'),
event('FXR',induce,'ABCC1'),
event('FXR',induce,'ABCC1'),
event('CYP7A1',regulate,'GATA'),
event('CYP7A1',regulate,'GATA1'),
event('FXR',modulate,'CYP7A1'),
event('FXR',modulate,'FXR'),
event('FXR',modulate,'CYP7A1'),
event('FXR',modulate,'FXR'),
event('immune protein Tsi1',increase,'FXR'),
event('immune protein Tsi1',increase,'FXR'),
event('FXR',associate,'FXR'),
event('FXR',associate,'FXR'),
event('GW4064',decrease,'SHP'),
event('GW4064',decrease,'cyp2d6'),
event('cyp2d6',decrease,'SHP'),
event('SHP',express,'FXR'),
event('SHP',express,'FXR'),
event('FXR',enhance,'FXR'),
event('FXR',enhance,'FXR'),
event('GW4064',enhance,'FXR'),
event('GW4064',enhance,'ABCB11'),
event('GW4064',enhance,'FXR'),
event('guggulsterone',enhance,'ABCB11'),
event('FXR',regulate,'TST1'),
event('FXR',regulate,'TST1'),
event('bile acid',target,'NR3C1'),
event('Lithocholic acid',target,'NR3C1'),
event('chenodeoxycholic acid',target,'NR3C1'),
event('NR3C1',activate,'FXR'),
event('NR3C1',activate,'FXR'),
event('NR3C1',activate,'TST1'),
event('ABCB11',regulate,'FXR'),
event('ABCB11',regulate,'FXR'),
event('ABCB11',induce,'oxysterol'),
event('ABCB11',induce,'LXR'),
event('ABCB11',increase,'oxysterol'),
event('oxysterol',mediate,'FXR'),
event('oxysterol',mediate,'LXR'),
event('oxysterol',mediate,'FXR'),
event('ABCB11',mediate,'FXR'),
event('ABCB11',mediate,'LXR'),
event('ABCB11',mediate,'FXR'),
event('ABCB11',induce,'FXR'),
event('ABCB11',induce,'FXR'),
event('oxysterol',induce,'FXR'),
event('oxysterol',induce,'ABCB11'),
event('oxysterol',induce,'FXR'),
event('FXR',induce,'ABCB11'),
event('FXR',induce,'ABCB11'),
event('LXR',prevent,'FXR'),
event('LXR',prevent,'FXR'),
event('FXR',inhibit,'oxysterol'),
event('FXR',inhibit,'LXR'),
event('FXR',inhibit,'oxysterol'),
event('FXR',inhibit,'LXR'),
event('SLCO1A2',regulate,'FXR'),
event('SLCO1A2',regulate,'LXR'),
event('SLCO1A2',regulate,'NR1I2'),
event('SLCO1A2',regulate,'FXR'),
event('SLCO1A2',regulate,'TST1'),
event('SLCO1B3',regulate,'FXR'),
event('SLCO1B3',regulate,'LXR'),
event('SLCO1B3',regulate,'NR1I2'),
event('SLCO1B3',regulate,'FXR'),
event('SLCO1B3',regulate,'TST1'),
event('clotrimazole',induce,'SLCO1A2'),
event('clotrimazole',induce,'SLCO1B3'),
event('FXR',induce,'SLCO1A2'),
event('FXR',induce,'SLCO1B3'),
event('LXR',induce,'SLCO1A2'),
event('LXR',induce,'SLCO1B3'),
event('NR1I2',induce,'SLCO1A2'),
event('NR1I2',induce,'SLCO1B3'),
event('FXR',induce,'SLCO1A2'),
event('FXR',induce,'SLCO1B3'),
event('FXR',bind,'LRH'),
event('FXR',bind,'LRH'),
event('LRH',bind,'FXR'),
event('LRH',bind,'FXR'),
event('LRH',recruit,'FXR'),
event('LRH',recruit,'FXR'),
event('FXR',lead,'FXR'),
event('FXR',lead,'FXR'),
event('FXR',increase,'vitamin D analog'),
event('FXR',increase,'vitamin D analog'),
event('FXR',target,'GW4064'),
event('FXR',target,'GW4064'),
event('FXR',activate,'SHP'),
event('FXR',activate,'SHP'),
event('FXR',regulate,'GATA'),
event('FXR',regulate,'GATA1'),
event('FXR',regulate,'GATA'),
event('FXR',regulate,'GATA1'),
event('FXR',mediate,'FXR'),
event('FXR',mediate,'FXR'),
event('GW4064',activate,'FXR'),
event('GW4064',activate,'FXR'),
event('GW4064',activate,'TST1'),
event('GW4064',express,'FXR'),
event('GW4064',express,'FXR'),
event('FXR',increase,'RXRa'),
event('FXR',increase,'RXRa'),
event('SHP',induce,'CYP7A1'),
event('SHP',induce,'FXR'),
event('SHP',induce,'FXR'),
event('NR1I2',inhibit,'SHP'),
event('SHP',decrease,'CYP7A1'),
event('SHP',recruit,'GATA'),
event('SHP',recruit,'GATA1'),
event('CYP7A1',activate,'FXR'),
event('CYP7A1',activate,'SHP'),
event('CYP7A1',activate,'FXR'),
event('SHP',involve,'HNF4A      '),
event('SHP',promote,'LXR'),
event('SHP',bind,'cyproterone acetate'),
event('SHP',mediate,'LXR'),
event('SHP',involve,'PPAR'),
event('SHP',involve,'PPARA'),
event('SHP',increase,'PPAR'),
event('SHP',increase,'PPARA'),
event('SHP',require,'PPAR'),
event('SHP',require,'PPARA'),
event('FXR',lead,'SHP'),
event('FXR',lead,'SHP'),
event('SHP',repress,'cyp2d6'),
event('SHP',inhibit,'androstane'),
event('SHP',inhibit,'NR1I3'),
event('SHP',mediate,'STAT'),
event('STAT',mediate,'SHP'),
event('SHP',associate,'STAT'),
event('HNF1A',bind,'HNF4A      '),
event('SHP',inhibit,'HNF1A'),
event('SHP',inhibit,'HNF4A      '),
event('FXR',mediate,'RXR'),
event('FXR',mediate,'SHP'),
event('FXR',mediate,'RXR'),
event('FXR',mediate,'SHP'),
event('RXR',regulate,'SHP'),
event('RXR',regulate,'ABCB11'),
event('RXR',regulate,'ABCB1'),
event('RXRa',regulate,'SHP'),
event('RXRa',regulate,'ABCB11'),
event('RXRa',regulate,'ABCB1'),
event('FXR',regulate,'ABCB1'),
event('FXR',regulate,'ABCB1'),
event('FXR',activate,'RXRa'),
event('FXR',activate,'RXRa'),
event('FXR',mediate,'NR3C1'),
event('FXR',mediate,'NR3C1'),
event('SHP',increase,'vitamin D analog'),
event('SHP',interact,'LXR'),
event('SHP',interact,'LXRb'),
event('SHP',interact,'LXRa'),
event('SHP',inhibit,'LXR'),
event('SHP',inhibit,'abca1'),
event('LXRa',activate,'PPAR'),
event('LXRa',activate,'PPARA'),
event('SHP',decrease,'RXR'),
event('SHP',decrease,'RXRa'),
event('SHP',decrease,'LXR'),
event('SHP',decrease,'LXRa'),
event('SHP',decrease,'PPAR'),
event('SHP',decrease,'PPARA'),
event('SHP',decrease,'PPARG'),
event('LXR',involve,'SHP'),
event('LXR',involve,'PPAR'),
event('LXR',involve,'PPARA'),
event('LXR',involve,'PPARG'),
event('LXRa',involve,'SHP'),
event('LXRa',involve,'PPAR'),
event('LXRa',involve,'PPARA'),
event('LXRa',involve,'PPARG'),
event('FXR',regulate,'simvastatin'),
event('LXR',regulate,'simvastatin'),
event('FXR',regulate,'simvastatin'),
event('simvastatin',induce,'FXR'),
event('simvastatin',induce,'FXR'),
event('FXR',bind,'SHP'),
event('LXR',bind,'SHP'),
event('FXR',bind,'SHP'),
event('SHP',decrease,'progesterone analog'),
event('LRH',stimulate,'SHP'),
event('SHP',regulate,'FXR'),
event('SHP',regulate,'LRH'),
event('SHP',regulate,'FXR'),
event('PPAR',repress,'SHP'),
event('PPARA',repress,'SHP'),
event('SHP',interact,'STAT'),
event('SHP',involve,'STAT'),
event('STAT',repress,'SHP'),
event('SHP',inhibit,'STAT'),
event('SHP',modulate,'HNF4A      '),
event('SHP',bind,'PPAR'),
event('SHP',bind,'PPARA'),
event('SHP',bind,'PPARG'),
event('SHP',enhance,'PPAR'),
event('SHP',enhance,'PPARA'),
event('SHP',enhance,'PPARG'),
event('RXR',bind,'NR1I2'),
event('SHP',repress,'SLC10A2'),
event('SHP',inhibit,'RXR'),
event('SHP',bind,'RXR'),
event('GW4064',involve,'HNF4A      '),
event('cyp2d6',induce,'HNF4A      '),
event('fibrate',target,'SHP'),
event('fibrate',increase,'SHP'),
event('SHP',modulate,'fibrate'),
event('GW4064',induce,'ABCC2'),
event('FXR',increase,'GW4064'),
event('FXR',increase,'GW4064'),
event('FXRE',increase,'GW4064'),
event('GW4064',inhibit,'RXR'),
event('GW4064',inhibit,'FXR'),
event('GW4064',inhibit,'FXR'),
event('PPAR',target,'FXR'),
event('PPAR',target,'LXR'),
event('PPAR',target,'SHP'),
event('PPAR',target,'FXR'),
event('PPARA',target,'FXR'),
event('PPARA',target,'LXR'),
event('PPARA',target,'SHP'),
event('PPARA',target,'FXR'),
event('RAR',bind,'FXR'),
event('RAR',bind,'FXR'),
event('RARA',bind,'FXR'),
event('RARA',bind,'FXR'),
event('FXR',heterodimerize,'RXR'),
event('FXR',heterodimerize,'RXR'),
event('SHP',interact,'androstane'),
event('SHP',interact,'NR1I3'),
event('progesterone analog',bind,'RXR'),
event('progesterone analog',bind,'RXRa'),
event('progesterone analog',bind,'PPAR'),
event('progesterone analog',bind,'PPARA'),
event('SHP',modulate,'progesterone analog'),
event('SHP',modulate,'PPAR'),
event('SHP',modulate,'PPARA'),
event('SHP',modulate,'RXR'),
event('SHP',modulate,'RXRa'),
event('FXR',modulate,'SHP'),
event('FXR',modulate,'SHP'),
event('FXR',prevent,'SHP'),
event('FXR',prevent,'SHP'),
event('FXR',recruit,'FXR'),
event('FXR',recruit,'FXR'),
event('FXR',induce,'STAT'),
event('FXR',induce,'STAT'),
event('GW4064',inhibit,'SHP'),
event('GW4064',inhibit,'STAT'),
event('GW4064',increase,'SHP'),
event('FXRE',target,'FXR'),
event('FXRE',target,'FXR'),
event('FXR',promote,'FXR'),
event('FXR',promote,'FXR'),
event('FXR',induce,'vitamin D analog'),
event('FXR',induce,'vitamin D analog'),
event('FXR',regulate,'FXRE'),
event('FXR',regulate,'FXRE'),
event('FXR',regulate,'ABCC1'),
event('FXR',regulate,'ABCC4'),
event('FXR',regulate,'ABCC1'),
event('FXR',regulate,'ABCC4'),
event('FXR',induce,'ABCC4'),
event('FXR',induce,'ABCC4'),
event('FXR',suppress,'ABCC1'),
event('FXR',suppress,'ABCC4'),
event('FXR',suppress,'ABCC1'),
event('FXR',suppress,'ABCC4'),
event('FXR',suppress,'androstane'),
event('FXR',suppress,'NR1I3'),
event('FXR',suppress,'androstane'),
event('FXR',suppress,'NR1I3'),
event('FXR',regulate,'androstane'),
event('FXR',regulate,'NR1I3'),
event('FXR',regulate,'androstane'),
event('FXR',regulate,'NR1I3'),
event('SHP',induce,'GW4064'),
event('GW4064',inhibit,'guggulsterone'),
event('FXR',associate,'androstane'),
event('FXR',associate,'NR1I3'),
event('FXR',associate,'androstane'),
event('FXR',associate,'NR1I3'),
event('ABCB11',associate,'androstane'),
event('ABCB11',associate,'NR1I3'),
event('ABCB11',associate,'FXR'),
event('ABCB11',associate,'FXR'),
event('androstane',lead,'NR1I3'),
event('androstane',lead,'FXR'),
event('androstane',lead,'ABCB11'),
event('androstane',lead,'FXR'),
event('androstane',lead,'FXRE'),
event('NR1I3',lead,'androstane'),
event('NR1I3',lead,'FXR'),
event('NR1I3',lead,'ABCB11'),
event('NR1I3',lead,'FXR'),
event('NR1I3',lead,'FXRE'),
event('FXR',require,'androstane'),
event('FXR',require,'NR1I3'),
event('ABCB11',require,'androstane'),
event('ABCB11',require,'NR1I3'),
event('FXR',require,'androstane'),
event('FXR',require,'NR1I3'),
event('androstane',target,'FXR'),
event('androstane',target,'FXR'),
event('NR1I3',target,'FXR'),
event('NR1I3',target,'FXR'),
event('FXR',recruit,'androstane'),
event('FXR',recruit,'NR1I3'),
event('FXR',recruit,'ABCB11'),
event('FXR',recruit,'androstane'),
event('FXR',recruit,'NR1I3'),
event('FXR',recruit,'ABCB11'),
event('FXR',recruit,'RXR'),
event('FXR',recruit,'RXR'),
event('FABP6',target,'LXR'),
event('LXR',bind,'FABP6'),
event('LXR',bind,'FXRE'),
event('FABP6',bind,'FXR'),
event('FABP6',bind,'LXR'),
event('FABP6',bind,'FXR'),
event('FABP6',bind,'FXRE'),
event('RXR',recognize,'FXR'),
event('RXR',recognize,'FXR'),
event('RXR',recognize,'FXRE'),
event('LXR',recognize,'FXR'),
event('LXR',recognize,'FXR'),
event('LXR',recognize,'FXRE'),
event('LXR',regulate,'FABP6'),
event('FXR',lead,'PPAR'),
event('FXR',lead,'PPARA'),
event('FXR',lead,'PPAR'),
event('FXR',lead,'PPARA'),
event('ABCB11',mediate,'RXR'),
event('ABCB11',mediate,'FXRE'),
event('RXR',mediate,'GW4064'),
event('RXR',mediate,'FXR'),
event('RXR',mediate,'FXR'),
event('ABCB11',mediate,'GW4064'),
event('RXR',decrease,'FXR'),
event('RXR',decrease,'ABCB11'),
event('RXR',decrease,'FXR'),
event('RXR',decrease,'FXRE'),
event('FXR',repress,'FXR'),
event('FXR',repress,'FXR'),
event('FXRE',repress,'FXR'),
event('FXRE',repress,'FXR'),
event('ABCB11',induce,'RXR'),
event('ABCB11',induce,'RXRa'),
event('ABCB1',induce,'RXR'),
event('ABCB1',induce,'RXRa'),
event('FXR',repress,'ABCB11'),
event('FXR',repress,'ABCB1'),
event('FXR',repress,'ABCB11'),
event('FXR',repress,'ABCB1'),
event('FXR',require,'ABCB11'),
event('FXR',require,'ABCB1'),
event('FXR',require,'ABCB11'),
event('FXR',require,'ABCB1'),
event('USF',involve,'androstane'),
event('USF',involve,'NR1I3'),
event('USF',bind,'androstane'),
event('USF',bind,'NR1I3'),
event('USF',interact,'androstane'),
event('USF',interact,'NR1I3'),
event('HNF4A      ',bind,'TST1'),
event('TST1',decrease,'HNF4A      '),
event('HNF4A      ',associate,'TST1'),
event('AML1',target,'HNF4A      '),
event('USF',increase,'NR3C1'),
event('USF',mediate,'SHP'),
event('USF',bind,'SHP'),
event('USF',increase,'vitamin D analog'),
event('RXR',bind,'USF'),
event('RXR',bind,'GATA'),
event('VDR',bind,'progesterone analog'),
event('VDR',bind,'USF'),
event('VDR',bind,'GATA'),
event('USF',bind,'progesterone analog'),
event('USF',bind,'GATA'),
event('GATA',target,'GATA1'),
event('STAT',bind,'RXR'),
event('STAT',bind,'RXRa'),
event('STAT',bind,'RAR'),
event('STAT',bind,'RARA'),
event('RAR',enhance,'STAT'),
event('RARA',enhance,'STAT'),
event('STAT',enhance,'RAR'),
event('STAT',enhance,'RARA'),
event('RAR',associate,'RARA'),
event('RAR',associate,'STAT'),
event('RARA',associate,'RAR'),
event('RARA',associate,'STAT'),
event('STAT',associate,'RAR'),
event('STAT',associate,'RARA'),
event('STAT',require,'RXR'),
event('STAT',require,'RXRa'),
event('STAT',require,'RAR'),
event('STAT',require,'RARA'),
event('Trans-acting T-cell-specific transcription factor GATA-3',express,'progesterone analog'),
event('LRH',bind,'HNF4A      '),
event('GATA',bind,'HNF4A      '),
event('GATA',bind,'LRH'),
event('LRH',activate,'HNF4A      '),
event('LRH',activate,'GATA'),
event('LXR',enhance,'HNF3B'),
event('HNF1A',bind,'HNF3B'),
event('HNF1A',increase,'HNF3B'),
event('HNF4A      ',express,'Phenobarbital'),
event('HNF4A      ',express,'cyp2b6'),
event('HNF4A      ',express,'HNF3B'),
event('androstane',induce,'Phenobarbital'),
event('androstane',induce,'cyp2b6'),
event('androstane',induce,'cyp2c9'),
event('androstane',induce,'cyp2c19'),
event('androstane',induce,'cyp3a4'),
event('NR1I3',induce,'Phenobarbital'),
event('NR1I3',induce,'cyp2b6'),
event('NR1I3',induce,'cyp2c9'),
event('NR1I3',induce,'cyp2c19'),
event('NR1I3',induce,'cyp3a4'),
event('HNF3B',associate,'progesterone analog'),
event('abca1',bind,'TATA'),
event('HNF3B',bind,'abca1'),
event('HNF3B',inhibit,'oxysterol'),
event('HNF3B',inhibit,'RXR'),
event('HNF3B',inhibit,'LXR'),
event('HNF3B',inhibit,'abca1'),
event('abca1',involve,'TATA'),
event('HNF3B',involve,'abca1'),
event('HNF3B',involve,'TATA'),
event('NR1I2',associate,'cyp3a4'),
event('ABCB1',associate,'cyp3a4'),
event('SHP',induce,'androstane'),
event('SHP',induce,'NR1I3'),
event('CAP',associate,'progesterone analog'),
event('bile acid',increase,'Lithocholic acid'),
event('bile acid',increase,'chenodeoxycholic acid'),
event('Lithocholic acid',increase,'bile acid'),
event('Lithocholic acid',increase,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',increase,'bile acid'),
event('chenodeoxycholic acid',increase,'Lithocholic acid'),
event('NR3C1',decrease,'bile acid'),
event('NR3C1',decrease,'Lithocholic acid'),
event('NR3C1',decrease,'chenodeoxycholic acid'),
event('bile acid',induce,'PPAR'),
event('bile acid',induce,'PPARA'),
event('Lithocholic acid',induce,'PPAR'),
event('Lithocholic acid',induce,'PPARA'),
event('chenodeoxycholic acid',induce,'PPAR'),
event('chenodeoxycholic acid',induce,'PPARA'),
event('bile acid',induce,'Lithocholic acid'),
event('bile acid',induce,'chenodeoxycholic acid'),
event('Lithocholic acid',induce,'bile acid'),
event('Lithocholic acid',induce,'chenodeoxycholic acid'),
event('chenodeoxycholic acid',induce,'bile acid'),
event('chenodeoxycholic acid',induce,'Lithocholic acid'),
event('progesterone analog',target,'PPARG'),
event('PPAR',target,'progesterone analog'),
event('PPARA',target,'progesterone analog'),
event('PPARG',target,'progesterone analog'),
event('progesterone analog',induce,'nqo1'),
event('GATA',regulate,'CYP7A1'),
event('GATA1',regulate,'CYP7A1'),
event('STAT',recognize,'polycyclic aromatic hydrocarbon'),
event('STAT',recognize,'AHR'),
event('polycyclic aromatic hydrocarbon',target,'AHR'),
event('polycyclic aromatic hydrocarbon',target,'STAT'),
event('AHR',target,'polycyclic aromatic hydrocarbon'),
event('AHR',target,'STAT'),
event('STAT',bind,'progesterone analog'),
event('STAT',induce,'progesterone analog'),
event('bile acid',increase,'STAT'),
event('Lithocholic acid',increase,'STAT'),
event('chenodeoxycholic acid',increase,'STAT'),
event('PPAR',increase,'STAT'),
event('PPARA',increase,'STAT'),
event('bile acid',promote,'STAT'),
event('Lithocholic acid',promote,'STAT'),
event('chenodeoxycholic acid',promote,'STAT'),
event('FXR',mediate,'STAT'),
event('FXR',mediate,'STAT'),
event('STAT',bind,'FXR'),
event('STAT',bind,'FXR'),
event('LRH',repress,'STAT'),
event('CYP1A1',repress,'STAT'),
event('SLCO1A2',bind,'ABCC1'),
event('ABCC1',bind,'SLCO1A2'),
event('vitamin D analog',inhibit,'STAT'),
event('LXR',enhance,'STAT'),
event('LXR',inhibit,'STAT'),
event('LXRb',mediate,'LXR'),
event('LXRa',mediate,'LXR'),
event('STAT',mediate,'LXR'),
event('LXRa',regulate,'abca1'),
event('LXR',lead,'abca1'),
event('LXRa',lead,'abca1'),
event('STAT',enhance,'LXR'),
event('STAT',enhance,'LXRa'),
event('LXR',decrease,'abca1'),
event('LXRa',decrease,'abca1'),
event('STAT',decrease,'abca1'),
event('RAR',lead,'RARA'),
event('RARA',lead,'RAR'),
event('STAT',lead,'RAR'),
event('STAT',lead,'RARA'),
event('RAR',retain,'RXR'),
event('RAR',retain,'RARA'),
event('RARA',retain,'RXR'),
event('RARA',retain,'RAR'),
event('RXR',activate,'STAT'),
event('RXR',associate,'RXRa'),
event('RXRa',associate,'RXR'),
event('STAT',associate,'RXR'),
event('STAT',associate,'RXRa'),
event('RXR',increase,'STAT'),
event('RXRa',increase,'STAT'),
event('STAT',inhibit,'PPAR'),
event('STAT',inhibit,'PPARA'),
event('STAT',lead,'SHP'),
event('SHP',regulate,'STAT'),
event('HNF1A',regulate,'SHP'),
event('HNF1A',lead,'SHP'),
event('HNF1A',lead,'STAT'),
event('SHP',regulate,'vitamin D analog'),
event('STAT',regulate,'vitamin D analog'),
event('SHP',suppress,'STAT'),
event('HNF1A',target,'CEBPB'),
event('HNF1A',target,'enhancer-binding protein beta'),
event('CEBPB',target,'HNF1A'),
event('CEBPB',target,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',target,'HNF1A'),
event('enhancer-binding protein beta',target,'CEBPB'),
event('CEBPB',regulate,'HNF1A'),
event('enhancer-binding protein beta',regulate,'HNF1A'),
event('progesterone analog',express,'CEBPB'),
event('progesterone analog',express,'enhancer-binding protein beta'),
event('CEBPB',inhibit,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',inhibit,'CEBPB'),
event('CEBPB',bind,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',bind,'CEBPB'),
event('CEBPB',promote,'PPAR'),
event('CEBPB',promote,'PPARA'),
event('enhancer-binding protein beta',promote,'PPAR'),
event('enhancer-binding protein beta',promote,'PPARA'),
event('CEBPB',lead,'PPAR'),
event('CEBPB',lead,'PPARA'),
event('enhancer-binding protein beta',lead,'PPAR'),
event('enhancer-binding protein beta',lead,'PPARA'),
event('CEBPB',induce,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',induce,'CEBPB'),
event('CEBPB',express,'GATA'),
event('enhancer-binding protein beta',express,'GATA'),
event('CEBPB',express,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',express,'CEBPB'),
event('NR3C1',require,'STAT'),
event('PPAR',increase,'GATA'),
event('PPARA',increase,'GATA'),
event('ABCC1',express,'ABCC2'),
event('ABCC2',express,'ABCC1'),
event('CYP1A1',inhibit,'vitamin D analog'),
event('PPAR',target,'LXRa'),
event('PPARA',target,'LXRa'),
event('SHP',enhance,'VDR'),
event('PPAR',promote,'AKR1C4'),
event('PPAR',promote,'CEBPB'),
event('PPAR',promote,'enhancer-binding protein beta'),
event('PPARA',promote,'AKR1C4'),
event('PPARA',promote,'CEBPB'),
event('PPARA',promote,'enhancer-binding protein beta'),
event('PPARG',promote,'AKR1C4'),
event('PPARG',promote,'PPAR'),
event('PPARG',promote,'PPARA'),
event('PPARG',promote,'CEBPB'),
event('PPARG',promote,'enhancer-binding protein beta'),
event('RXR',promote,'progesterone analog'),
event('PPAR',promote,'progesterone analog'),
event('PPARA',promote,'progesterone analog'),
event('PPARG',promote,'progesterone analog'),
event('RXRb',bind,'RAR'),
event('RXRb',bind,'RARA'),
event('troglitazone',suppress,'PPAR'),
event('troglitazone',suppress,'PPARA'),
event('troglitazone',suppress,'PPARG'),
event('PPAR',suppress,'PPARA'),
event('PPAR',suppress,'PPARG'),
event('PPARA',suppress,'PPAR'),
event('PPARA',suppress,'PPARG'),
event('PPARG',suppress,'PPAR'),
event('PPARG',suppress,'PPARA'),
event('VDR',suppress,'PPAR'),
event('VDR',suppress,'PPARA'),
event('VDR',suppress,'PPARG'),
event('RXR',decrease,'PPAR'),
event('RXR',decrease,'PPARA'),
event('RXR',decrease,'PPARG'),
event('RXRg',decrease,'PPAR'),
event('RXRg',decrease,'PPARA'),
event('RXRg',decrease,'PPARG'),
event('PPAR',decrease,'PPARG'),
event('PPARA',decrease,'PPARG'),
event('PPARG',decrease,'PPAR'),
event('PPARG',decrease,'PPARA'),
event('PPARG',bind,'PPAR'),
event('PPARG',bind,'PPARA'),
event('PPARB',decrease,'PPAR'),
event('PPARB',decrease,'PPARA'),
event('CAP',regulate,'OCT1'),
event('OCT1',promote,'CAP'),
event('OCT1',associate,'vitamin D analog'),
event('transcription factor Oct-1',activate,'TST1'),
event('PPAR',increase,'OCT1'),
event('PPAR',increase,'transcription factor Oct-1'),
event('PPARA',increase,'OCT1'),
event('PPARA',increase,'transcription factor Oct-1'),
event('transcription factor Oct-1',decrease,'OCT1'),
event('OCT1',decrease,'transcription factor Oct-1'),
event('ABCB1',express,'OCT1'),
event('ABCB1',express,'transcription factor Oct-1'),
event('OCT1',express,'ABCB1'),
event('OCT1',express,'transcription factor Oct-1'),
event('transcription factor Oct-1',express,'ABCB1'),
event('transcription factor Oct-1',express,'OCT1'),
event('OCT1',inhibit,'ABCB1'),
event('transcription factor Oct-1',inhibit,'ABCB1'),
event('transcription factor Oct-1',mediate,'OCT1'),
event('ABCB11',increase,'bosentan'),
event('ABCB11',increase,'troglitazone'),
event('OCT1',inhibit,'ABCC1'),
event('OCT1',inhibit,'ABCC2'),
event('transcription factor Oct-1',inhibit,'ABCC1'),
event('transcription factor Oct-1',inhibit,'ABCC2'),
event('vitamin D analog',decrease,'OCT1'),
event('vitamin D analog',decrease,'transcription factor Oct-1'),
event('ABCB1',express,'ABCC1'),
event('ABCB1',express,'ABCC3'),
event('ABCC1',express,'ABCC3'),
event('ABCC2',express,'ABCC3'),
event('ABCB1',increase,'SLCO1A2'),
event('ABCB1',increase,'SLCO1B1'),
event('SHP',inhibit,'OCT1'),
event('SHP',inhibit,'transcription factor Oct-1'),
event('OCT1',activate,'SHP'),
event('transcription factor Oct-1',activate,'SHP'),
event('vitamin D analog',repress,'androstane'),
event('vitamin D analog',repress,'NR1I3'),
event('PPAR',induce,'AKR1C4'),
event('PPARA',induce,'AKR1C4'),
event('PPARG',induce,'AKR1C4'),
event('PPAR',lead,'AKR1C4'),
event('PPARA',lead,'AKR1C4'),
event('PPARG',lead,'AKR1C4'),
event('TRANSCRIPTION INITIATION FACTOR TFIID-1',interact,'TATA'),
event('TRANSCRIPTION INITIATION FACTOR TFIID-1',bind,'TATA'),
event('GATA',express,'GATA1'),
event('TRANSCRIPTION INITIATION FACTOR TFIID-1',activate,'TATA'),
event('oxysterol',express,'dehydroepiandrosterone'),
event('QDPR',express,'progesterone analog'),
event('progesterone analog',express,'QDPR'),
event('TATA',involve,'GATA'),
event('FXR',require,'RXR'),
event('FXR',require,'RXR'),
event('RXR',require,'ABCB11'),
event('RXR',activate,'ABCB11'),
event('FXR',activate,'ABCB11'),
event('FXR',activate,'ABCB11'),
event('vitamin D analog',bind,'TATA'),
event('LXR',bind,'TATA'),
event('LXRb',bind,'TATA'),
event('LXRa',bind,'TATA'),
event('RXR',bind,'TATA'),
event('RAR',bind,'vitamin D analog'),
event('RAR',bind,'TATA'),
event('RARA',bind,'vitamin D analog'),
event('RARA',bind,'TATA'),
event('progesterone analog',bind,'RAR'),
event('progesterone analog',bind,'RARA'),
event('progesterone analog',bind,'VDR'),
event('RAR',bind,'VDR'),
event('RARA',bind,'VDR'),
event('vitamin D analog',mediate,'progesterone analog'),
event('vitamin D analog',mediate,'RAR'),
event('vitamin D analog',mediate,'RARA'),
event('RAR',mediate,'progesterone analog'),
event('RAR',mediate,'RARA'),
event('RARA',mediate,'progesterone analog'),
event('RARA',mediate,'RAR'),
event('TATA',bind,'progesterone analog'),
event('TATA',bind,'GATA'),
event('TATA',bind,'NR3C1'),
event('TATA',bind,'RXR'),
event('TATA',bind,'PPAR'),
event('TATA',bind,'PPARA'),
event('TATA',bind,'STAT'),
event('TATA',bind,'GATA1'),
event('PPAR',induce,'fibrate'),
event('PPAR',induce,'RXR'),
event('PPARA',induce,'fibrate'),
event('PPARA',induce,'RXR'),
event('VDR',bind,'TATA'),
event('RXR',activate,'RXRg'),
event('RXRg',activate,'RXR'),
event('RXRg',activate,'VDR'),
event('RAR',mediate,'RXR'),
event('RAR',mediate,'TATA'),
event('RARA',mediate,'RXR'),
event('RARA',mediate,'TATA'),
event('RXR',increase,'VDR'),
event('TST1',increase,'RXR'),
event('TST1',increase,'VDR'),
event('progesterone analog',activate,'PPAR'),
event('progesterone analog',activate,'PPARA'),
event('progesterone analog',activate,'PPARG'),
event('fibrate',lead,'PPAR'),
event('fibrate',lead,'PPARA'),
event('VDR',recruit,'RXR'),
event('VDR',bind,'RXR'),
event('TATA',bind,'VDR'),
event('RXR',associate,'TATA'),
event('RXRg',mediate,'RXR'),
event('VDR',associate,'RXR'),
event('HFH2',increase,'transcription factor Oct-1'),
event('PPAR',suppress,'STAT'),
event('PPARA',suppress,'STAT'),
event('AML1',suppress,'STAT'),
event('AML1',interact,'GATA'),
event('AML1',associate,'RAR'),
event('AML1',associate,'RARA'),
event('AML1',associate,'CORE-BINDING FACTOR ALPHA SUBUNIT'),
event('AML1',associate,'CORE-BINDING FACTOR CBF-BETA'),
event('NR3C1',recruit,'vitamin D analog'),
event('TST1',bind,'AML1'),
event('GATA',induce,'AML1'),
event('GATA1',induce,'AML1'),
event('AML1',increase,'androstane'),
event('AML1',increase,'NR1I3'),
event('AML1',target,'TST1'),
event('CEBPB',associate,'AML1'),
event('enhancer-binding protein beta',associate,'AML1'),
event('AML1',associate,'progesterone analog'),
event('AML1',participate,'RAR'),
event('AML1',participate,'RARA'),
event('RAR',target,'RARA'),
event('RARA',target,'RAR'),
event('AML1',express,'RAR'),
event('AML1',express,'RARA'),
event('AML1',induce,'RAR'),
event('AML1',induce,'RARA'),
event('RAR',activate,'RXR'),
event('RARA',activate,'RXR'),
event('RXR',induce,'AML1'),
event('RAR',induce,'AML1'),
event('RARA',induce,'AML1'),
event('PPAR',induce,'AML1'),
event('PPARA',induce,'AML1'),
event('PPARG',induce,'AML1'),
event('ABCB1',induce,'AML1'),
event('GATA',increase,'RAR'),
event('GATA',increase,'RARA'),
event('AML1',express,'SHP'),
event('vitamin D analog',decrease,'GATA'),
event('NR3C1',decrease,'GATA'),
event('progesterone analog',induce,'GATA'),
event('GATA',repress,'GATA1'),
event('GATA',suppress,'GATA1'),
event('GATA1',suppress,'GATA'),
event('GATA',interact,'GATA1'),
event('GATA1',recognize,'GATA'),
event('GATA',regulate,'GATA1'),
event('GATA1',regulate,'GATA'),
event('GATA',require,'HNF4A      '),
event('GATA',bind,'ABCG5'),
event('GATA',bind,'ABCG8'),
event('GATA',regulate,'CYP1A1'),
event('PPAR',involve,'GATA'),
event('PPARA',involve,'GATA'),
event('PPARB',involve,'GATA'),
event('GATA',bind,'dehydroepiandrosterone'),
event('GATA',bind,'sult2a1'),
event('dehydroepiandrosterone',mediate,'GATA'),
event('sult2a1',mediate,'GATA'),
event('sult2a1',express,'dehydroepiandrosterone'),
event('dehydroepiandrosterone',regulate,'GATA'),
event('sult2a1',regulate,'GATA'),
event('dehydroepiandrosterone',increase,'GATA'),
event('sult2a1',increase,'GATA'),
event('GATA',enhance,'dehydroepiandrosterone'),
event('GATA',increase,'LRH'),
event('LRH',target,'GATA'),
event('GATA',retain,'LRH'),
event('progesterone analog',bind,'GATA'),
event('GATA',bind,'CEBPB'),
event('GATA',bind,'enhancer-binding protein beta'),
event('GATA1',target,'GATA'),
event('GATA1',express,'GATA'),
event('GATA',bind,'PPAR'),
event('GATA',bind,'PPARA'),
event('GATA',mediate,'PPAR'),
event('GATA',mediate,'PPARA'),
event('RXR',interact,'GATA'),
event('RXR',repress,'GATA'),
event('RAR',express,'GATA'),
event('RARA',express,'GATA'),
event('RAR',recognize,'GATA'),
event('RARA',recognize,'GATA'),
event('RAR',interact,'RARA'),
event('RARA',interact,'RAR'),
event('GATA',interact,'RAR'),
event('GATA',interact,'RARA'),
event('RXR',inhibit,'GATA'),
event('RXRa',inhibit,'RAR'),
event('RXRa',inhibit,'RARA'),
event('RXRa',inhibit,'GATA'),
event('STAT',inhibit,'SHP'),
event('GATA',interact,'androstane'),
event('GATA',interact,'NR1I3'),
event('GATA1',interact,'androstane'),
event('GATA1',interact,'NR1I3'),
event('androstane',enhance,'GATA'),
event('androstane',enhance,'GATA1'),
event('NR1I3',enhance,'GATA'),
event('NR1I3',enhance,'GATA1'),
event('GATA',activate,'GATA1'),
event('GATA1',activate,'GATA'),
event('GATA',induce,'GATA1'),
event('GATA',induce,'TST1'),
event('GATA1',induce,'GATA'),
event('GATA1',induce,'TST1'),
event('Erythroid transcription factor',regulate,'GATA'),
event('Erythroid transcription factor',regulate,'GATA1'),
event('androstane',regulate,'NR1I3'),
event('NR1I3',regulate,'androstane'),
event('ABCC1',interact,'TST1')
]).
