base([
event('CYP7A1',activate,'cholesterol'),
event('LRH',activate,'CYP7A1'),
event('LRH',activate,'cholesterol'),
event('cholesterol',inhibit,'CYP7A1'),
event('GATA',increase,'CYP7A1'),
event('GATA',increase,'cholesterol'),
event('GATA1',increase,'CYP7A1'),
event('GATA1',increase,'cholesterol'),
event('SHP',inhibit,'CYP7A1'),
event('SHP',increase,'cholesterol'),
event('CYP7A1',involve,'cholesterol'),
event('cholesterol',promote,'CYP7A1'),
event('GATA',decrease,'GATA1'),
event('GATA1',decrease,'GATA'),
event('QDPR',involve,'TST1'),
event('CYP7A1',associate,'cholesterol'),
event('cholesterol',associate,'FXR'),
event('FXR',induce,'SHP'),
event('oxysterol',increase,'cholesterol'),
event('FXR',decrease,'cholesterol'),
event('SHP',repress,'CYP7A1'),
event('SHP',repress,'cholesterol'),
event('cholesterol',induce,'CYP7A1'),
event('FXR',increase,'cholesterol'),
event('FXR',inhibit,'cholesterol'),
event('CYP7A1',increase,'SHP'),
event('SHP',bind,'LRH'),
event('CYP7A1',repress,'SHP'),
event('SHP',recruit,'TST1'),
event('FXR',inhibit,'CYP7A1'),
event('FXR',inhibit,'SHP'),
event('FXR',recruit,'CYP7A1'),
event('FXR',recruit,'SHP'),
event('bile acid',increase,'RXR'),
event('RXR',increase,'bile acid'),
event('bile acid',enhance,'RXR'),
event('RXR',inhibit,'FXR'),
event('CYP7A1',increase,'cholesterol'),
event('RXR',bind,'bile acid'),
event('RXR',bind,'FXR'),
event('bile acid',decrease,'RXR'),
event('RXR',target,'SHP'),
event('FXR',target,'SHP'),
event('GATA',increase,'SHP'),
event('GATA1',increase,'SHP'),
event('cholesterol',repress,'SHP'),
event('cholesterol',repress,'GATA'),
event('cholesterol',repress,'GATA1'),
event('cholesterol',increase,'SHP'),
event('cholesterol',increase,'GATA'),
event('cholesterol',increase,'GATA1'),
event('cholesterol',suppress,'CYP7A1'),
event('cholesterol',suppress,'FXR'),
event('cholesterol',stimulate,'FXR'),
event('CYP7A1',regulate,'cholesterol'),
event('CYP7A1',stimulate,'cholesterol'),
event('CYP7A1',stimulate,'oxysterol'),
event('cholesterol',stimulate,'oxysterol'),
event('cholesterol',stimulate,'CYP7A1'),
event('cholesterol',stimulate,'SHP'),
event('FXR',regulate,'CYP7A1'),
event('FXR',regulate,'SHP'),
event('cholesterol',decrease,'CYP7A1'),
event('RXR',stimulate,'CYP7A1'),
event('RXR',stimulate,'oxysterol'),
event('CYP7A1',bind,'RXR'),
event('oxysterol',bind,'CYP7A1'),
event('CYP7A1',regulate,'oxysterol'),
event('oxysterol',involve,'cholesterol'),
event('oxysterol',synthesize,'cholesterol'),
event('cholesterol',induce,'oxysterol'),
event('oxysterol',target,'cholesterol'),
event('oxysterol',regulate,'cholesterol'),
event('oxysterol',promote,'cholesterol'),
event('cholesterol',inhibit,'oxysterol'),
event('cholesterol',interact,'oxysterol'),
event('cholesterol',enhance,'oxysterol'),
event('cholesterol',enhance,'STAT'),
event('oxysterol',bind,'cholesterol'),
event('cholesterol',lead,'oxysterol'),
event('oxysterol',mediate,'cholesterol'),
event('oxysterol',inhibit,'cholesterol'),
event('cholesterol',regulate,'oxysterol'),
event('cholesterol',bind,'oxysterol'),
event('cholesterol',bind,'LXRb'),
event('oxysterol',recruit,'cholesterol'),
event('cholesterol',mediate,'oxysterol'),
event('cholesterol',associate,'CYP7A1'),
event('cholesterol',mediate,'CYP7A1'),
event('FXR',involve,'cholesterol'),
event('GATA',suppress,'CYP7A1'),
event('GATA',suppress,'cholesterol'),
event('GATA1',suppress,'CYP7A1'),
event('GATA1',suppress,'cholesterol'),
event('SHP',target,'LXRa'),
event('SHP',target,'FXR'),
event('oxysterol',increase,'LXRa'),
event('LXRa',activate,'CYP7A1'),
event('LXRa',activate,'FXR'),
event('cholesterol',regulate,'CYP7A1'),
event('CYP7A1',bind,'FXR'),
event('CYP7A1',bind,'SHP'),
event('SHP',inactivate,'CYP7A1'),
event('SHP',inactivate,'LRH'),
event('FXR',target,'CYP7A1'),
event('FXR',target,'cholesterol'),
event('cholesterol',activate,'CYP7A1'),
event('cholesterol',mediate,'LXRb'),
event('cholesterol',mediate,'LXRa'),
event('FXR',express,'LXRb'),
event('FXR',bind,'RXR'),
event('LXRa',involve,'cholesterol'),
event('LXRb',activate,'FXR'),
event('LXRb',activate,'TST1'),
event('LXRa',activate,'TST1'),
event('LXRb',involve,'cholesterol'),
event('RXR',express,'cholesterol'),
event('cholesterol',bind,'FXR'),
event('LXRb',prevent,'cholesterol'),
event('LXRa',prevent,'cholesterol'),
event('LXRb',decrease,'cholesterol'),
event('cholesterol',associate,'LXRb'),
event('oxysterol',target,'RXR'),
event('oxysterol',enhance,'cholesterol'),
event('oxysterol',stimulate,'cholesterol'),
event('cholesterol',enhance,'LXRa'),
event('LXRa',bind,'RXR'),
event('FXR',bind,'LXRa'),
event('GATA',induce,'FXR'),
event('GATA1',induce,'FXR'),
event('GATA',inhibit,'CYP7A1'),
event('GATA',inhibit,'cholesterol'),
event('GATA',inhibit,'SHP'),
event('GATA1',inhibit,'CYP7A1'),
event('GATA1',inhibit,'cholesterol'),
event('GATA1',inhibit,'SHP'),
event('SHP',bind,'GATA'),
event('SHP',bind,'GATA1'),
event('LRH',promote,'SHP'),
event('LRH',promote,'GATA'),
event('LRH',promote,'GATA1'),
event('LRH',induce,'CYP7A1'),
event('CYP7A1',mediate,'LRH'),
event('LRH',repress,'SHP'),
event('LRH',target,'CYP7A1'),
event('SHP',target,'CYP7A1'),
event('SHP',target,'LRH'),
event('LRH',target,'cholesterol'),
event('LRH',involve,'CYP7A1'),
event('LRH',involve,'FXR'),
event('LRH',involve,'cholesterol'),
event('LRH',require,'CYP7A1'),
event('LRH',require,'FXR'),
event('LRH',activate,'FXR'),
event('LRH',regulate,'CYP7A1'),
event('RXR',repress,'CYP7A1'),
event('RXR',repress,'LRH'),
event('RXR',repress,'SHP'),
event('FXR',repress,'CYP7A1'),
event('FXR',repress,'LRH'),
event('FXR',repress,'RXR'),
event('FXR',repress,'SHP'),
event('SHP',involve,'LRH'),
event('SHP',repress,'LRH'),
event('SHP',inhibit,'LRH'),
event('SHP',interact,'LRH'),
event('FXR',activate,'CYP7A1'),
event('SHP',enhance,'LRH'),
event('LRH',bind,'CYP7A1'),
event('SHP',bind,'CYP7A1'),
event('CYP7A1',increase,'LRH'),
event('FXR',increase,'CYP7A1'),
event('FXR',increase,'LRH'),
event('FXR',increase,'SHP'),
event('SHP',increase,'CYP7A1'),
event('SHP',increase,'LRH'),
event('CYP7A1',decrease,'cholesterol'),
event('CYP7A1',bind,'LRH'),
event('LRH',enhance,'SHP'),
event('LRH',enhance,'CYP7A1'),
event('SHP',involve,'FXR'),
event('cholesterol',express,'LRH'),
event('LRH',activate,'SHP'),
event('LRH',activate,'RXR'),
event('LRH',increase,'cholesterol'),
event('FXR',require,'CYP7A1'),
event('LRH',repress,'CYP7A1'),
event('FXR',stimulate,'LRH'),
event('FXR',stimulate,'SHP'),
event('LRH',induce,'FXR'),
event('LRH',induce,'SHP'),
event('CYP7A1',regulate,'SHP'),
event('cholesterol',regulate,'SHP'),
event('LRH',increase,'SHP'),
event('SHP',involve,'CYP7A1'),
event('SHP',involve,'cholesterol'),
event('cholesterol',mediate,'LRH'),
event('cholesterol',mediate,'FXR'),
event('cholesterol',mediate,'SHP'),
event('FXR',suppress,'CYP7A1'),
event('FXR',suppress,'cholesterol'),
event('FXR',suppress,'LRH'),
event('SHP',suppress,'CYP7A1'),
event('SHP',suppress,'cholesterol'),
event('SHP',suppress,'LRH'),
event('LRH',target,'STAT'),
event('cholesterol',bind,'LRH'),
event('cholesterol',bind,'CEBPB'),
event('cholesterol',bind,'enhancer-binding protein beta'),
event('LRH',involve,'SHP'),
event('FXR',activate,'RXR'),
event('LRH',increase,'RXR'),
event('LRH',increase,'FXR'),
event('FXR',mediate,'LRH'),
event('SHP',mediate,'LRH'),
event('LRH',regulate,'SHP'),
event('LRH',express,'cholesterol'),
event('LRH',regulate,'cholesterol'),
event('LRH',decrease,'GATA'),
event('LRH',target,'SHP'),
event('CYP7A1',associate,'FXR'),
event('CYP7A1',repress,'RXR'),
event('CYP7A1',repress,'FXR'),
event('CYP7A1',repress,'GATA'),
event('CYP7A1',repress,'GATA1'),
event('RXR',increase,'CYP7A1'),
event('RXR',increase,'FXR'),
event('FXR',increase,'RXR'),
event('cholesterol',bind,'CYP7A1'),
event('LXRa',bind,'CYP7A1'),
event('cholesterol',increase,'CYP7A1'),
event('RXR',activate,'CYP7A1'),
event('RXR',activate,'oxysterol'),
event('CYP7A1',stimulate,'RXR'),
event('oxysterol',mediate,'CYP7A1'),
event('RXR',mediate,'CYP7A1'),
event('RXR',mediate,'cholesterol'),
event('FXR',mediate,'CYP7A1'),
event('FXR',mediate,'cholesterol'),
event('RXR',enhance,'cholesterol'),
event('SHP',regulate,'cholesterol'),
event('FXR',induce,'CYP7A1'),
event('FXR',induce,'GATA'),
event('FXR',induce,'GATA1'),
event('GATA',repress,'CYP7A1'),
event('GATA',repress,'SHP'),
event('GATA1',repress,'CYP7A1'),
event('GATA1',repress,'SHP'),
event('SHP',associate,'CYP7A1'),
event('CYP7A1',target,'cholesterol'),
event('GATA',express,'CYP7A1'),
event('GATA1',express,'CYP7A1'),
event('HNF3B',bind,'GATA'),
event('NID1',interact,'RXR'),
event('TST1',bind,'RXR'),
event('zinc ion',associate,'RXR'),
event('transcription factor Oct-1',require,'RXR'),
event('RXR',activate,'FXR'),
event('GATA',bind,'GATA1'),
event('GATA1',bind,'GATA'),
event('bile acid',mediate,'RXR'),
event('bile acid',mediate,'FXR'),
event('FXR',increase,'bile acid'),
event('SHP',mediate,'GATA'),
event('SHP',mediate,'GATA1'),
event('bile acid',mediate,'STAT'),
event('RXR',increase,'cholesterol'),
event('RXR',bind,'cholesterol'),
event('cholesterol',bind,'RXR'),
event('oxysterol',bind,'RXR'),
event('oxysterol',modulate,'RXR'),
event('RXR',regulate,'cholesterol'),
event('RXR',regulate,'FXR'),
event('RXR',interact,'cholesterol'),
event('RXR',inhibit,'LRH'),
event('LRH',suppress,'RXR'),
event('transcription factor Oct-1',mediate,'LRH'),
event('LRH',modulate,'SHP'),
event('LRH',stimulate,'cholesterol'),
event('FXR',increase,'GATA'),
event('FXR',increase,'GATA1'),
event('GATA',enhance,'GATA1'),
event('GATA1',enhance,'GATA'),
event('FXR',activate,'cholesterol'),
event('SHP',repress,'FXR'),
event('FXR',bind,'RXRa'),
event('RXR',induce,'cholesterol'),
event('GATA',activate,'FXR'),
event('GATA1',activate,'FXR'),
event('cholesterol',involve,'RXR'),
event('cholesterol',involve,'RXRa'),
event('cholesterol',activate,'RXR'),
event('STAT',interact,'RXR'),
event('cholesterol',require,'RXR'),
event('RXR',regulate,'RXRa'),
event('RXR',regulate,'RXRb'),
event('RXRg',regulate,'RXR'),
event('RXRg',regulate,'RXRa'),
event('RXRg',regulate,'RXRb'),
event('FXR',induce,'FXRE'),
event('RXR',bind,'FXRE'),
event('FXR',bind,'FXRE'),
event('TST1',express,'RXR'),
event('cholesterol',mediate,'GATA'),
event('cholesterol',mediate,'GATA1'),
event('SHP',inhibit,'cholesterol'),
event('FXR',regulate,'cholesterol'),
event('cholesterol',increase,'FXR'),
event('CYP7A1',regulate,'GATA'),
event('CYP7A1',regulate,'GATA1'),
event('FXR',modulate,'CYP7A1'),
event('FXR',induce,'cholesterol'),
event('immune protein Tsi1',increase,'FXR'),
event('FXR',bind,'cholesterol'),
event('SHP',express,'FXR'),
event('FXR',regulate,'TST1'),
event('cholesterol',activate,'FXR'),
event('cholesterol',activate,'TST1'),
event('FXR',express,'cholesterol'),
event('oxysterol',mediate,'FXR'),
event('oxysterol',induce,'FXR'),
event('FXR',dimerize,'cholesterol'),
event('FXR',inhibit,'oxysterol'),
event('FXR',bind,'LRH'),
event('LRH',bind,'FXR'),
event('LRH',recruit,'FXR'),
event('FXR',activate,'SHP'),
event('FXR',regulate,'GATA'),
event('FXR',regulate,'GATA1'),
event('SHP',induce,'CYP7A1'),
event('SHP',induce,'FXR'),
event('SHP',decrease,'CYP7A1'),
event('SHP',decrease,'cholesterol'),
event('SHP',activate,'cholesterol'),
event('SHP',recruit,'GATA'),
event('SHP',recruit,'GATA1'),
event('CYP7A1',activate,'FXR'),
event('CYP7A1',activate,'SHP'),
event('SHP',target,'cholesterol'),
event('FXR',lead,'SHP'),
event('SHP',mediate,'STAT'),
event('STAT',mediate,'SHP'),
event('SHP',require,'cholesterol'),
event('SHP',associate,'STAT'),
event('FXR',mediate,'RXR'),
event('FXR',mediate,'SHP'),
event('RXR',regulate,'SHP'),
event('SHP',interact,'LXRb'),
event('SHP',interact,'LXRa'),
event('SHP',decrease,'RXR'),
event('FXR',bind,'SHP'),
event('LRH',stimulate,'SHP'),
event('SHP',regulate,'LRH'),
event('SHP',regulate,'FXR'),
event('SHP',interact,'STAT'),
event('SHP',involve,'STAT'),
event('STAT',repress,'SHP'),
event('SHP',inhibit,'STAT'),
event('SHP',inhibit,'RXR'),
event('SHP',bind,'RXR'),
event('FXR',heterodimerize,'cholesterol'),
event('FXR',heterodimerize,'RXR'),
event('SHP',modulate,'RXR'),
event('FXR',modulate,'SHP'),
event('FXR',prevent,'SHP'),
event('FXR',induce,'STAT'),
event('FXRE',target,'FXR'),
event('FXR',regulate,'FXRE'),
event('FXR',recruit,'RXR'),
event('RXR',recognize,'FXR'),
event('RXR',recognize,'FXRE'),
event('RXR',mediate,'FXR'),
event('RXR',decrease,'FXR'),
event('RXR',decrease,'FXRE'),
event('FXRE',repress,'FXR'),
event('USF',mediate,'SHP'),
event('USF',bind,'SHP'),
event('RXR',bind,'USF'),
event('RXR',bind,'GATA'),
event('USF',bind,'GATA'),
event('GATA',target,'GATA1'),
event('STAT',bind,'RXR'),
event('STAT',require,'RXR'),
event('GATA',bind,'LRH'),
event('LRH',activate,'GATA'),
event('HNF3B',inhibit,'oxysterol'),
event('HNF3B',inhibit,'RXR'),
event('HNF3B',involve,'TATA'),
event('GATA',regulate,'CYP7A1'),
event('GATA',regulate,'cholesterol'),
event('GATA1',regulate,'CYP7A1'),
event('GATA1',regulate,'cholesterol'),
event('bile acid',increase,'STAT'),
event('bile acid',promote,'STAT'),
event('FXR',mediate,'STAT'),
event('STAT',bind,'FXR'),
event('LRH',repress,'STAT'),
event('STAT',inhibit,'cholesterol'),
event('cholesterol',increase,'STAT'),
event('STAT',decrease,'cholesterol'),
event('RXR',activate,'STAT'),
event('STAT',associate,'RXR'),
event('RXR',increase,'STAT'),
event('STAT',lead,'SHP'),
event('SHP',regulate,'STAT'),
event('SHP',suppress,'STAT'),
event('CEBPB',target,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',target,'CEBPB'),
event('CEBPB',inhibit,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',inhibit,'CEBPB'),
event('CEBPB',bind,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',bind,'CEBPB'),
event('CEBPB',induce,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',induce,'CEBPB'),
event('CEBPB',express,'GATA'),
event('enhancer-binding protein beta',express,'GATA'),
event('CEBPB',express,'enhancer-binding protein beta'),
event('enhancer-binding protein beta',express,'CEBPB'),
event('CAP',regulate,'OCT1'),
event('OCT1',promote,'CAP'),
event('transcription factor Oct-1',activate,'TST1'),
event('transcription factor Oct-1',decrease,'OCT1'),
event('OCT1',decrease,'transcription factor Oct-1'),
event('OCT1',express,'transcription factor Oct-1'),
event('transcription factor Oct-1',express,'OCT1'),
event('transcription factor Oct-1',mediate,'OCT1'),
event('SHP',inhibit,'OCT1'),
event('SHP',inhibit,'transcription factor Oct-1'),
event('OCT1',activate,'SHP'),
event('transcription factor Oct-1',activate,'SHP'),
event('TRANSCRIPTION INITIATION FACTOR TFIID-1',interact,'TATA'),
event('TRANSCRIPTION INITIATION FACTOR TFIID-1',bind,'TATA'),
event('GATA',express,'GATA1'),
event('TRANSCRIPTION INITIATION FACTOR TFIID-1',activate,'TATA'),
event('oxysterol',express,'cholesterol'),
event('TATA',involve,'GATA'),
event('FXR',require,'RXR'),
event('cholesterol',involve,'oxysterol'),
event('RXR',bind,'TATA'),
event('TATA',bind,'GATA'),
event('TATA',bind,'RXR'),
event('TATA',bind,'STAT'),
event('TATA',bind,'GATA1'),
event('TST1',increase,'RXR'),
event('RXR',associate,'TATA'),
event('HFH2',increase,'transcription factor Oct-1'),
event('AML1',suppress,'STAT'),
event('AML1',interact,'GATA'),
event('AML1',associate,'CORE-BINDING FACTOR ALPHA SUBUNIT'),
event('AML1',associate,'CORE-BINDING FACTOR CBF-BETA'),
event('TST1',bind,'AML1'),
event('GATA',induce,'AML1'),
event('GATA1',induce,'AML1'),
event('AML1',target,'TST1'),
event('CEBPB',associate,'AML1'),
event('enhancer-binding protein beta',associate,'AML1'),
event('RXR',induce,'AML1'),
event('AML1',express,'SHP'),
event('GATA',repress,'GATA1'),
event('GATA',suppress,'GATA1'),
event('GATA1',suppress,'GATA'),
event('GATA',inhibit,'zinc ion'),
event('GATA1',inhibit,'zinc ion'),
event('zinc ion',modulate,'GATA'),
event('zinc ion',modulate,'GATA1'),
event('GATA',interact,'GATA1'),
event('GATA1',recognize,'GATA'),
event('zinc ion',bind,'GATA'),
event('GATA',bind,'zinc ion'),
event('GATA',regulate,'GATA1'),
event('GATA1',regulate,'GATA'),
event('GATA',increase,'LRH'),
event('LRH',target,'GATA'),
event('GATA',retain,'LRH'),
event('GATA',bind,'CEBPB'),
event('GATA',bind,'enhancer-binding protein beta'),
event('GATA1',target,'GATA'),
event('GATA1',express,'GATA'),
event('RXR',interact,'GATA'),
event('RXR',repress,'GATA'),
event('RXR',inhibit,'GATA'),
event('STAT',inhibit,'SHP'),
event('GATA',activate,'GATA1'),
event('GATA1',activate,'GATA'),
event('GATA',induce,'GATA1'),
event('GATA',induce,'TST1'),
event('GATA1',induce,'GATA'),
event('GATA1',induce,'TST1'),
event('Erythroid transcription factor',regulate,'GATA'),
event('Erythroid transcription factor',regulate,'GATA1')
]).
