base([
event('NR1H4',inhibit,'NR1H4'),
event('cholesterol',involve,'bile acid'),
event('cholesterol',involve,'cholesterol'),
event('NR0B2',mediate,'NR0B2'),
event('NR0B2',bind,'NR0B2'),
event('NR0B2',inhibit,'bile acid'),
event('NR0B2',inhibit,'NR0B2'),
event('NR0B2',regulate,'NR0B2'),
event('CYP7A1',regulate,'NR0B2'),
event('cholesterol',regulate,'NR0B2'),
event('NR5A2',regulate,'NR0B2'),
event('NR0B2',inhibit,'CYP7A1'),
event('bile acid',regulate,'NR1H4'),
event('NR0B2',involve,'NR0B2'),
event('bile acid',regulate,'bile acid'),
event('NR1H4',regulate,'NR0B2'),
event('NR1H4',bind,'NR0B2'),
event('NR1H4',involve,'bile acid'),
event('NR0B2',involve,'bile acid'),
event('NR0B2',regulate,'NR1H2'),
event('BAAT',regulate,'NRBF2'),
event('bile acid',regulate,'NRBF2'),
event('bile acid',involve,'NR1H4'),
event('BAAT',regulate,'bile acid'),
event('cholesterol',regulate,'bile acid'),
event('NR5A2',express,'NR5A2'),
event('NR5A2',regulate,'NR5A2'),
event('CYP7A1',regulate,'bile acid'),
event('CYP7A1',regulate,'cholesterol'),
event('cholesterol',regulate,'cholesterol'),
event('CYP7A1',regulate,'CYP7A1'),
event('NR5A2',target,'NR5A2'),
event('NR5A2',bind,'NR5A2'),
event('NR5A2',regulate,'CYP7A1'),
event('NR5A2',regulate,'bile acid'),
event('NR5A2',regulate,'cholesterol'),
event('NPC2',involve,'cholesterol'),
event('NPC2',bind,'cholesterol'),
event('cholesterol',bind,'cholesterol'),
event('NPC2',regulate,'cholesterol'),
event('NPC2',regulate,'NPC2'),
event('NPC2',inhibit,'cholesterol'),
event('LCAT',inhibit,'LCAT'),
event('LCAT',bind,'LCAT'),
event('NCEH1',involve,'cholesterol'),
event('NCEH1',regulate,'cholesterol'),
event('cholesterol',modulate,'cholesterol'),
event('cholesterol',inhibit,'cholesterol'),
event('NR1H4',target,'NR0B2'),
event('NR1H2',regulate,'cholesterol'),
event('oxysterols',bind,'bile acid'),
event('oxysterols',bind,'cholesterol'),
event('NRBF2',regulate,'bile acid'),
event('NR1H4',regulate,'bile acid'),
event('NRBF2',regulate,'cholesterol'),
event('NR5A2',mediate,'NR5A2'),
event('NR5A2',associate,'NR5A2'),
event('NR5A2',mediate,'cholesterol'),
event('NR5A2',involve,'NR5A2'),
event('bile acid',inhibit,'cholesterol'),
event('NR5A2',involve,'bile acid'),
event('NR5A2',involve,'NR0B2'),
event('bile acid',inhibit,'CYP7A1'),
event('bile acid',inhibit,'bile acid'),
event('NR1H4',inhibit,'CYP7A1'),
event('NR1H4',associate,'CYP7A1'),
event('NR1H4',associate,'bile acid'),
event('NR1H4',associate,'NR1H4'),
event('NR1H4',inhibit,'NR5A2'),
event('NR1H4',inhibit,'NR0B2'),
event('NR5A2',inhibit,'CYP7A1'),
event('NR5A2',inhibit,'NR0B2'),
event('NR1H4',regulate,'NR5A2'),
event('NR5A2',regulate,'NR1H4'),
event('NR0B2',involve,'NR1H4'),
event('bile acid',inhibit,'NR0B2'),
event('NR0B2',inhibit,'NR5A2'),
event('bile acid',regulate,'NR5A2'),
event('CYP7A1',inhibit,'cholesterol'),
event('CYP7A1',bind,'NR5A2'),
event('CYP7A1',bind,'NR1H3'),
event('CYP7A1',bind,'NR1H2'),
event('CYP7A1',bind,'NR0B2'),
event('CYP7A1',regulate,'NR1H3'),
event('CYP7A1',regulate,'NR1H2'),
event('cholesterol',regulate,'NR1H3'),
event('cholesterol',regulate,'NR1H2'),
event('cholesterol',express,'NR5A2'),
event('CYP7A1',regulate,'NR5A2'),
event('NR0B2',associate,'NR0B2'),
event('CYP7A1',inhibit,'NR0B2'),
event('NR0B2',associate,'NR5A2'),
event('NR1H4',regulate,'NRBF2'),
event('NRBF2',target,'NR0B2'),
event('NR5A2',regulate,'NRBF2'),
event('NR1H4',mediate,'NR5A2'),
event('NR0B2',mediate,'NR5A2'),
event('NR0B2',involve,'CYP7A1'),
event('NR0B2',involve,'cholesterol'),
event('NR0B2',bind,'bile acid'),
event('CH25H',inhibit,'CH25H'),
event('CH25H',target,'CH25H'),
event('cholesterol',target,'cholesterol'),
event('CH25H',regulate,'CH25H'),
event('oxysterols',regulate,'CH25H'),
event('NR1H2',regulate,'CH25H'),
event('NR1H2',regulate,'NR1H2'),
event('oxysterols',regulate,'CYP7A1'),
event('CH25H',regulate,'cholesterol'),
event('cholesterol',regulate,'LCAT'),
event('LCAT',associate,'LCAT'),
event('NRBF2',inhibit,'CYP7A1'),
event('NRBF2',inhibit,'bile acid'),
event('NRBF2',inhibit,'NR5A2'),
event('NRBF2',inhibit,'NR1H2'),
event('NRBF2',inhibit,'NRBF2'),
event('NRBF2',inhibit,'NR0B2'),
event('NR1H4',inhibit,'bile acid'),
event('NR1H4',inhibit,'NR1H2'),
event('NR1H4',inhibit,'NRBF2'),
event('NRBF2',regulate,'NR1H2'),
event('cholesterol',bind,'bile acid'),
event('bile acid',mediate,'bile acid'),
event('NPC1',involve,'cholesterol'),
event('NPC1L1',involve,'cholesterol'),
event('NPC1',express,'cholesterol'),
event('NPC1L1',express,'cholesterol'),
event('cholesterol',express,'cholesterol'),
event('NPC1',associate,'cholesterol'),
event('NPC1L1',associate,'cholesterol'),
event('NPC1',mediate,'cholesterol'),
event('NPC1L1',mediate,'cholesterol'),
event('cholesterol',associate,'cholesterol'),
event('NPC2',inhibit,'NPC2'),
event('NPC2',mediate,'cholesterol'),
event('NPC1',regulate,'NPC1'),
event('cholesterol',target,'NPC2'),
event('cholesterol',associate,'NPC1'),
event('cholesterol',associate,'NPC2'),
event('NPC2',bind,'NPC1'),
event('NPC1',bind,'NPC2'),
event('cholesterol',regulate,'NPC2'),
event('NPC2',bind,'NPC2'),
event('NPC1',associate,'NPC1'),
event('NPC1',express,'NPC1'),
event('NPC1',express,'NPC1L1'),
event('NPC1',express,'NPC2'),
event('NPC1L1',express,'NPC1'),
event('NPC1L1',express,'NPC1L1'),
event('NPC1L1',express,'NPC2'),
event('NPC2',express,'NPC1'),
event('NPC2',express,'NPC1L1'),
event('NPC2',express,'NPC2'),
event('NPC1',regulate,'cholesterol'),
event('cholesterol',mediate,'cholesterol'),
event('cholesterol',regulate,'oxysterols'),
event('NPC1L1',regulate,'cholesterol'),
event('NPC1',inhibit,'NR1H2'),
event('NPC1L1',inhibit,'NR1H2'),
event('NPC1',bind,'CYP7A1'),
event('NPC1',bind,'cholesterol'),
event('NPC1',bind,'NR1H2'),
event('NPC1L1',bind,'CYP7A1'),
event('NPC1L1',bind,'cholesterol'),
event('NPC1L1',bind,'NR1H2'),
event('cholesterol',bind,'CYP7A1'),
event('cholesterol',bind,'NR1H2'),
event('cholesterol',bind,'NPC1'),
event('cholesterol',express,'NPC1'),
event('NPC1',target,'cholesterol'),
event('NPC2',target,'cholesterol'),
event('NPC1',involve,'NPC2'),
event('cholesterol',inhibit,'NR5A2'),
event('cholesterol',inhibit,'NR0B2'),
event('cholesterol',inhibit,'NPC1'),
event('FAF1',bind,'FAF1'),
event('FAF1',modulate,'FAF1'),
event('RABGAP1L',inhibit,'RABGAP1L'),
event('NR1H4',regulate,'CYP7A1'),
event('NR1H4',regulate,'NR1H3'),
event('NR1H4',regulate,'NR1H2'),
event('NR5A2',bind,'NR1H2'),
event('NR1H3',bind,'NR1H2'),
event('NR1H2',bind,'NR1H2'),
event('NR0B2',regulate,'NR5A2'),
event('NR5A2',bind,'CYP7A1'),
event('NR1H3',bind,'CYP7A1'),
event('NR1H2',bind,'CYP7A1'),
event('NR0B2',bind,'CYP7A1'),
event('NR5A2',bind,'NR1H3'),
event('NR1H2',bind,'NR1H3'),
event('NR0B2',bind,'NR1H3'),
event('NR0B2',bind,'NR1H2'),
event('NR1H3',regulate,'CYP7A1'),
event('NR1H3',regulate,'NR5A2'),
event('NR1H3',regulate,'NR1H3'),
event('NR1H3',regulate,'NR1H2'),
event('NR1H3',regulate,'NR0B2'),
event('NR1H2',regulate,'CYP7A1'),
event('NR1H2',regulate,'NR5A2'),
event('NR1H2',regulate,'NR1H3'),
event('NR1H2',regulate,'NR0B2'),
event('NR0B2',regulate,'CYP7A1'),
event('NR0B2',regulate,'NR1H3'),
event('NR5A2',mediate,'bile acid'),
event('cholesterol',inhibit,'bile acid'),
event('bile acid',regulate,'CYP7A1'),
event('NR1H3',target,'NR1H4'),
event('NR1H3',target,'NR0B2'),
event('NR1H2',target,'NR1H4'),
event('NR1H2',target,'NR0B2'),
event('bile acid',inhibit,'oxysterols'),
event('bile acid',inhibit,'NR1H3'),
event('bile acid',inhibit,'NR1H2'),
event('NR1H2',regulate,'NR1H4'),
event('NR1H4',regulate,'NR1H4'),
event('NR1H4',regulate,'RUNX1'),
event('cholesterol',regulate,'NR1H4'),
event('NR0B2',associate,'NR1H2'),
event('NR0B2',associate,'NR1H3'),
event('NR0B2',inhibit,'NR1H2'),
event('NR0B2',target,'NR1H3'),
event('NR0B2',target,'NR1H2'),
event('NR0B2',target,'NR1H4'),
event('oxysterols',regulate,'NR1H3'),
event('oxysterols',regulate,'NR1H2'),
event('bile acid',regulate,'NR0B2'),
event('bile acid',regulate,'NR1H3'),
event('bile acid',regulate,'NR1H2'),
event('bile acid',regulate,'cholesterol'),
event('NR0B2',regulate,'bile acid'),
event('NR1H2',bind,'NR0B2'),
event('cholesterol',regulate,'CYP7A1'),
event('NRBF2',regulate,'NR1H4'),
event('RIT1',inhibit,'RIT1'),
event('NUDC',bind,'NUDC'),
event('NUDC',regulate,'NUDC'),
event('NUDC',inhibit,'NUDC'),
event('NUDC',express,'NUDC'),
event('NUDC',dimerize,'NUDC'),
event('NR0B2',inhibit,'NR1H3'),
event('NR0B2',inhibit,'NRBF2'),
event('NR1H3',involve,'NR0B2'),
event('NR1H2',involve,'NR0B2'),
event('NR1H2',associate,'CYP7A1'),
event('NR1H3',associate,'CYP7A1'),
event('NR0B2',bind,'NR5A2'),
event('NR5A2',associate,'CYP7A1'),
event('NR5A2',associate,'NR1H4'),
event('NR5A2',express,'bile acid'),
event('NR5A2',express,'cholesterol'),
event('bile acid',inhibit,'NR5A2'),
event('NR5A2',target,'bile acid'),
event('NR5A2',target,'cholesterol'),
event('FAF1',regulate,'FAF1'),
event('FAF1',inhibit,'FAF1'),
event('bile acid',mediate,'NR5A2'),
event('bile acid',mediate,'NR1H4'),
event('bile acid',mediate,'NR0B2'),
event('cholesterol',mediate,'bile acid'),
event('cholesterol',mediate,'NR5A2'),
event('cholesterol',mediate,'NR1H4'),
event('cholesterol',mediate,'NR0B2'),
event('NR1H4',inhibit,'cholesterol'),
event('NR0B2',inhibit,'cholesterol'),
event('bile acid',regulate,'oxysterols'),
event('CYP7A1',bind,'bile acid'),
event('CYP7A1',bind,'NR1H4'),
event('NR5A2',target,'CYP7A1'),
event('NR5A2',involve,'cholesterol'),
event('NR1H4',bind,'NR5A2'),
event('NR1H4',bind,'NR1H4'),
event('NR5A2',bind,'NR1H4'),
event('NR1H4',express,'NR1H2'),
event('NR1H4',bind,'NRBF2'),
event('NR1H2',bind,'bile acid'),
event('NR1H2',bind,'cholesterol'),
event('cholesterol',inhibit,'NR1H2'),
event('NR1H2',inhibit,'cholesterol'),
event('NR1H2',modulate,'NR1H2'),
event('oxysterols',modulate,'oxysterols'),
event('bile acid',associate,'bile acid'),
event('bile acid',target,'NR1H4'),
event('NR1H4',target,'NR1H4'),
event('NPC1',associate,'NR1H2'),
event('NPC1L1',associate,'NR1H2'),
event('NR1H2',inhibit,'NPC1'),
event('NR1H2',inhibit,'NR1H2'),
event('NR1H3',inhibit,'NR1H2'),
event('NR1H2',regulate,'NPC1'),
event('NR1H2',regulate,'NPC2'),
event('cholesterol',regulate,'NPC1'),
event('NR1H2',modulate,'cholesterol'),
event('NR1H2',target,'NR1H2'),
event('cholesterol',inhibit,'NPC1L1'),
event('cholesterol',associate,'NR1H4'),
event('NR1H2',associate,'cholesterol'),
event('NPC1',inhibit,'cholesterol'),
event('NPC1L1',inhibit,'cholesterol'),
event('NR1H3',associate,'cholesterol'),
event('NPC1',modulate,'NPC1'),
event('NPC1',modulate,'NPC1L1'),
event('NPC1',modulate,'cholesterol'),
event('NPC1L1',modulate,'NPC1'),
event('NPC1L1',modulate,'NPC1L1'),
event('NPC1L1',modulate,'cholesterol'),
event('cholesterol',modulate,'NPC1'),
event('cholesterol',modulate,'NPC1L1'),
event('CYP7A1',inhibit,'NPC1'),
event('CYP7A1',inhibit,'NPC1L1'),
event('NPC1',associate,'CYP7A1'),
event('NPC1L1',associate,'CYP7A1'),
event('NPC1',target,'NR1H2'),
event('NPC1L1',target,'cholesterol'),
event('NPC1L1',target,'NR1H2'),
event('NR1H2',target,'cholesterol'),
event('NPC1',bind,'NPC1'),
event('NPC1',bind,'NPC1L1'),
event('NPC1L1',bind,'NPC1'),
event('NPC1L1',bind,'NPC1L1'),
event('cholesterol',involve,'NR1H3'),
event('cholesterol',involve,'NR1H2'),
event('NPC1',associate,'oxysterols'),
event('NPC2',associate,'cholesterol'),
event('NPC2',associate,'oxysterols'),
event('cholesterol',associate,'oxysterols'),
event('LCAT',regulate,'cholesterol'),
event('NR1H3',involve,'cholesterol'),
event('cholesterol',regulate,'NRBF2'),
event('NRBF2',target,'NRBF2'),
event('NR1H2',inhibit,'NPC1L1'),
event('NRBF2',inhibit,'NPC1'),
event('NRBF2',inhibit,'NPC1L1'),
event('LCAT',bind,'NR1H3'),
event('LCAT',bind,'NR1H2'),
event('cholesterol',mediate,'oxysterols'),
event('NPC1',regulate,'NR1H2'),
event('NRBF2',target,'cholesterol'),
event('cholesterol',associate,'NR1H2'),
event('cholesterol',inhibit,'CAP'),
event('CYP7A1',bind,'NPC1'),
event('CYP7A1',bind,'NPC1L1'),
event('cholesterol',associate,'NPC1L1'),
event('NRBF2',regulate,'NRBF2'),
event('NR0B2',express,'NR0B2'),
event('FOXA2',target,'FOXA2'),
event('FOXA2',bind,'FOXA2'),
event('NR1H2',regulate,'bile acid'),
event('CYP7A1',involve,'cholesterol'),
event('NR1H2',involve,'cholesterol'),
event('NR1H4',involve,'cholesterol'),
event('NR1H3',bind,'NRBF2'),
event('NR1H4',regulate,'cholesterol'),
event('NRBF2',bind,'NR1H4'),
event('NR1H4',heterodimerize,'cholesterol'),
event('NR1H4',heterodimerize,'NRBF2'),
event('NRBF2',inhibit,'NR1H4'),
event('CYP7A1',inhibit,'NRBF2'),
event('CYP7A1',inhibit,'NR1H4'),
event('NRBF2',regulate,'CYP7A1'),
event('NR1H4',express,'bile acid'),
event('NR1H4',express,'NR1H4'),
event('NR1H4',involve,'NR1H4'),
event('NR0B2',bind,'NRBF2'),
event('NRBF2',bind,'NRBF2'),
event('NR1H4',target,'bile acid'),
event('BAAT',mediate,'NRBF2'),
event('BAAT',mediate,'NR1H4'),
event('NR1H4',regulate,'BAAT'),
event('BAAT',mediate,'BAAT'),
event('BAAT',bind,'BAAT'),
event('BAAT',regulate,'BAAT'),
event('NRBF2',bind,'BAAT'),
event('RIT1',regulate,'RIT1'),
event('cholesterol',mediate,'NR1H3'),
event('cholesterol',mediate,'NR1H2'),
event('oxysterols',involve,'NR1H2'),
event('NR1H2',bind,'oxysterols'),
event('NR1H2',regulate,'oxysterols'),
event('NR1H2',target,'CYP7A1'),
event('NR1H2',target,'bile acid'),
event('FAF1',associate,'FAF1'),
event('NR1H4',regulate,'FOXA2'),
event('bile acid',target,'NR0B2'),
event('cholesterol',target,'NR1H4'),
event('cholesterol',target,'NR0B2'),
event('NR1H3',target,'oxysterols'),
event('NR1H2',target,'oxysterols'),
event('NR1H3',regulate,'oxysterols'),
event('NR1H4',regulate,'oxysterols'),
event('NR1H3',regulate,'NR1H4'),
event('NR0B2',regulate,'NR1H4'),
event('NR0B2',express,'NR1H4'),
event('NR1H4',mediate,'NRBF2'),
event('NR1H4',mediate,'NR0B2'),
event('NRBF2',regulate,'NR0B2'),
event('CYP7A1',involve,'bile acid'),
event('bile acid',involve,'bile acid'),
event('BAAT',target,'BAAT'),
event('bile acid',target,'BAAT'),
event('NR1H2',involve,'NR1H2'),
event('NR1H2',involve,'NRBF2'),
event('NR1H2',regulate,'NRBF2'),
event('NR1H2',heterodimerize,'NR1H2'),
event('NR1H2',heterodimerize,'NRBF2'),
event('NR1H4',modulate,'NR0B2'),
event('NR0B2',associate,'bile acid'),
event('bile acid',bind,'bile acid'),
event('NR1H4',bind,'bile acid'),
event('NR1H3',inhibit,'cholesterol'),
event('NR1H3',involve,'NR1H2'),
event('NR1H3',express,'NR1H2'),
event('NR1H2',express,'NR1H2'),
event('NR1H2',associate,'NR1H2'),
event('NR1H3',express,'NR1H3'),
event('NR1H2',express,'NR1H3'),
event('NR1H2',mediate,'NR1H2'),
event('NR1H2',mediate,'NRBF2'),
event('NRBF2',mediate,'NRBF2'),
event('NRBF2',express,'bile acid'),
event('NRBF2',express,'cholesterol'),
event('NR1H3',associate,'NR1H3'),
event('NR1H3',associate,'NR1H2'),
event('NR1H2',associate,'NR1H3'),
event('NR1H2',target,'NRBF2'),
event('NRBF2',target,'NR1H2'),
event('NRBF2',bind,'NR1H2'),
event('NR1H3',inhibit,'oxysterols'),
event('NR1H3',inhibit,'NR1H3'),
event('NR1H2',inhibit,'oxysterols'),
event('NR1H2',inhibit,'NR1H3'),
event('NR1H3',regulate,'NRBF2'),
event('NRBF2',bind,'cholesterol'),
event('cholesterol',bind,'NRBF2'),
event('oxysterols',bind,'NR1H2'),
event('oxysterols',bind,'NRBF2'),
event('NRBF2',associate,'cholesterol'),
event('NRBF2',associate,'NR1H2'),
event('oxysterols',target,'cholesterol'),
event('oxysterols',target,'NR1H2'),
event('oxysterols',target,'NRBF2'),
event('NR1H3',regulate,'cholesterol'),
event('NR1H2',target,'NPC1'),
event('cholesterol',regulate,'CAP'),
event('NR1H2',inhibit,'bile acid'),
event('RUNX1',regulate,'RUNX1'),
event('NR1H2',dimerize,'cholesterol'),
event('NR1H4',dimerize,'cholesterol'),
event('NR1H2',inhibit,'NR1H4'),
event('oxysterols',regulate,'cholesterol'),
event('cholesterol',inhibit,'CYP7A1'),
event('FOXA2',inhibit,'FOXA2'),
event('FOXA2',inhibit,'oxysterols'),
event('FOXA2',inhibit,'NR1H2'),
event('FOXA2',inhibit,'NRBF2'),
event('oxysterols',involve,'bile acid'),
event('oxysterols',involve,'cholesterol'),
event('oxysterols',modulate,'cholesterol'),
event('FOXA2',mediate,'FOXA2'),
event('FOXA2',regulate,'FOXA2'),
event('bile acid',associate,'NR1H4'),
event('bile acid',associate,'NR0B2'),
event('FOXA2',associate,'FOXA2'),
event('FOXA2',express,'FOXA2'),
event('cholesterol',associate,'bile acid'),
event('cholesterol',mediate,'CYP7A1'),
event('cholesterol',associate,'CYP7A1'),
event('CYP7A1',associate,'cholesterol'),
event('cholesterol',bind,'NR1H3'),
event('NR1H2',inhibit,'CYP7A1'),
event('NR1H4',express,'cholesterol'),
event('NR1H2',bind,'NRBF2'),
event('cholesterol',bind,'NR1H4'),
event('NR1H2',bind,'NR1H4'),
event('bile acid',involve,'cholesterol'),
event('NR1H4',inhibit,'NR1H3'),
event('NR1H4',bind,'NR1H3'),
event('NR1H4',bind,'NR1H2'),
event('NR1H4',target,'CYP7A1'),
event('NR1H4',target,'cholesterol'),
event('NPC1',bind,'NR1H4'),
event('NPC1L1',bind,'NR1H4'),
event('NR1H4',mediate,'NR1H4'),
event('cholesterol',mediate,'NPC1'),
event('cholesterol',mediate,'NPC1L1'),
event('NR1H4',inhibit,'NPC1'),
event('NR1H4',inhibit,'NPC1L1'),
event('LCAT',associate,'cholesterol'),
event('LCAT',involve,'cholesterol'),
event('cholesterol',associate,'LCAT'),
event('cholesterol',inhibit,'LCAT'),
event('NR1H4',modulate,'bile acid'),
event('bile acid',inhibit,'NR1H4'),
event('NR1H4',associate,'NR0B2'),
event('NR0B2',regulate,'cholesterol'),
event('NR0B2',inhibit,'NR1H4'),
event('CYP7A1',regulate,'NR1H4'),
event('NR1H3',inhibit,'CYP7A1'),
event('cholesterol',inhibit,'NR1H3'),
event('CYP7A1',bind,'cholesterol'),
event('NR1H2',regulate,'FOXA2'),
event('SRY',regulate,'SRY'),
event('SRY',bind,'SRY'),
event('SRY',associate,'SRY'),
event('SRY',express,'SRY'),
event('NPC1',regulate,'NR5A2'),
event('NPC1L1',regulate,'NR5A2'),
event('NRBF2',regulate,'oxysterols'),
event('CYP7A1',regulate,'NRBF2'),
event('bile acid',mediate,'CYP7A1'),
event('bile acid',mediate,'cholesterol'),
event('NR1H2',mediate,'CYP7A1'),
event('NR1H2',mediate,'bile acid'),
event('NR1H2',mediate,'cholesterol'),
event('NRBF2',mediate,'CYP7A1'),
event('NRBF2',mediate,'bile acid'),
event('NRBF2',mediate,'cholesterol'),
event('NR1H4',mediate,'CYP7A1'),
event('NR1H4',mediate,'bile acid'),
event('NR1H4',mediate,'cholesterol'),
event('CYP7A1',bind,'CYP7A1'),
event('CYP7A1',associate,'NR1H2'),
event('CYP7A1',associate,'NR1H4'),
event('bile acid',associate,'cholesterol'),
event('NR1H4',modulate,'CYP7A1'),
event('NR1H4',modulate,'NR1H4'),
event('NR5A2',bind,'NR0B2'),
event('NR0B2',associate,'cholesterol'),
event('SRY',inhibit,'cholesterol'),
event('oxysterols',modulate,'NR1H2'),
event('oxysterols',bind,'NR1H3'),
event('NR1H3',bind,'NR1H3'),
event('NR1H2',involve,'bile acid'),
event('bile acid',involve,'CYP7A1'),
event('CYP7A1',inhibit,'bile acid'),
event('NR0B2',associate,'CYP7A1'),
event('CYP7A1',target,'bile acid'),
event('CYP7A1',target,'cholesterol'),
event('cholesterol',regulate,'NPC1L1'),
event('cholesterol',bind,'NPC1L1'),
event('cholesterol',target,'bile acid'),
event('NPC2',regulate,'bile acid'),
event('NPC2',regulate,'NPC1'),
event('NPC1',associate,'NPC1L1'),
event('NPC1L1',associate,'NPC1'),
event('NPC1L1',associate,'NPC1L1'),
event('cholesterol',inhibit,'BAAT'),
event('BAAT',inhibit,'BAAT'),
event('LCAT',express,'BAAT'),
event('bile acid',express,'bile acid'),
event('LCAT',regulate,'bile acid'),
event('NR0B2',target,'NR0B2'),
event('NR0B2',associate,'NPC2'),
event('NCEH1',express,'cholesterol'),
event('BAAT',associate,'BAAT'),
event('BAAT',involve,'BAAT'),
event('NPC1',regulate,'NPC2'),
event('NPC1',mediate,'NPC1'),
event('NPC1',bind,'oxysterols'),
event('NPC2',bind,'oxysterols'),
event('cholesterol',bind,'NPC2'),
event('cholesterol',bind,'CH25H'),
event('PBX1',associate,'PBX1'),
event('PBX1',bind,'PBX1'),
event('PBX1',inhibit,'PBX1'),
event('LCAT',express,'LCAT'),
event('NR0B2',target,'CYP7A1'),
event('NR0B2',target,'cholesterol'),
event('CYP7A1',inhibit,'CYP7A1'),
event('PBX1',regulate,'PBX1'),
event('PBX1',target,'PBX1'),
event('RUNX1',associate,'PBX1'),
event('PBX1',involve,'RUNX1'),
event('LCAT',inhibit,'cholesterol'),
event('LCAT',regulate,'LCAT'),
event('NR0B2',modulate,'NR0B2'),
event('CLIP1',target,'CLIP1'),
event('CLIP1',target,'CLIP2'),
event('CLIP2',target,'CLIP1'),
event('CLIP2',target,'CLIP2'),
event('CLIP3',target,'CLIP1'),
event('CLIP3',target,'CLIP2'),
event('CLIP1',inhibit,'CLIP1'),
event('CLIP1',inhibit,'CLIP2'),
event('CLIP2',inhibit,'CLIP1'),
event('CLIP2',inhibit,'CLIP2'),
event('NR1H4',bind,'cholesterol'),
event('NR0B2',target,'bile acid'),
event('CAP',bind,'CAP'),
event('CLIP2',regulate,'CLIP2'),
event('CLIP1',bind,'CLIP1'),
event('CLIP1',bind,'CLIP2'),
event('CLIP2',bind,'CLIP1'),
event('CLIP2',bind,'CLIP2'),
event('CAP',bind,'CLIP1'),
event('CAP',bind,'CLIP2'),
event('CLIP1',regulate,'CLIP1'),
event('CLIP1',regulate,'CLIP2'),
event('CLIP2',regulate,'CLIP1'),
event('NPC1',regulate,'NPC1L1'),
event('NPC1',associate,'NPC2'),
event('NPC1L1',regulate,'NPC1'),
event('NPC1L1',regulate,'NPC1L1'),
event('NPC1',mediate,'NPC1L1'),
event('NPC1L1',mediate,'NPC1'),
event('NPC1L1',mediate,'NPC1L1'),
event('NPC1',inhibit,'NPC1'),
event('NPC1',inhibit,'NPC1L1'),
event('NPC1L1',inhibit,'NPC1'),
event('NPC1L1',inhibit,'NPC1L1'),
event('NCEH1',target,'cholesterol'),
event('NPC2',associate,'NPC2'),
event('NR5A2',inhibit,'NR5A2'),
event('CLIP1',associate,'CLIP1'),
event('CLIP1',associate,'CLIP2'),
event('CLIP2',associate,'CLIP1'),
event('CLIP2',associate,'CLIP2'),
event('PBX1',mediate,'PBX1'),
event('NR1H4',express,'NR0B2'),
event('CLIP1',mediate,'CLIP1'),
event('CLIP1',mediate,'CLIP2'),
event('CLIP2',mediate,'CLIP1'),
event('CLIP2',mediate,'CLIP2'),
event('CAP',associate,'CLIP1'),
event('CAP',associate,'CLIP2'),
event('cholesterol',regulate,'CMTR2'),
event('NR5A2',associate,'bile acid'),
event('NR5A2',associate,'cholesterol'),
event('CYP7A1',target,'CYP7A1'),
event('RUNX1',bind,'RUNX1'),
event('RUNX1',associate,'RUNX1'),
event('RUNX1',express,'RUNX1'),
event('RUNX1',target,'RUNX1'),
event('RUNX1',involve,'RUNX1'),
event('RUNX1',inhibit,'RUNX1'),
event('NCBP2',bind,'NCBP1'),
event('BAAT',express,'BAAT'),
event('BAAT',involve,'bile acid'),
event('TCAP',regulate,'TCAP'),
event('TCAP',regulate,'CAP'),
event('CAP',regulate,'TCAP'),
event('CAP',regulate,'CAP'),
event('TCAP',associate,'TCAP'),
event('TCAP',modulate,'TCAP'),
event('TCAP',associate,'CAP'),
event('CAP',associate,'TCAP'),
event('CAP',associate,'CAP'),
event('TCAP',target,'TCAP'),
event('TCAP',target,'CAP'),
event('NCBP3',regulate,'NCBP3'),
event('NCBP3',inhibit,'NCBP3'),
event('cholesterol',target,'NPC1'),
event('cholesterol',target,'NPC1L1'),
event('NPC1',bind,'NRBF2'),
event('NPC1L1',bind,'NRBF2'),
event('RUNX1',mediate,'RUNX1'),
event('CMTR1',associate,'CMTR1'),
event('NRBF2',modulate,'NRBF2'),
event('NRBF2',associate,'NRBF2'),
event('CAP',inhibit,'CAP'),
event('NR1H3',target,'CYP7A1'),
event('bile acid',associate,'CYP7A1'),
event('CYP7A1',bind,'NRBF2'),
event('bile acid',bind,'NR1H3'),
event('bile acid',bind,'NR1H2'),
event('bile acid',bind,'NRBF2'),
event('NR1H3',target,'cholesterol'),
event('NR1H3',regulate,'bile acid'),
event('RUNX1',express,'NR0B2'),
event('CAP',regulate,'NR1H4'),
event('NR1H2',involve,'oxysterols'),
event('oxysterols',inhibit,'NR1H2'),
event('NR1H3',mediate,'NR1H3'),
event('NR1H3',mediate,'NR1H2'),
event('NR1H2',mediate,'NR1H3'),
event('NR1H3',target,'NR1H3'),
event('NR1H3',target,'NR1H2'),
event('NR1H2',target,'NR1H3'),
event('NR1H2',associate,'NRBF2'),
event('cholesterol',express,'NR1H2'),
event('NCBP1',associate,'NCBP1'),
event('NCBP1',associate,'NCBP2'),
event('NCBP2',associate,'NCBP1'),
event('NCBP2',associate,'NCBP2'),
event('NCBP2',regulate,'NCBP2'),
event('NCBP2',involve,'NCBP1'),
event('CAP',express,'CAP'),
event('bile acid',bind,'NR1H4'),
event('CYP7A1',associate,'CYP7A1'),
event('NR1H2',associate,'NR1H4'),
event('NRBF2',associate,'NR1H4'),
event('FAF1',express,'FAF1'),
event('NRBF2',mediate,'NR1H2'),
event('NR1H3',associate,'NRBF2'),
event('bile acid',bind,'cholesterol'),
event('NCBP2',express,'NCBP2'),
event('NCBP2',involve,'NCBP2'),
event('NRBF2',involve,'NR1H2'),
event('NRBF2',express,'NR1H2'),
event('MDFIC',regulate,'MDFIC'),
event('MDFIC',express,'MDFIC'),
event('MDFIC',inhibit,'MDFIC'),
event('MDFIC',involve,'MDFI'),
event('MDFI',associate,'MDFI'),
event('MDFIC',associate,'MDFI'),
event('MDFI',inhibit,'MDFI'),
event('MDFIC',bind,'MDFI'),
event('MDFI',associate,'MDFIC'),
event('MDFIC',associate,'MDFIC'),
event('MDFI',inhibit,'MDFIC'),
event('MDFIC',inhibit,'MDFI'),
event('MDFI',express,'MDFI'),
event('CAP',associate,'FAF1'),
event('NPC2',target,'NPC2'),
event('cholesterol',mediate,'NPC2'),
event('NPC2',associate,'NPC1'),
event('NPC2',inhibit,'NPC1'),
event('NPC1L1',regulate,'NPC2'),
event('NPC1',inhibit,'NPC2'),
event('NPC1L1',inhibit,'NPC2'),
event('NPC2',express,'cholesterol'),
event('NPC2',regulate,'NPC1L1'),
event('cholesterol',bind,'LCAT'),
event('RIT1',associate,'RIT1'),
event('RIT1',associate,'NR1H2'),
event('NUDC',associate,'NUDC'),
event('EIF4G3',associate,'EIF4G3'),
event('EIF4G3',inhibit,'EIF4G3'),
event('MDFIC',bind,'MDFIC'),
event('bile acid',express,'CYP7A1'),
event('bile acid',express,'cholesterol'),
event('bile acid',bind,'CAP'),
event('SRY',inhibit,'SRY'),
event('SRY',regulate,'cholesterol'),
event('CMTR2',regulate,'CMTR2'),
event('TCAP',involve,'TCAP'),
event('TCAP',involve,'CAP'),
event('CAP',involve,'TCAP'),
event('CAP',involve,'CAP'),
event('NPC1',inhibit,'bile acid'),
event('NPC1L1',inhibit,'bile acid'),
event('NPC1',target,'NPC1'),
event('NPC1',target,'NPC1L1'),
event('NPC1L1',target,'NPC1'),
event('NPC1L1',target,'NPC1L1'),
event('bile acid',regulate,'NPC1'),
event('bile acid',regulate,'NPC1L1'),
event('bile acid',bind,'NPC1'),
event('bile acid',bind,'NPC1L1'),
event('BAAT',regulate,'cholesterol'),
event('BAAT',associate,'cholesterol'),
event('RABGAP1L',associate,'RABGAP1L'),
event('RABGAP1L',bind,'RABGAP1L'),
event('oxysterols',inhibit,'cholesterol'),
event('CLIP1',regulate,'NR1H2'),
event('CLIP2',regulate,'NR1H2'),
event('NCEH1',regulate,'NCEH1'),
event('CAP',mediate,'CAP'),
event('cholesterol',mediate,'NRBF2'),
event('NRBF2',involve,'cholesterol'),
event('NR1H2',associate,'oxysterols'),
event('bile acid',modulate,'bile acid'),
event('cholesterol',inhibit,'NR1H4'),
event('NR1H4',associate,'NRBF2'),
event('NRBF2',express,'NRBF2'),
event('NRBF2',mediate,'NR1H4'),
event('NRBF2',bind,'bile acid'),
event('NRBF2',associate,'bile acid'),
event('bile acid',target,'bile acid'),
event('bile acid',mediate,'NRBF2')
]).
