verb(verbo([approve])) --> [approved].
verb(verbo([inhibit])) --> [inhibits].
verb(verbo([revise])) --> [Revised].
verb(verbo([inhibit])) --> [inhibits].
verb(verbo([be])) --> [is].
verb(verbo([have])) --> [has].
verb(verbo([undergo])) --> [undergone].
verb(verbo([be])) --> [is].
verb(verbo([be])) --> [is].
verb(verbo([publish])) --> [published].
verb(verbo([discover])) --> [discovered].
verb(verbo([publish])) --> [Published].
verb(verbo([approve])) --> [approved].
verb(verbo([inhibit])) --> [inhibits].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [been].
verb(verbo([limit])) --> [limited].
verb(verbo([approve])) --> [approved].
verb(verbo([show])) --> [shown].
verb(verbo([broad-])) --> [broad-].
verb(verbo([be])) --> [is].
verb(verbo([warrant])) --> [warrants].
verb(verbo([be])) --> [is].
verb(verbo([approve])) --> [approved].
verb(verbo([show])) --> [shown].
verb(verbo([identify])) --> [identified].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [been].
verb(verbo([confirm])) --> [confirmed].
verb(verbo([be])) --> [been].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [been].
verb(verbo([show])) --> [shown].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [been].
verb(verbo([demonstrate])) --> [demonstrated].
verb(verbo([believe])) --> [believed].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [been].
verb(verbo([show])) --> [shown].
verb(verbo([pseudorabie])) --> [pseudorabies].
verb(verbo([show])) --> [shown].
verb(verbo([infect])) --> [infected].
verb(verbo([observe])) --> [observed].
verb(verbo([justify])) --> [justified].
verb(verbo([observe])) --> [observed].
verb(verbo([observe])) --> [observed].
verb(verbo([be])) --> [is].
verb(verbo([strand])) --> [stranded].
verb(verbo([be])) --> [is].
verb(verbo([relate])) --> [related].
verb(verbo([reveal])) --> [revealed].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [been].
verb(verbo([show])) --> [shown].
verb(verbo([take])) --> [Taken].
verb(verbo([follow])) --> [followed].
verb(verbo([harvest])) --> [harvested].
verb(verbo([analyse])) --> [analysed].
verb(verbo([release])) --> [released].
verb(verbo([treat])) --> [treated].
verb(verbo([compare])) --> [compared].
verb(verbo([associate])) --> [associated].
verb(verbo([observe])) --> [observed].
verb(verbo([treat])) --> [treated].
verb(verbo([compare])) --> [compared].
verb(verbo([observe])) --> [observed].
verb(verbo([observe])) --> [observed].
verb(verbo([observe])) --> [observed].
verb(verbo([test])) --> [tested].
verb(verbo([test])) --> [tested].
verb(verbo([infect])) --> [infected].
verb(verbo([treat])) --> [treated].
verb(verbo([collect])) --> [collected].
verb(verbo([observe])) --> [observed].
verb(verbo([treat])) --> [treated].
verb(verbo([observe])) --> [observed].
verb(verbo([test])) --> [tested].
verb(verbo([determine])) --> [determined].
verb(verbo([detect])) --> [detected].
verb(verbo([repeat])) --> [repeated].
verb(verbo([observe])) --> [observed].
verb(verbo([release])) --> [released].
verb(verbo([take])) --> [Taken].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [is].
verb(verbo([mediate])) --> [mediated].
verb(verbo([show])) --> [shown].
verb(verbo([give])) --> [given].
verb(verbo([raise])) --> [raises].
verb(verbo([be])) --> [is].
verb(verbo([prove])) --> [proven].
verb(verbo([pursue])) --> [pursued].
verb(verbo([be])) --> [is].
verb(verbo([have])) --> [has].
verb(verbo([establish])) --> [established].
verb(verbo([be])) --> [is].
verb(verbo([approve])) --> [approved].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [is].
verb(verbo([mimic])) --> [mimics].
verb(verbo([approve])) --> [approved].
verb(verbo([note])) --> [noted].
verb(verbo([find])) --> [found].
verb(verbo([develop])) --> [developed].
verb(verbo([base])) --> [based].
verb(verbo([be])) --> [is].
verb(verbo([combine])) --> [combined].
verb(verbo([know])) --> [known].
verb(verbo([demonstrate])) --> [demonstrates].
verb(verbo([be])) --> [is].
verb(verbo([maintain])) --> [maintained].
verb(verbo([seed])) --> [seeded].
verb(verbo([plate])) --> [plates].
verb(verbo([remove])) --> [removed].
verb(verbo([replace])) --> [replaced].
verb(verbo([indicate])) --> [indicated].
verb(verbo([incubate])) --> [incubated].
verb(verbo([indicate])) --> [indicated].
verb(verbo([collect])) --> [collected].
verb(verbo([spin])) --> [spun].
verb(verbo([transfer])) --> [transferred].
verb(verbo([collect])) --> [collected].
verb(verbo([set])) --> [set].
verb(verbo([extract])) --> [extracted].
verb(verbo([perform])) --> [performed].
verb(verbo([incubate])) --> [incubated].
verb(verbo([perform])) --> [performed].
verb(verbo([perform])) --> [performed].
verb(verbo([use])) --> [used].
verb(verbo([calculate])) --> [Calculated].
verb(verbo([convert])) --> [converted].
verb(verbo([treat])) --> [treated].
verb(verbo([compare])) --> [compared].
verb(verbo([change])) --> [changed].
verb(verbo([fit])) --> [fitted].
verb(verbo([support])) --> [supported].
verb(verbo([be])) --> [is].
verb(verbo([betamediate])) --> [betamediated].
verb(verbo([be])) --> [is].
verb(verbo([affect])) --> [affects].
verb(verbo([target])) --> [targets].
verb(verbo([inhibit])) --> [inhibits].
verb(verbo([control])) --> [controlled].
verb(verbo([envelop])) --> [enveloped].
verb(verbo([localize])) --> [localizes].
verb(verbo([be])) --> [is].
verb(verbo([antagonize])) --> [antagonizes].
verb(verbo([inhibit])) --> [inhibits].
verb(verbo([emerge])) --> [emerged].
verb(verbo([control])) --> [controlled].
verb(verbo([be])) --> [is].
verb(verbo([infect])) --> [infected].
verb(verbo([indicate])) --> [indicated].
verb(verbo([take])) --> [taken].
verb(verbo([associate])) --> [associated].
verb(verbo([determine])) --> [determined].
verb(verbo([indicate])) --> [indicated].
verb(verbo([treat])) --> [treated].
verb(verbo([perform])) --> [performed].
verb(verbo([associate])) --> [associated].
verb(verbo([fit])) --> [fitted].
verb(verbo([indicate])) --> [indicated].
verb(verbo([propose])) --> [proposed].
verb(verbo([fall])) --> [falls].
verb(verbo([bind])) --> [binds].
verb(verbo([destabilise])) --> [destabilises].
verb(verbo([reduce])) --> [reduced].
verb(verbo([be])) --> [is].
verb(verbo([be])) --> [is].
verb(verbo([approve])) --> [approved].
verb(verbo([have])) --> [has].
verb(verbo([be])) --> [is].
